[#108] 티켓 집계 리팩토링
f-lab-edu/heeverse-ticket pull request #109
Opened 2023-11-07 05:56 UTC by gutenLEE

## 개요
- 관련 Issue 번호 : 
  - #82 
  - #108 

## 작업사항
- Contorller 와 Service DTO 결합도 낮추기

## 변경로직

### 변경전
- Controller DTO를 Service 계층으로 전달함
### 변경후
- Controller에서 서비스 계층용 DTO 생성하고 전달

2023-11-07 06:03 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/domain/dto/AggregateDto.java
> +        private int pageSize;
페이징 사이즈도 동적으로 변경되도록 변경했습니다.

2023-11-07 06:03 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/domain/dto/enums/StrategyType.java
>          };
이전 피드백에서 setter 로 전략패턴 주입했을때 사이드 이펙트로 **잘못된 인스턴스 주입**이 있었는데, 
enum 에서 인스턴스 타입 **패턴매칭 로직**이 있으므로 유효성 검사 역할도 수행한다고 생각합니다

2023-11-07 06:03 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateSelectMapperDto.java
> +        }
`AsynchronizableAggregation`, `synchronizableAggregation` 인터페이스는 별개로 존재하는데 

```java
public interface SynchronizableAggregation {

    List<AggregateDto.Response> aggregate(
            AggregateSelectMapperDto.Request aggrDto,
            boolean useNormalization
    );
}

public interface AsynchronizableAggregation {
    void aggregate(AggregateSelectMapperDto.Request request);

}
``` 

DTO는 같은걸 사용하다보니 query과 전략객체로 처리용 DTO 생성 분기문이 생겼습니다. 
이럴 떄는 DTO도 분리하는게 더 적합했을까요?

2023-11-07 06:03 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/reader/AggregationReaderTest.java
개발이 완료되어 멱등성 있는 테스트코드로 전환 작업중입니다

2023-11-07 12:26 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateSelectMapperDto.java
> +        }
DTO를 공용으로 만들어두고 더 많은 역할을 수행하도록 만들수록 점점 더 그 DTO는 수정하기 어려워지며, 담당하는 역할이 커지게 됩니다. 뭔가 수정사항이 생기면 이 DTO를 수정하기 어렵기 때문에, 내부 변수를 추가하거나 덧입히는 형식으로 DTO는 점점 더 커지게되며 결국 관리하기 어려운 DTO가 됩니다. 이걸 보통 `fat DTO`라고 부릅니다.

이와 관련된 논의는 [One big fat DTO vs multiple skinny DTO] 라는 키워드로 찾아보시면 좀 더 많은 정보를 찾아볼 수 있고, 정답이 없는 문제이기 때문에 본인만의 개발 철학을 계속해서 고민하며 근거를 댈 수 있다면 어떤 방식으로 개발하든 좋을 것으로 보입니다.

단, 단순히 이렇게 하니 편리하더라~ 와 같이 추상적인 이유는 납득하기 어려우므로 명확한 근거를 고민해보는게 좋겠네요.

2023-11-08 12:09 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/reader/AggregationReaderTest.java
멱등성 있는 테스트로 전환하였습니다. 
집계 쿼리 문법 중 H2에서 제공하는 문법이 없어 제거하였습니다.

2023-11-08 12:09 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/reader/firstclass/ResultMapUnitTest.java
병렬 프로그래밍에서 `ResultMap` 의 안전성 확인을 위한 테스트코드 입니다

2023-11-08 12:31 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateSelectMapperDto.java
> +        }
개인적으로 자료구조로서 DTO는 필요한 데이터만 정확하게 전달하는 것이 적합하다 생각합니다!
자료구조로서 DTO는 상태를 노출시키기 때문에 불필요한 필드를 Null 상태로 두는 것은 예외 발생 여지를 남기는 것 같습니다.

2023-11-08 13:49 UTC, f-lab-maverick requested changes
고생하셨습니다~ 코멘트 확인 부탁드려요

2023-11-08 13:49 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/domain/dto/AggregateDto.java
> +            this.pageSize = pageSize == 0 ? DEFAULT_SIZE : pageSize;
`pageSize`로 0 미만이 들어올 경우도 고려해주시면 좋겠네요~

2023-11-08 13:49 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +    concert_seq      int      null
여기는 왜 bigint에서 int로 변경되었나요?

2023-11-08 13:49 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +    concert_seq     int                                not null,
`concert_seq`가 어떤 테이블은 bigint고 어떤 테이블은 int네요. 이렇게 타입이 불일치하면 결국 데이터를 저장할 수 있는 범위도 불일치하게되어 여러 문제가 발생하지 않을까요?

2023-11-08 13:49 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/reader/firstclass/ResultMapUnitTest.java
> +    @DisplayName("새로운 key 인 경우 add 테스트")
테스트명은 정확히 어떤 조건에서 어떤 결과에 대한 테스트라는 것이 명확하게 나타날 수 있어야 합니다. 
테스트가 깨질 경우 테스트명을 보고 어느정도 유추할 수 있어야 해요.

예를 들자면, [새로운 key를 add할 경우 ~~해야 한다] [기존 key를 add할 경우 실패해야 한다]
와 같은 네이밍을 들 수 있겠네요.

2023-11-09 07:00 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateSelectMapperDto.java
> +            @Min(0)
`The annotated element must be a number whose value must be higher or equal to the specified minimum.`
[링크](https://jakarta.ee/specifications/bean-validation/3.0/apidocs/?jakarta/validation/constraints/Min.html)
문서를 확인하니, `@Min(0)`일 경우 concertSeq에 0입력도 가능한것 같습니다.

2023-11-09 07:03 UTC, ZhenxiKim commented on src/main/resources/schema.sql
> +(
해당 테이블에 pk가 없는 이유는 무엇인가요?

2023-11-09 07:54 UTC, gutenLEE commented on src/main/resources/schema.sql
> +(
성능 비교용으로 만든 테이블이라 PK를 지정 안했습니다..
innodb엔진은 PK가 없을 경우에 auto_increment 컬럼을 내부적으로 알아서 만들어주지만 
명시적으로 선언할 것을 권장하고 있으니 다음엔 추가하겠습니다

2023-11-09 07:54 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateSelectMapperDto.java
> +            @Min(0)
아하 감사합니다! 수정하겠습니다

2023-11-09 07:55 UTC, gutenLEE commented on src/main/resources/schema.sql
> +    concert_seq      int      null
아 신경을쓰지 못했네요... 챙기겠습니다!

2023-11-09 07:55 UTC, gutenLEE commented on src/main/resources/schema.sql
> +    concert_seq     int                                not null,
주의하겠습니다!

2023-11-10 10:40 UTC, gutenLEE commented
컨펌 후 머지합니다

2023-11-10 10:40 UTC, merged