[#2] 회원가입 - requestDTO 정규표현식 적용 및 비밀번호 암호화
f-lab-edu/heeverse-ticket pull request #11
Opened 2023-07-20 10:23 UTC by ZhenxiKim

## 개요
- 관련 Issue 번호 : #2 

## 작업사항
- 회원 requestDTO 정규표현식 적용
- 비밀번호 암호화 적용

## 변경로직
- 정규표현식 상수로 변경
- 공통 BaseEntity 추상클래스로 변경

2023-07-20 11:21 UTC, gutenLEE commented on src/main/java/com/heeverse/member/domain/entity/Member.java
> +    private Long memberId;
저희가 고민했던 PK 종류 UUID 와 Sequential ID 차이점이 보안 측면에서도 있었습니다. 

Sequential ID 는  숫자다 보니 외부에 노출하는 시퀀스일 경우 
시퀀스 추측 가능성이 있어 비정상적인 자원 요청 발생 위험이 있습니다. 

UUID 는 반대로 추측이 어렵답니다. 
하지만 단점도 있는데, PK 로 사용할 경우 bigint 보다 2배 큰 크기, 그리고 인덱싱이나 select 쿼리 시 성능 저하 문제 등이 있습니다. 

그래서 UUID 와 Sequential ID 를 같이 사용하는 경우도 있다네요! 

Member 엔티티도 고민을 해봤는데 Member 의 경우 로그인 인증 과정을 거치기 때문에 
UUID 까지는 필요 없을 것 같습니다.  정희님 의견도 궁금합니다!

2023-07-20 14:09 UTC, f-lab-maverick requested changes
이번에는 수정했으면 하는 사항이 있습니다.
코멘트 읽어보신 후 답변/수정 부탁드려요~

2023-07-20 14:09 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/domain/entity/Member.java
> +    private Long memberId;
일반적으로는 시퀀스 노출이 아닌, `email` 또는 `id`에 유니크 조건을 두고, url에 id나 email을 노출하기도 합니다. github의 경우에도 아래처럼 URL을 설계했죠
https://github.com/ZhenxiKim

URL에 굳이 시퀀스 값을 노출하지 않아도 되니, 이 부분은 자유롭게 고민해보셔도 좋을 것으로 보입니다. 

추가적으로, 시퀀스가 노출된다면 보안적으로 왜 취약하다고 생각하시나요?

2023-07-20 14:09 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/domain/entity/Member.java
> +    @Builder
만약, 빌더를 사용할 때 password와 같은 값을 주입하지 않은채로 build하면 어떤 일이 발생할까요?

2023-07-20 14:09 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/dto/MemberRequestDto.java
> +@Getter
필요한 lombok 어노테이션만 사용하는것 좋습니다 👍

2023-07-20 14:09 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/dto/MemberRequestDto.java
> +    static final String EMAIL_REGEX = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
이러한 정규식을 `MemberRequestDto`에서만 사용할까요? Service 레이어에서 이 정규식을 사용할 때 `MemberRequestDto.MEMBER_ID_REGEX` 형식으로 참조하게 될텐데, 정규식의 위치가 여기 있어야 할까요?

2023-07-20 14:09 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/service/MemberService.java
> +    }
이 메서드는 Service 레이어임에도 불구하고, HTTP와 연관된 HTTP Status를 리턴하고 있습니다.
Controller의 책임이 Service레이어까지 전파된건 아닌지 고민해 보시는게 좋을 것으로 보입니다.

만약, 다른 Service에서 이 메서드를 호출한다면 리턴값으로 HttpStatus가 올텐데 이게 과연 Service 레이어에서 적절한 리턴값일까요?

[MVC 모델](https://developer.mozilla.org/ko/docs/Glossary/MVC)에서는 컨트롤러가 사용자에 입력을 받고, 응답을 생성해주는 역할을 하는 것으로 정의되어 있습니다. 위 문서를 한번 읽어보시는게 도움이 될 것으로 보이네요~

추가적으로 더 알아보고 싶다면, layered architecture 라는 키워드를 찾아보시는 것도 도움이 될 것으로 보입니다.

2023-07-20 14:09 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/service/MemberService.java
> +    }
다른 개발자가 메서드명이 `is~`로 시작된다면 리턴값으로 boolean형태를 리턴할 것으로 기대할 것입니다. 아직 내부 구현이 완료되지 않아 내부에서 적절하지 않은 값이라면 `throw ~`를 해줄지, 리턴으로 boolean값을 내려줄지 정해지지 않았는데요, 각 상황에 맞는 적절한 메서드 시그니처를 가져갈 수 있도록 해주세요~

2023-07-20 14:09 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/dto/MemberRequestDtoTest.java
> +    @ValueSource(strings = {"홍길동", "Romeo", "데이비드 Kim"})
👍

2023-07-20 14:50 UTC, gutenLEE commented on src/main/java/com/heeverse/member/domain/entity/Member.java
> +    private Long memberId;
auto increment 로 생성된 시퀀스가 노출되면 다음 시퀀스를 예측할 수 있기 때문에 
크롤링으로 자원을 전부 취득하는 등 문제가 발생할 수 있습니다

2023-07-20 15:07 UTC, gutenLEE commented on src/main/java/com/heeverse/member/domain/entity/Member.java
> +    @Builder
어노테이션 프로세싱 결과 코드를 확인해보니 
password 같은 필수값도  null 이 허용된다는걸 확인했습니다. 

```java
  public MemberBuilder password(String password) {
      this.password = password;
      return this;
  }
````

수정하겠습니다

2023-07-20 15:20 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/domain/entity/Member.java
> +    private Long memberId;
적절하지 않은 사용자가 자원을 취득하지 못하도록 막는게 인증/인가 아닐까요?
단순히 접근 가능한 URL만 노출된다고 정보가 유출되는 것은 Secure coding 에 대해 고려하지 않은 것으로 보일 수 있습니다. 모든 API에는 적절한 인증/인가 접근제어가 필요합니다~

2023-07-21 02:37 UTC, gutenLEE commented on src/main/java/com/heeverse/member/domain/entity/Member.java
> +    private Long memberId;
아하 모든 API에는 인증/인가 접근제어 고민해보겠습니다

2023-07-21 09:57 UTC, f-lab-maverick approved these changes
확인하였습니다~ 코멘트 확인 부탁드리고, 수정해서 푸시 후 머지해주세요~

2023-07-21 09:57 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/util/RegexUtils.java
> +    }
👍

2023-07-21 09:57 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/controller/MemberController.java
> +    @ResponseStatus(HttpStatus.OK)
자원을 생성하는 행위는 200 리턴도 좋지만, 좀 더 REST한 API를 만들기 위해서는 201 CREATED를 반환해주는게 어떨까요?
각 상황에 어떤 HTTP Status를 리턴해줄지 애매하다면 아래 문서를 참고해보세요.
https://learn.microsoft.com/ko-kr/azure/architecture/best-practices/api-design#post-methods

2023-07-21 09:57 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/service/MemberService.java
> +    }
아직 DB에 대한 로직이 존재하지 않지만, 이런 데이터를 다루는 메서드에는 반드시 `@Transactional` 메서드를 사용해주세요. 사용하지 않는다면 트랜잭션이 제공해주는 많은 기능을 사용할 수 없습니다.

트랜잭션의 기능은 DB관련된 기능이 많으므로, 이 부분은 Real MySQL을 공부할 때 더 익히실 수 있을거에요~

2023-07-21 09:57 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/service/MemberService.java
> +        }
코드 블럭 내부에 변수가 많을수록 코드를 읽기 어려워집니다.
이렇게 조건으로만 사용하는 변수의 경우 짧게 줄여주시면 불필요한 변수 선언을 줄일 수 있습니다. 코드 읽기도 더 쉬워져요~
```suggestion
        if (isExistMember(memberRequestDto)) {
            throw new DuplicatedMemberException();
        }
```

2023-07-21 09:57 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/dto/MemberRequestDtoDuplicatedMemberException.java
일반적으로 테스트의 경우 클래스 끝에 `~~Test`와 같은 네이밍 규칙을 가지게 됩니다.
이 클래스가 테스트 용도라는걸 명시해주는 것인데요, 클래스 네이밍을 변경해주시는게 어떨까요?

2023-07-21 10:12 UTC, gutenLEE commented on src/test/java/com/heeverse/member/dto/MemberRequestDtoDuplicatedMemberException.java
> +class MemberRequestDtoDuplicatedMemberException {
테스트 클래스명이 잘못 바뀐 듯한데 맞을까요?!

2023-07-21 10:12 UTC, gutenLEE commented on src/main/java/com/heeverse/member/controller/MemberController.java
> +    public void register(@RequestBody @Valid MemberRequestDto memberRequestDto) {
void 로 변경하신 이유가 궁금합니다!

2023-07-22 05:49 UTC, ZhenxiKim reviewed
작성한 코드에 대한 내용정리 첨언했습니다.

2023-07-22 05:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/service/MemberService.java
> +            .password(passwordEncoder.encode(memberRequestDto.getPassword()))
비밀번호 암호화를 서비스 계층에서 처리했는데, 멤버 도메인의 기능으로 볼 수 도 있을거같아서 Member.class에 넣을지 고민했었습니다. 다른분들의 의견은 어떤지 궁금합니다.

2023-07-22 05:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/domain/entity/Member.java
> +    @Builder
필수값 필드에 null이 셋팅될 수 있는 위험이 발생합니다. 아래 블로그에 정리한 두가지 방법 중 @NotNull을 사용하여 null에 대한 위험을 제거하였습니다. 
https://zhenxikim.tistory.com/81

2023-07-22 05:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/dto/MemberRequestDto.java
> +    static final String EMAIL_REGEX = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
어떠한 레이어에 종속되지 않고 하나의 클래스에서 관리 포인트를 둬서 관리하기 쉽게 common 패키지의 util클래스로 빼서 수정하였습니다.

2023-07-22 05:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/exception/DuplicatedMemberException.java
> +@ResponseStatus(code = HttpStatus.CONFLICT)
클라이언트의 회원가입 요청 데이터와 서버측에 데이터가 충돌나는 로직이므로 Status code 409(Conflict-요청이 현재 서버와 충돌날 경우)를 택했습니다.

2023-07-22 05:49 UTC, ZhenxiKim commented on src/test/java/com/heeverse/member/dto/MemberRequestDtoDuplicatedMemberException.java
클래스명이 완전 다른내용으로 들어가버렸네요ㅎㅎ 수정하겠습니다.

2023-07-22 06:08 UTC, ZhenxiKim commented on src/test/java/com/heeverse/member/dto/MemberRequestDtoDuplicatedMemberException.java
> +class MemberRequestDtoDuplicatedMemberException {
네~ 오타가 있었습니다 수정하겠습니다!

2023-07-22 06:10 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/controller/MemberController.java
> +    public void register(@RequestBody @Valid MemberRequestDto memberRequestDto) {
회원가입의 경우 리턴값을 줄 필요 없고 회원가입 성공 여부와 회원 가입할 내용이 이미 존재한다면 Exception을 리턴받기 때문에 void와 Http Status 코드로 처리하였습니다.

2023-07-22 06:31 UTC, merged

2023-07-22 07:04 UTC, gutenLEE commented on src/main/java/com/heeverse/member/service/MemberService.java
> +            .password(passwordEncoder.encode(memberRequestDto.getPassword()))
저의 생각은 멤버 도메인의 기능이 아니라고 생각합니다! 
보안을 위한 암호화라서 암호화된 패스워드가 멤버 객체의 행동의 결과인가? 라고 봤을때는 아니라는 생각이 듭니다!
또한 Member 클래스 내부에서 암호화를 하게되면 Member 가 Encoder 객체를 의존하게 되는데 이것이 가장 큰 단점 같습니다

2023-07-22 12:13 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/service/MemberService.java
> +            .password(passwordEncoder.encode(memberRequestDto.getPassword()))
멤버 도메인은 말그대로 멤버와 관련된 일을 해야합니다.
암호화와 복호화는 멤버도메인에 종속된 역할은 아니므로, 별도 로직으로 태우는것이 좋을 것으로 보이네요~

암호화를 멤버 도메인에 종속시키면 @gutenLEE 유희님이 말씀해주신대로 도메인이 별도 Bean에 의존해야하게 됩니다. 즉, 멤버 도메인은 암호화를 담당하는 객체 없이는 동작할 수 없게되므로 이는 도메인의 책임을 많이 부여하게 되는 부작용이 생길 수 있습니다.