refactor : read commited로 수정
f-lab-edu/heeverse-ticket pull request #111
Opened 2023-11-18 11:48 UTC by ZhenxiKim

## 개요
- 관련 Issue 번호 : #110 

테스트를 위해 트랜잭션 명을 출력하는 로그를 남겨놨습니다.

2023-11-18 11:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    @Transactional(propagation = Propagation.MANDATORY, isolation = Isolation.READ_COMMITTED)
부모 트랜잭션이 동일하게 유지되도록 전파속성을 MANDATORY로 설정했습니다.

2023-11-18 11:54 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
> +            //ticketOrderEventHandler.saveTicketOrderLog(new TicketOrderEvent(dto, memberSeq, ticketOrderSeq));
티켓 예매 로그를 남기는 부분은 티켓 예매 정합성 로그 확인을 위해 잠시 주석 처리 했습니다.

2023-11-20 11:07 UTC, ZhenxiKim commented on src/main/java/com/heeverse/config/RdsConnectionProps.java
> +public class RdsConnectionProps extends DataSourceProperties {
multi datasource로 설정할 경우 트랜잭션 공유가 되지 않아 rock이 유지 되지 않는 현상이 발생했습니다. datasource를 하나로 다시 변경하였습니다.

2023-11-20 11:09 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    @Transactional(propagation = Propagation.MANDATORY, isolation = Isolation.READ_COMMITTED, noRollbackFor = TicketNotNormallyUpdatedException.class)
TicketOrderService의 예매 기능의 트랜잭션에 포함되도록 전파 레벨을 MANDATORY로 지정하였습니다.
중첩 트랜잭션이다 보니 하위 트랜잭션에서 발생하는 예외처리에 대해 noRollbackFor가 명시되지 않으면 상위 트랜잭션에서 rollback되어 하위 트랜잭션에도 명시했습니다.

2023-11-20 11:10 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
> +            ticketService.checkBookedTicket(dto, reqTicketSeqList);
격리 수준을 낮추면서 발생할 수 있는 데이터 정합성 문제를 방지하기 위해, 방어코드를 락 잡는로직 앞 뒤로 추가하였습니다.

2023-11-20 13:32 UTC, f-lab-maverick requested changes
고생하셨습니다~ 리뷰 확인 후 답변부탁드립니다.

2023-11-20 13:32 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    @Transactional(propagation = Propagation.MANDATORY, isolation = Isolation.READ_COMMITTED, noRollbackFor = TicketNotNormallyUpdatedException.class)
Propagation이 MANDATORY라면 부모트랜잭션의 설정을 모두 따라갈텐데요, 중첩트랜잭션이라고 생각하신 이유가 있으신가요? 추가적으로, MANDATORY라면 신규 트랜잭션 생성을 하지 않을텐데 isolation level을 선언했을 때 정상동작할까요? isolation level은 트랜잭션 시작시 적용해주어야 적용됩니다~ MySQL에서는 Isolation level을 트랜잭션 도중 바꿀 수 없습니다.

2023-11-20 13:32 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    @Transactional(propagation = Propagation.MANDATORY, isolation = Isolation.READ_COMMITTED, noRollbackFor = AlreadyBookedTicketException.class)
이 부분도 마찬가지로, 부모트랜잭션 내부에서만 사용이 가능한 로직이라면 `isolation = Isolation.READ_COMMITTED`은 부모 트랜잭션에서 설정해야하지 않을까요?

2023-11-20 13:32 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +                .filter(d -> ObjectUtils.isEmpty(d.getOrderSeq()))
`ObjectUtils.isEmpty(d.getOrderSeq())`이 무준을 아직 하지 않은 티켓을 나타내는 비즈니스 로직이라면, 이런 형식으로 메서드 네이밍을 붙여서 가독성과 어떤 로직인지를 명시해줄 수 있습니다.
```suggestion
                .filter(d -> d.isNotOrdered())
```

```suggestion
                .filter(Ticket::isNotOrdered)
```

2023-11-20 13:32 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
> +            ticketService.checkBookedTicket(dto, reqTicketSeqList);
`SELECT FOR UPDATE`로 ticket을 조회하는 동시에 락을 잡을 수 있기 때문에, X-Lock을 사용할 때에는 이렇게까지 하지는 않아도 됩니다. 왜냐하면 X-Lock을 잡은 이후에는 다른트랜잭션에서는 락을 잡을 수 없어 대기상태로 기다릴 것이기 떄문에, `ticketService.getTicketLock`로 락을 잡는 동시에 조회하여 유효성 검증을 해도 되겠습니다. (이후에 유효성을 더 검증하지 않아도 됩니다)

Lock을 잡는 행위자체가 부담이 될 수 있기 때문에 Lock 이전에 Non-lock으로 유효성 검증을 한번 하는건 좋을거같습니다~

2023-11-20 14:31 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    @Transactional(propagation = Propagation.MANDATORY, isolation = Isolation.READ_COMMITTED, noRollbackFor = TicketNotNormallyUpdatedException.class)
아 새롭게 시작되는 트랜잭션이 아니어서 중첩 트랙잭션이라는 명칭은 알맞지 않군요~
부모트랜잭션에서 시작되므로 격리수준은 부모 트랜잭션에만 명시했습니다.

2023-11-20 14:32 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
> +            ticketService.checkBookedTicket(dto, reqTicketSeqList);
X-Lock은 트랜잭션 기반한 락이므로 추가 유효성 검사는 없어도 되겠군요!

2023-11-20 14:54 UTC, f-lab-maverick approved these changes
확인하였습니다. 고생하셨어요~

2023-11-21 06:05 UTC, merged