[#113] 인증&인가 리팩토링
f-lab-edu/heeverse-ticket pull request #114
Opened 2023-12-07 11:06 UTC by gutenLEE

## 개요
- 관련 Issue 번호 : #113

## 목표
1. JwtTokenProvider 클래스 분리 : JwtDecoder와 JwtProvider로 분리
2. 토큰 만료 시 리프레시 토큰 생성 로직 추가

2023-12-07 11:07 UTC, gutenLEE commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
리팩토링할 클래스여서 주석 처리했습니다

2023-12-08 10:28 UTC, ZhenxiKim commented on src/main/java/com/heeverse/config/VaultOperationService.java
> +        return Objects.requireNonNull(operations.get(secrets)).getRequiredData();
static method여서 클래스명은 빼도 될 것 같습니다.

2023-12-08 10:52 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> +            @AuthenticationPrincipal AuthenticatedMember member
인증에 필요한 정보만 담은 객체를 따로 생성하신건가요?

2023-12-08 10:53 UTC, ZhenxiKim reviewed
리뷰 완료했습니다.

2023-12-08 12:43 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> +            @AuthenticationPrincipal AuthenticatedMember member
맞습니다!
filter 레이어에서 조회한 Member 엔티티를 계속 들고 다니기 보다는 
필요한 상태만 담은 객체를 만들어봤습니다. 
그리고 인증이 완료된 유저라는 의미를 명확하게 표현할 수 있어서 만들어봤습니다.

2023-12-09 01:52 UTC, f-lab-maverick requested changes
리팩토링에 어려움을 겪고 있다고 하시던데요, 그 부분은 리팩토링의 목적이 명확하지 않기 떄문인 것으로 보입니다.

잘 작동하고 문제없는 코드를 왜 바꾸어야할지가 본인 스스로 납득되지 않으면 코드 리팩토링은 방향을 잃고뭘 바꿔야할지도 모른 채 그저 보이는 코드를 약간 수정하고 종료되는 경우가 많습니다.

가독성이 좋은 코드를 만든다면 클린 코드라는 책을 추천드립니다. 이 책의 모든 부분이 다 완벽한 것은 아니지만, 깔끔한 코드를 고민한다면 충분히 한번 쯤 읽어볼만한 책입니다.

제가 드린 리뷰 수정 후 다시 리뷰요청 해주세요~

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/dto/AuthenticatedMember.java
> +    private final long seq;
이 `seq`라는 상태는 사용하지 않는 것으로 보이고, 어떤 seq인지도 불명확하네요.
`AuthenticatedMember.seq` 라고했을 때 어떤 시퀀스인지 알 수 있도록 명확한 네이밍 룰이 필요해 보입니다. 필요하지 않은 상태라면 제거해도 좋습니다.

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/dto/AuthenticatedMember.java
> +}
관습적인 생성자 코드는 `@RequiredArgsConstructor`로 축약하여 코드량을 줄이는 것도 좋습니다. 자바는 동일한 코드가 많이 나오기 떄문에 코드량을 줄여주는것도 가독성에 좋습니다.

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JsonAuthenticationFilter.java
> +        response.setHeader(HttpHeaders.AUTHORIZATION, TOKEN_TYPE + StringUtils.SPACE + jwtProvider.generateToken(authentication));
`TOKEN_TYPE + StringUtils.SPACE + jwtProvider.generateToken(authentication)`

이 부분은 비즈니스로직으로 볼 수 있습니다. 별도 메서드로 분리해주시는게 좋겠습니다.

상수를 사용해주신 부분은 좋네요~ 또 다른 방식으로는 이렇게 덧셈형식으로 토큰 형태를 생성해주는것이 아닌, format을 사용하여 이 토큰이 어떤 형태인지를 한눈에 볼 수 있게 하는것도 괜찮겠습니다.


```
String.format("%s %s", TOKEN_TYPE, jwtProvider.generateToken(authentication))
```

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
> +        Authentication authentication = null;
`SecurityContextHolder.getContext().setAuthentication(jwtProvider.getAuthentication(token););`

이와같이 코드를 변경하면 `authentication` 변수가 필요하지 않겠네요.

변수 선언 후 null을 할당하거나, 다른 값을 재할당하는 것은 해당 변수를  개발자가 계속 트래킹해야하기 때문에 휴먼 에러의 가능성을 높이고 가독성을 떨어뜨립니다. null 선언은 최대한 지양해주세요.

추가적으로, 이런 변수 선언시 `final`키워드를 반드시 붙여주시는것도 깔끔한 코드 작성에 큰 도움이 됩니다. 변수에 값을 재할당해야 하는 경우라면 차라리 새로운 변수를 생성해주는것이 더 읽기 편한 코드가 되는 경우가 많습니다.

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
> +            String token = request.getHeader(HttpHeaders.AUTHORIZATION).replaceAll(TOKEN_TYPE, "").trim();
이런 `token`변수도 final 선언을 해주면 불변성이 보장됩니다.

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
> +        } catch (ExpiredJwtException e) {
`ExpiredJwtException`이 아닌 다른 예외가 발생했을 경우에는 어떻게 처리할지도 고려 되었나요?

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtDecoder.java
> +                .getBody();
```
Jwts.parserBuilder()
                .setSigningKey(key)
                .build()
```
이 코드를 실행하면 `JWTParser`가 나오는데요, 헤더를 파싱할 때 마다 이 parser를 새로 만들 필요가 있나요?

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtDecoder.java
> +        return claimMap;
Map, List, Set등의 컬랙션을 리턴할 때에는 이 컬랙션이 변경되지 않도록 불변형태의 컬랙션을 사용해주셔야 합니다. `immutableMap`의 키워드를 찾아보시고 자료구조 리턴시에는 내부 형태가 변경되지 않도록 신경써서 전달해주세요.

자료구조가 여러 메서드를 거치며 내부 상태가 변경되는 코드가 생기면 그 코드는 점점 더 파악하기 어려워지고 변경이 불가해집니다.

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtProvider.java
> +    public boolean validate(String token) throws AuthenticationException {
`throws AuthenticationException` 이게 꼭 필요한 시그니처인가요?

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtProvider.java
> +    public boolean validate(String token) throws AuthenticationException {
이 메서드는 validation에 실패할 시 예외를 던지고 있습니다. 그렇다면 return값이 필요 없을 것으로 보이네요~

2023-12-09 01:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/LoginAuthenticationProvider.java
> +        return new UsernamePasswordAuthenticationToken(member, null, getAuthority());
생성자 파라미터로 null을 주고 있군요. 패스워드를 안주기 위해 그런 것으로 보이는데, 이렇게 null값을 넘견주는 생성자는 NPE가능성이 높습니다. 소스코드에서 직접적으로 null을 할당하고 넘기고 다루는것은 최대한 지양해주세요.

2개의 파라미터만 받는 생성자를 별도로 만들어 주는것이 더 명시적이고 깔끔한 로직으로 보이네요.

2023-12-27 14:31 UTC, closed without merging