[#4] 로그인 기능 중 멤버 정보 조회 필터
f-lab-edu/heeverse-ticket pull request #13
Opened 2023-07-23 11:49 UTC by gutenLEE

## 개요
- 관련 Issue 번호 : #4 
- 작업 커밋 : dc31499bf6648d58ebde12556054d6758258e116 (pull 을 했더니 해당 브랜치 커밋까지 다 딸려왔네요.. 다음엔  rebase 를 사용해보겠습니다)

## 작업사항

![image](https://github.com/f-lab-edu/heeverse-ticket/assets/61870748/3846c78f-eb79-459c-b7ef-869f3812db84)
1. `JsonAuthenticationFilter.class`  생성 : json 데이터를 Dto 로 맵핑 처리를 하는 필터
2. `LoginAuthenticationProvider.class` 생성 : 인증 로직 수행 

## 변경로직

1. PasswordEncoder 구현 Bean 을 `SecurityConfig` 클래스에 선언했습니다. 
   회원가입 시  기존 `PwdEncoder` 대신 이 Bean 을 사용하는 것으로 변경하고 
   추가 기능이 늘어나면 클래스로 분리하는 것을 제안해봅니다.

2023-07-23 12:01 UTC, gutenLEE commented on src/main/java/com/heeverse/member/dto/LoginDto.java
JDK14 에 도입된 불변 객체를 만들어 주는 record 타입을 사용해봤습니다. 
불변의 VO 클래스부터 사용해보면 좋을 것 같습니다.

1. 불변 상태를 만들기 위한 어노테이션들을 추가하거나 setter 를 선언할 방법이 없어서 믿고 사용할 수 있습니다.
2. getter 메서드 호출시 `get_` prefix 가 붙지 않아 가독성이 좋습니다.

2023-07-23 12:01 UTC, gutenLEE commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
Spring Security 에서 `formLogin()` 을 사용하면 Content-Type이 x-www-form-urlencoded인 방식으로만 데이터를 받을 수 있습니다. 
REST API 개발 목적에 맞게 로그인도 JSON 으로 데이터를 처리할 수 있도록 했습니다.

2023-07-24 04:49 UTC, ZhenxiKim reviewed
리뷰완료했습니다!

2023-07-24 04:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/controller/LoginController.java
> +public class LoginController {
login행위는 member 도메인의 행위로 생각 되서, MemberController에서 처리해도 괜찮을거같습니다. 아니면 인증관련한 컨트롤로러 AuthenticationControlle와 같은 명칭도 괜찮을거같습니다.

2023-07-24 04:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/controller/LoginController.java
> +        return "done auth";
프론트 서버와의 통신을 위해 로그인 성공, 실패 HttpStatusCode와 어떤 회원의 로그인 정보인지 알 수 있도록 제공하는 것이 좋을 거 같습니다.

2023-07-24 04:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/dto/LoginDto.java
코드양이 줄어들어서 좋네요~
추가적으로 login요청시 사용하는 dto일 경우 requestDTO같이 명칭이 붙으면 정확한 용도를 파악하기 쉬울거같습니다.

2023-07-24 04:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
ObjectMapping관련 여러 라이브러리가 있는데 그 중 ObjectMapper를 선택하신 이유가 궁금합니다.

2023-07-24 04:55 UTC, gutenLEE commented on src/main/java/com/heeverse/member/dto/LoginDto.java
아 requestDto  으로 하기로 했었죠 변경하겠습니다!

2023-07-24 04:58 UTC, gutenLEE commented on src/main/java/com/heeverse/member/controller/LoginController.java
> +        return "done auth";
앗 테스트를 위해 임시로 만든 엔드포인트인데 저렇게 두면 안될것같네요... 
다음부턴 테스트 코드에서 확인할 수 있도록 테스트코드 학습 하겠습니다

2023-07-24 11:53 UTC, f-lab-maverick requested changes
고생하셨습니다~ 여러 시도를 하시는게 눈에 보이네요.
테스트도 작성하려고 노력하시는 모습 좋습니다. 이렇게 계속 작성 연습 지속해주세요.
남긴 코멘트 확인 후 수정 부탁드립니다~

2023-07-24 11:53 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/JacksonConfig.java
> +    }
Spring boot에서는 `ObjectMapper`를 이미 Bean으로 관리하고 있습니다.
추가적으로 빈을 등록해주신 이유가 있으신가요? 별도 커스텀 설정을 하기 위함이 아니라면 별도로 등록할 필요는 없어 보입니다.

2023-07-24 11:53 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
`ObjectMapper`를 이미 bean으로 선언해 두었는데 여기서는 신규로 객체를 생성하고 있네요.
객체 생성도 비용이고, 이렇게 ObjectMapper를 신규로 생성하여 사용한다면 bean 생성시 적용한 설정이 적용되지 않을 것으로 보입니다.

물론 이 Filter 자체는 bean이 아니므로 자동 주입이 안되겠지만 이는 직접 생성자 주입을 통해 DI를 적용해보는건 어떠신가요?

2023-07-24 11:53 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
> +        } catch (IOException e) {
불필요한 공백이 보이네요~ 이런 부분도 가독성에 영향을 미칩니다.

2023-07-24 11:53 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
> +        String body = request.getReader().lines().collect(Collectors.joining());
Request에서 body를 읽는 행위를 진행하면 이후 body 내용이 소실됩니다.
꽤나 중요한 내용이니 [이 글](https://www.baeldung.com/java-servletrequest-illegalstateexception)을 참고해 주시고, Request에서 stream을 읽어야할 필요가 있을 경우 이러한 내용을 고려해서 작성해주세요~

2023-07-24 11:53 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
> +    }
메소드에서 `throws IOException` 형식으로 예외를 전파하면 이 메서드를 사용하는 모든 메서드에서는 이 예외에 대한 처리를 해주어야 합니다.
IOException은 복구가 불가능한 예외이므로 아래처럼 wrapping을 통해 내부에서 예외를 처리하여 사용하는쪽에서 불필요한 중복 예외처리를 하지 않을 수 있도록 변경해주세요~

```
try {
   
} catch (IOException e) {
    throw new RuntimeException(e);
}
```

2023-07-24 11:53 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/LoginAuthenticationProvider.java
> +    }
`"USER"` 같은 리터럴은 상수로 관리해주세요~

2023-07-24 11:53 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +                )
`addFilter`, `addFilterBefore`, `addFilterAfter`, `addFilterAt` 이것이 어떤 차이가 있는지도 찾아보시는게 좋아보입니다~

2023-07-24 11:53 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/controller/LoginController.java
> +public class LoginController {
Login을 member로 처리할지, 별도 도메인으로 처리할지 고민하는 포인트가 좋은 포인트로 보이네요.

이러한 고민은 도메인별로 모든 레이어를 만들기 때문에 발생합니다. 이렇게 레이어를 구성하였을 경우 도메인이 2개 이상 포함된 비즈니스 로직이 발생한다면 어떤 Service클래스에 로직을 둘지, 어떤 Controller에 만들지 고민하게 됩니다.

관심사별로 Controller, Service를 생성해보는것도 고민해보시면 좋을 것으로 보이고, 정답은 없으므로 장단점을 비교해서 정해주시면 될거같습니다~

2023-07-24 11:53 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/controller/LoginController.java
> +        return "done auth";
현재 적용된 Security 설정을 사용한다면 이 엔드포인트가 필요하지 않을 것으로 보이네요

2023-07-24 11:53 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginControllerTest.java
> +class LoginControllerTest {
`@SpringBootTest`로 어느정도 축약할 수 있습니다~

2023-07-25 11:59 UTC, gutenLEE commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
JsonAuthenticationFilter 로 생성자 주입을 하려니 SecurityConfig 클래스에서도 주입을 받아야 하는데
ObjectMapper 가 필요한 곳에만 주입을 받자는 의도였습니다. 
하지만 객체 생성비용을 같이 고려하지 못했네요... 고민해보겠습니다!

2023-07-25 12:14 UTC, gutenLEE commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +                )
`FilterOrderRegistration` 클래스는 필터의 적용 순서를 보관하는 클래스 입니다. 

- `addFilterBefore`, `addFilterAfter`은 두번때 파라미터 필터의 순서 앞, 뒤로 등록한다. 
- `addFilterAt`은 두번때 파라미터 필터와 똑같은 순서에 등록한다. 
- `addFilter`은  `FilterOrderRegistration` 에 필터 순서를 조회 정보를 요청합니다. 있으면 해당 위치에 등록하고 없으면 예외가 발생합니다. 

JsonAuthenticationFilter 는 UsernamePasswordAuthenticationFilter와 동일한 순서로 등록되도록 
`addFilterAt` 를 적용하면 좋을 것 같습니다.

2023-07-26 10:03 UTC, gutenLEE reviewed
로그인 멤버 인증 필터에서 멤버 정보 조회하여 credential 비교 로직 추가했습니다.

2023-07-26 10:03 UTC, gutenLEE commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
ObjectMapper 이 스프링 내장이여서 사용하였습니다. 

추가로 Gson 도 검색을 해보았는데, 
데이터 크기나 처리 개수에 따라 라이브러리 마다 성능 차이가 있다는 것을 알게되었습니다.  
큰 사이즈(100MB 이상) JSON 처리엔 jackson, 작은 용량은 Gson 이 성능에서 우수하다고 합니다

2023-07-26 10:03 UTC, gutenLEE commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +    private final ObjectMapper objectMapper;
ObjectMapper 에 별다른 설정이 필요하지 않아 스프링이 빈으로 등록해둔걸 사용하려다보니
JsonAuthenticationProvider`로 의존성 주입을 위해 SecurityConfig 도 주입을 받았습니다. 
설정 컴포넌트에도 생성자 주입을 선언하는게 괜찮은지 궁금합니다!

2023-07-26 10:03 UTC, gutenLEE commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
> +            request = new ContentCachingRequestWrapper(request);
`ContentCachingRequestWrapper` 를 사용하면 
- getReader(), getInputStream()  을 여러번 호출해도 `IlligalStateException` 발생하지 않는다
- 하지만 한 필터에서 body Content 스트림을 소비하면 다른 필터가 스트림을 또 다시 소비할 수 없는 문제는 여전히 남아있다.
까지 확인했습니다.

2023-07-27 06:14 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/StubMemberService.java
아직 DB 연동을 안해서 Stub 을 사용해봤습니다. 
Stub 은 MemberService 를 상속함으로써 MemberService 가 변경되면 
`@Override` 주석이 달린 메서드도 영향을 받을텐데
이런 Stub 은 개발 초기에만 사용하고 나중엔 제거를 하는지 궁금합니다.

2023-07-27 06:14 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +@SpringBootTest(properties = "spring.main.allow-bean-definition-overriding=true")
Stub 객체를 주입받는 방법을 시도해봤습니다.  bean overriding 이 가능하도록 했습니다.

2023-07-27 09:06 UTC, ZhenxiKim reviewed
오늘 리뷰는 하나밖에 못했습니다. 분발해보겠습니다

2023-07-27 09:06 UTC, ZhenxiKim commented on src/main/java/com/heeverse/config/Authority.java
> +public class Authority {
권한 클래스를 en um 클래스로 변경하여 en um 클래스에서 제공하는 메소드를 사용하거나 권한을 파라미터로 받는 코드에서 enum 클래스로 정의함으로써, 다른 static final String 값이 들어오지 못하게 막을 수 있을 거 같습니다.

2023-07-27 14:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +    private final ObjectMapper objectMapper;
네~ 설정 컴포넌트도 빈 주입이 가능합니다. 직접 만들지 빈을 사용할지는 선택사항으로 생각해주시면 될거같네요.

2023-07-27 14:33 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/StubMemberService.java
이런 형식으로도 테스트를 할 수 있지만, 내부 Repository등을 Mock으로 사용하는 방식을 좀 더 선호하기는 합니다.
왜냐하면 테스트하고자 하는 대상이 Service클래스인데 실제 테스트하는건 Stub Service가 되는 것이라서 차이가 날 수 있기 때문이에요.

2023-07-27 14:36 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +@SpringBootTest(properties = "spring.main.allow-bean-definition-overriding=true")
이러한 테스트 전용 속성이 필요하다면 test용 properties 파일을 생성해서 관리해주시는건 어떨까요?

2023-07-27 15:47 UTC, f-lab-maverick approved these changes
확인하였습니다~
테스트코드쪽에 약간의 코멘트를 남겨두었습니다.
확인부탁드리고 이후 작업하실 때 고민해보시면 좋은 고민포인트가 될 것으로 보입니다~

2023-07-27 15:47 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
> +    }
👍

2023-07-27 15:47 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
> +            request = new ContentCachingRequestWrapper(request);
기존 선언된 변수에 다른 객체를 할당하는건 그리 좋은 선택은 아닙니다.
최초 선언된 객체와 다른 객체가 있으면 모든 코드를 꼼꼼히 봐야 이해할 수 있게되고 코드 흐름 파악에도 좋지 않은 영향을 줄 수 있기 때문에, 항상 선언시 상수로 선언하고, 필요하지 않은 변수는 선언하지 않는것이 좋아요~

이렇게 바꿔보시는건 어떤가요?
```
toLoginDto(new ContentCachingRequestWrapper(request));
```

2023-07-27 15:47 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/LoginAuthenticationProvider.java
> +    }
상수처리 좋습니다~

2023-07-27 15:47 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/service/MemberService.java
> +        return Optional.of(Member.builder().build());
회원 객체가 비어있는 상태로 생성될 수 있나요?
이렇게 불완전한상태로 객체 생성을 할 수 있다면 빌더패턴을 사용하지 않는게 좋지 않을까요?

2023-07-27 15:47 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +class LoginAuthenticationTest {
이 테스트는 Spring 컨테이너가 올라가고, 실제 DB까지 연결된 상태이기 때문에 통합테스트로 보아야 할 것으로 보이네요. 통합테스트로 한다면 개발서버 DB를 테스트용으로 사용하셔도 되고, 테스트전용 인메모리 DB를 사용하셔도 좋습니다.

통합테스트에서 Mocking을 반드시 할 필요는 없어요~ 다만, 데이터 조작 이후 롤백될 수 있도록 `@Transactional` 어노테이션을 필수로 넣어주셔야 합니다.

2023-07-27 15:47 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +class LoginAuthenticationTest {
로그인에 대한 테스트를 한다면
1. 회원가입 (회원 생성)
2. 로그인
이 두가지 스텝이 필요할 것인데요, 이런 경우
회원 가입에 대한 통합테스트를 먼저 만들고, 로그인시 이 회원가입 테스트코드 메서드를 불러와 사용하면 좀 더 테스트를 편리하게 작성할 수 있습니다.

2023-07-27 15:47 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +    @DisplayName("로그인에 성공하면 HttpStatus 는 OK 다")
토큰도 같이 반환되는것을 확인해주면 좋을것 같네요~

2023-07-27 15:47 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/dto/RecordTypeTest.java
> +    }
학습테스트 좋습니다~ 👍

2023-07-27 23:52 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +@SpringBootTest(properties = "spring.main.allow-bean-definition-overriding=true")
아 그렇네요... 반영해보겠습니다!

2023-07-27 23:56 UTC, gutenLEE commented on src/main/java/com/heeverse/config/Authority.java
> +public class Authority {
추후 리팩토링때 반영해보겠습니다!

2023-07-28 00:04 UTC, merged

2023-07-28 00:05 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +class LoginAuthenticationTest {
아하 별도 이슈로 등록하고 다시 짜보겠습니다!

2023-07-28 00:10 UTC, gutenLEE commented on src/main/java/com/heeverse/member/service/MemberService.java
> +        return Optional.of(Member.builder().build());
생성자와 빌더 차이, 장단점에 대해 좀 더 알아보겠습니다