Feat/2/member join jeongheekim
f-lab-edu/heeverse-ticket pull request #14
Opened 2023-07-25 07:59 UTC by ZhenxiKim

## 개요
- 관련 Issue 번호 : #2 

## 작업사항
- mapper 설정
- h2 db 접속정보 설정
- schema.sql 설정
- security 이외 개발을 위해spring boot security auto config기능을 꺼놨습니다.
- memberService의 signup메소드는 리턴타입이 void여서 관련 클래스의 메소드를 제대로 호출하는지 검증하는 테스트 코드를 작성하였습니다.

2023-07-25 08:23 UTC, gutenLEE commented on src/main/resources/mapper/MemberMapper.xml
> +    SELECT *
(*) 보다 컬럼명을 명시하는 게 더 안전할 것 같습니다!

2023-07-25 11:46 UTC, f-lab-maverick requested changes
확인하였습니다~
리뷰 확인해주시고, 수정사항과 질문에 대해 답변해주신 후 다시 리뷰요청 부탁드립니다.

2023-07-25 11:46 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/controller/MemberController.java
> +    @ResponseStatus(HttpStatus.CREATED)
👍

2023-07-25 11:46 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/controller/MemberController.java
> +    @ResponseStatus(HttpStatus.CREATED)
만약 생성 도중 오류가 생긴다면 어떤 상태코드가 내려갈까요?

이후 이 에러에 따라 상태코드를 다르게 내려주려면 어떤 작업을 해야하는지 찾아보시는것도 좋습니다.

2023-07-25 11:46 UTC, f-lab-maverick commented on src/main/resources/application-local.yml
> +    username: sa
추후에 실제 DB를 연결한다면 db정보중 민감한 정보 (url, id, password)를 저장해야할 때가 올텐데요, github에 이런 정보를 올리게되면 DB를 탈취당할 수 있습니다.

이런 경우 어떻게 하면 좋을지 먼저 고민해보는것도 좋은 포인트가 될 것입니다.

2023-07-25 11:46 UTC, f-lab-maverick commented on src/main/resources/mapper/MemberMapper.xml
> +    SELECT *
명시적으로 어떤 데이터를 들고올지 쿼리에 컬럼으로 명시해주는것이 좋습니다.
`SELECT * ...`형식으로 데이터를 가져오게 되면 필요하지 않은 데이터까지 모두 조회하게 되고, 이로 인해 DB 성능저하, 네트워크 대역폭 낭비 등의 이슈가 생길 수 있습니다.

2023-07-25 11:46 UTC, f-lab-maverick commented on src/main/resources/mapper/MemberMapper.xml
> +    WHERE member_id = #{memberId}
파라미터를 전달할 때 `#`, `$`를 선택할 수 있습니다. `$`의 경우 SQL Injection의 위험이 있어 사용을 권장하지 않지만, 테이블명, 컬럼명등을 동적으로 파라미터를 사용해야할 때에는 `$`를 사용해야할 때도 있습니다.
이 차이점은 한번 알아보고 가시는게 좋겠습니다~

2023-07-25 11:46 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +);
이 DDL에는 PK가 없네요.
MySQL에서 PK를 지정하지 않으면 어떤 일이 발생할까요?

2023-07-25 11:46 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/service/MemberServiceTest.java
> +    void signup() {
`@DisplayName` 어노테이션을 통해 어떤 테스트를 하는지 명시해주는것이 좋습니다.
테스트는 어떤 기능을 테스트하고자 하는 것인지 명확하게 표시되어야 테스트가 실패할 때 관리할 수 있습니다.

만약 이게 어떤것을 테스트하는지 알 수 없다면, 테스트가 깨져도 누구도 어떤 기능이 깨진지 알기 어려울 것이고 결국 테스트코드가 삭제될 수 있습니다.

테스트코드도 관리 대상이기 때문에, 이런 부분을 꼼꼼히 챙기는 습관을 들여주시는게 좋겠습니다~

2023-07-25 11:46 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/service/MemberServiceTest.java
> +        verify(memberMapper, times(1)).insertMember(any(Member.class));
어떤걸 테스트하고자 하신건가요?
`verify`를 통해 특정 메소드가 호출되었음을 확인하는 것은 추후 리팩토링에 불리할 수 있지 않을까요?

2023-07-26 05:54 UTC, ZhenxiKim commented on src/main/resources/application-local.yml
> +    username: sa
[스프링 공식 문서](https://docs.spring.io/spring-boot/docs/1.0.1.RELEASE/reference/html/boot-features-external-config.html)에서 안내하는 것처럼 민감한 정보를 따로 파일로 뺀 뒤, 파일에서 접속정보로 읽어오도록 서버에 올리면서 시도해 보겠습니다.

2023-07-26 09:12 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/controller/MemberController.java
> +    @ResponseStatus(HttpStatus.CREATED)
생성 도중 오류가 발생하면 500 코드가 리턴됩니다. try-catch 문을 걸어 생성 도중 에러 발생 시 custom exception(custom exception에 리턴할 @Response Status 지정)을 발생시켜 상태코드를 다르게 내려줄 수 있습니다.

2023-07-26 09:21 UTC, ZhenxiKim commented on src/main/resources/schema.sql
> +);
데이터베이스에서 PK는 row를 식별하는 값으로 PK를 설정하지 않았을 때 아래와 같은 문제 발생합니다.

- row를 식별하는 키이므로  데이터 중복이슈가 발생할 수 있습니다.
- 데이터 무결성이 깨지는 문제가 발생할 수 있습니다.
 - 개체 무결성(entity integrity)
 - 모든 테이블이 기본 키를 가져야 하며, PK는 고유해야 하며 null을 허용하지 않는다.
 - 참조 무결성(referential integrity)
 - 하나의 테이블의 PK는 다른 테이블에서 참조키(FK)로 사용되므로 참조 관계가 깨질 수 있다.

2023-07-26 09:23 UTC, ZhenxiKim commented on src/test/java/com/heeverse/member/service/MemberServiceTest.java
> +        verify(memberMapper, times(1)).insertMember(any(Member.class));
signup 메소드가 리턴값이 void여서 메소드 호출 횟수가 1번 정상동작하는지 확인하려 했습니다. 조금 더 로직에 기반한 테스트 코드로 변경해보겠습니다. 예) 회원 가입 성공/실패

2023-07-27 08:18 UTC, ZhenxiKim commented on src/main/resources/mapper/MemberMapper.xml
> +    WHERE member_id = #{memberId}
#, $ 차이 정리해서 올립니다.
https://zhenxispace.notion.site/mybatis-90ea0cbf453a439291dded01b9db82f2?pvs=4

2023-07-27 15:50 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +);
네 맞습니다~ PK는 반드시 명시적으로 선언해주셔야 합니다~

2023-07-27 16:00 UTC, f-lab-maverick requested changes
추가 코멘트 확인해주시고 다시 리뷰요청 부탁드립니다~

2023-07-27 16:00 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/dto/MemberRequestDto.java
> +@Builder
1. `@Builder`가 선언되면 기존에 가지고있던 생성자는 어떻게 될까요? 
2. 이 객체에는 빌더 패턴이 필요할까요?
3. Request로 이 객체를 받아오려 한다면 기본생성자가 필요할 것입니다. `@RequestBody`어노테이션은 `Jackson2HttpMessageConverter `를 통해 객체로 역직렬화를 하기 때문에 이 경우 기본생성자가 필요합니다.

2023-07-27 16:00 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +ALTER TABLE member ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (member_id);
이렇게 테이블을 만든 후 PK를 선언해주는 방식 보다는 테이블 생성 DDL에 PK를 바로 선언해주시는게 좋습니다.
```
CREATE TABLE member
(
    member_id       bigint auto_increment PRIMARY KEY,
    id              varchar(50)  NOT NULL,
    password        varchar(60)  NOT NULL,
    email           varchar(100) NOT NULL,
    user_name       varchar(20)  NOT NULL,
    create_datetime datetime     NOT NULL
);
```

2023-07-27 16:00 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/service/MemberServiceTest.java
> +    @DisplayName("회원_requestDto_생성")
어노테이션 내부 값은 띄어쓰기, 공백 입력이 가능하기 떄문에 언더바를 사용하실 필요는 없습니다

2023-07-28 04:59 UTC, ZhenxiKim commented on src/main/resources/schema.sql
> +ALTER TABLE member ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (member_id);
칼럼 명과 함께 명시하는 것이 다른 개발자와 소통하기에 더 명시적이고 추가 구문을 통해 PK 제약 구문이 누락될 위험도 없겠군요!

2023-07-28 08:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/dto/MemberRequestDto.java
> +@Builder
1번 질문 답변) 매개변수가 없는 기본 생성자는 컴파일 시 기본 생성자가 없으면 자동으로 생성해 줍니다. 하지만 매개변수가 있는 생성자가 있으면 기본 생성자가 생성되지 않으므로 기본생성자를 생성해야 합니다.

2번 질문 답변) 
-  Setter를 정의해서 테스트 코드에서 필드를 세팅하기보다는 builder를 사용해서 무분별한 setter를 사용하지 않으려 했습니다.
-  객체지향 정보은닉 관점에서 setter를 지양한다고 공부했는데 dto 클래스는 도메인 성격이 아닌 data transfer 역할로 필요에 의하면 setter를 명시해서 사용하는 것이 좋을까요? 아니면 dto클래스에 값을 셋팅하는 메서드를 지정하는것이 나을지 고민이 됩니다. 수정한 코드에서는 @Setter를 사용하기보다는 필요한 필드에 대해서만 Setter메소드를 생성한다는 의미로 직접 생성했습니다.

2023-07-28 14:00 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/dto/MemberRequestDto.java
> +@Builder
이런경우 팩토리 메서드나 생성자를 이용하면 됩니다.
빌더의 경우 어떤 파라미터를 누락했는지 런타임이 되어야 알 수 있지만, 생성자나 팩토리메서드를 사용하면 필요한 파라미터를 모두 볼 수 있습니다.

`Setter`의 경우 불필요한경우 사용을 지양해야 하지만, 필요한 경우 당연히 선언해도 됩니다. 기본값으로 setter를 선언하는걸 지양해보는 방식으로 적응해주시면 됩니다~

빌더를 사용하나, 생성자를 사용하나 생성 시점에 필요한 모든 데이터를 넣어서 생성해주면 setter가 필요하지 않아요.

2023-07-29 06:32 UTC, ZhenxiKim commented on src/main/java/com/heeverse/member/dto/MemberRequestDto.java
> +@Builder
커밋한 부분은 생성자를 이용했습니다. 이번에 팩토리 메서드 패턴도 같이 공부하여 코드에는 적용하지 않았지만 정적 팩토리 메서드를 연습한 부분도 같이 봐주시면 감사하겠습니다.

정적 팩토리 메서드 구현 부
```java
public static MemberRequestDto newInstance() {
        MemberRequestDto dto = new MemberRequestDto();
        dto.id = "tester";
        dto.email = "tester@gmail.com";
        dto.password = "123passWd";
        dto.userName = "testerzzang";
        return dto;
    }
```

정적 팩토리 메서드 적용 부
```java 
@DisplayName("회원 requestDto 생성")
@BeforeEach
void memberEntitySetUp() {
    memberRequestDto = MemberRequestDto.newInstance();
}
```

2023-07-30 00:55 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/dto/MemberRequestDto.java
> +@Builder
`MemberRequestDto`는 실 운영에 사용하는 객체이고, `MemberRequestDto.newInstance();`는 테스트를 위한 객체 생성에 종속된 메서드입니다. 실제 운영코드에 테스트를 위한 전용 코드가 들어가는건 꽤 좋지 않은 생각입니다. 운영코드를 짜며 `newInstance`라는 메서드 명을 보고 테스트를 위한 메서드라고 판단하기는 어려울 테니까요.

이런 경우 테스트코드 내부에 객체 생성을 위한 메서드를 별도로 두는 방식이 있습니다.
ex)
```
public class MemberTest {
  public static MemberRequestDto createMemberRequest() {
    return ...
  }
}
```
여기서 파라미터 등을 받아 뭔가 다른걸로 변경하는 형식의 메서드로 변경도 가능합니다~ 테스트 관련 코드는 테스트 패키지 내부에만 존재하도록 해주세요.

2023-07-30 00:56 UTC, f-lab-maverick commented on src/main/java/com/heeverse/member/dto/MemberRequestDto.java
> +@Builder
또한, 정적 팩토리메소드를 사용하는건 무조건 좋은 선택은 아닙니다. 단순히 객체 생성을 위한 것이라면 생성자로 생성하는게 더 직관적인 경우가 많습니다.

정적 팩토리 메소드를 사용할 때에는 이 패턴이 필요한 경우가 어떤것일지 고민한 후 사용해주시면 좋겠습니다.

2023-07-30 00:58 UTC, f-lab-maverick approved these changes
확인하였습니다~ 머지해주셔도 좋습니다.

2023-07-30 00:58 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/service/MemberServiceTest.java
> +            "test@gmail.com");
테스트에 대한 코드는 단언문이 있어야 합니다. 이런 경우 약간 억지스러울 수는 있지만 `assertNotNull(memberRequestDto)`와 같은 형태로 단언을 해주시면 됩니다.

TDD방식으로 개발할 때에는 테스트코드 작성 후 실 코드를 작성하기 때문에 이런 생성과 관련한 테스트코드도 작성하기는 합니다 :)

2023-07-31 04:49 UTC, merged