[#4] 로그인 인증 테스트 코드 리팩토링
f-lab-edu/heeverse-ticket pull request #15
Opened 2023-07-31 13:06 UTC by gutenLEE

## 개요
- 관련 Issue 번호 : #4 

## 작업사항
- 로그인 인증 테스트 코드 리팩토링

### 변경전
- StubMemberService 대역 객체로 멤버 정보조회 처리

### 변경후
- StubMemberService 제거하고 DB 에서 조회

2023-07-31 13:11 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +                })
WebApplicationContext 에 등록된 빈중에 SecurityContext 를 못찾아서 이렇게 했습니다. 
더 찾아보겠습니다.

2023-08-01 04:21 UTC, ZhenxiKim reviewed
리뷰 완료하였습니다!

2023-08-01 04:21 UTC, ZhenxiKim commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +    @DisplayName("로그인에 성공하면 HttpStatus 는 redirection 다")
login 시 리다이렉트가 아닌 Http Status 200을 테스트하는 게 정상적인 테스트 시나리오가 될 것 같습니다.
현재 security 설정 때문에 모든 요청에 대해 리다이렉트로 동작하게 되어 설정이 되어있는데 저도 아직 이 부분을 찾고 있어서 알게 되면 공유하겠습니다.

2023-08-01 04:21 UTC, ZhenxiKim commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +    @DisplayName("회원가입 성공한 Member 만이 로그인 가능함")
하위 테스트와 유사한 것 같은데 로그인 기능만 테스트는 data.sql을 활용하여 dummy 회원 데이터가 있는지 테스트하는 것도 적절한 단위테스트의 단위가 될 것 같습니다.

2023-08-01 04:56 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +    @DisplayName("회원가입 성공한 Member 만이 로그인 가능함")
통합테스트로 회원가입이 성공한 유저를 대상으로 로그인을 테스트해보려 했는데 의미가 명확하지 않았던거 같슴다!
더 고민해보겠습니다!

2023-08-01 05:01 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +    @DisplayName("로그인에 성공하면 HttpStatus 는 redirection 다")
넵 변경하겠습니다
이후에 보완할 것이 로그인 성공, 실패를 처리하는 handler도 등록해야 될 것 같슴다!

2023-08-01 12:26 UTC, f-lab-maverick requested changes
약간의 코멘트를 남겼습니다. 디테일한 설명이 필요해보여 이 부분은 멘토링때 보충하여 설명드릴게요. 

멘토링 종료 후 수정사항 반영하여 재리뷰요청 부탁드려요~

2023-08-01 12:26 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +    }
이렇게 생성한 멤버를 return해줄 것이라면 memberRequestDto 변수를 사용하지 않아도 되지 않을까요?

2023-08-01 12:26 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +    @DisplayName("회원가입 성공한 Member 만이 로그인 가능함")
회원가입을 테스트하는 로직으로 로그인과 무관해보이네요. DisplayName 내용을 실제 테스트 내용으로 맞춰주세요~

2023-08-01 12:26 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +        memberService.signup(memberRequestDto);
약간의 팁인데요, 이런 경우 미리 만들어둔 테스트를 재사용하셔도 됩니다.
(`signUpTest()` 호출)

2023-08-01 12:26 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +                    assertEquals(memberRequestDto.getId(), authentication.getPrincipal());
when에는 행위가 들어가야합니다. when절에는 LoginDTO를 만드는 사전작업이 들어가있네요.

given / when / then에 각각 어떤 내용이 들어가야하는지 아래 링크를 통해 확인해주세요.
https://martinfowler.com/bliki/GivenWhenThen.html

2023-08-01 12:26 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +                    assertEquals(memberRequestDto.getId(), authentication.getPrincipal());
이 테스트는 mockMvc를 통해 블랙박스형태의 테스트를 하고있으면서 SecurityContext를 불러오는 화이트박스 테스트를 동시에 진행하고 있네요.

mockMvc로 테스트하실것이라면 로그인이 적용되어야만 접속 가능한 특정 URL을 조회하고, 조회가 가능한지를 테스트해보는게 더 명확합니다.

이 내용은 멘토링시간에 좀 더 말씀드리도록 할게요

2023-08-02 04:33 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +                    assertEquals(memberRequestDto.getId(), authentication.getPrincipal());
아하 넵 피드백 주신 부분들 학습하고 다시 요청하겠습니다!

2023-08-02 08:47 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +                    assertEquals(memberRequestDto.getId(), authentication.getPrincipal());
given 은 when에 정의할 행동에 필요한 상태 준비
when 은 행동을 정의
then 은 행동의 기대 결과를 검증

- Given-When-Then 패턴의 의도에 맞게 다시 짜보겠습니다.

2023-08-02 08:57 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +                    assertEquals(memberRequestDto.getId(), authentication.getPrincipal());
- mockMvc 사용한 `/login` 성공 테스트는 사용자 관점에서 테스트가 목적인 블랙 박스 검사다.
- SecurityContext 로 토큰을 검사한 것은 스프링 시큐리티의 로그인 처리 내부 소스 코드를 테스트한 것으로 개발자 관점의 화이트 박스 검사다.
- 블랙박스와 화이트 박스 검사는 분리해서 테스트 해야 한다.

로 이해했습니다!

2023-08-03 02:11 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +                    assertEquals(memberRequestDto.getId(), authentication.getPrincipal());
네 정확히 이해해주셨습니다 :)
위 관점대로 테스트를 분리해주세요.

2023-08-03 05:28 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +    @DisplayName("로그인에 성공하면 HttpStatus 는 redirection 다")
Http status 변경은 정희님 jwt 토큰 작업 완료 후나, 핸들러 추가 이슈 처리할때 하기 위해 수정 안했습니다!

2023-08-03 05:28 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
>  }
중복 코드는 재사용을 위해 메서드로 분리했습니다.

- 로그인을 위한 ResultActions
- 회원가입을 위한 ResultActions

2023-08-03 05:28 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +            );
이전 코드에서는 HttpServletRequest 에서 Authentication 객체를 직접 조회했는데,
SecurityMockMvcResultMatchers 사용으로 변경했습니다.

2023-08-03 05:28 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
>      void when_login_success_should_return_OK() throws Exception {
이전에 피드백 주신 로그인 성공 화이트박스 테스트에서
로그인 성공 후 특정 URI로 접근 테스트는 다른 엔드포인트 추가 후 추가하겠습니다

2023-08-03 14:49 UTC, f-lab-maverick approved these changes
확인하였습니다. 작성한 코멘트 참고하여 다음 테스트를 준비해주세요~
테스트코드 작성이 점점 익숙해지는게 보입니다 👍 👍

2023-08-03 14:49 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +        signUpTest();
아래 내용은 이후 테스트를 작성하실 때 팁정도로 생각해주시면 좋겠습니다.

---
이렇게 다른 테스트코드를 호출할 때에는 어떤 동작을 하는 테스트코드를 호출한 것인지 메서드명을 명확하게 해주시면 좋습니다. 테스트코드는 가독성이 정말 중요하기 떄문에 테스트코드에 한해서 한글로 메서드명을 짓는 경우도 꽤 있습니다.

예를 들면 아래와 같은 코드가 있겠네요.
```
final var member = 회원가입();
final var token = 로그인(member);
```

이후에 테스트를 좀 더 확장하시게 된다면 회원과 관련한 테스트도 다른 테스트 클래스에서 호출하고 싶으실거에요. 하지만 JUnit 5기반의 테스트는 static method를 테스트로 지정할 수 없습니다. 그렇기때문에 별도 TestHelper 클래스에 Test관련 로직을 만들고, 테스트에서는 이 static helper 메소드를 호출하여 검증하는 형식으로 변경하기도 합니다.

이렇게 별도 테스트 유틸에 관련 로직을 만들어두면 다른 테스트 클래스에서도 동일한 로직을 호출할 수 있게되고 이는 테스트를 재사용할 수 있게 되는 장점도 생깁니다.

유지보수하고 재사용하기 용이한 테스트를 만드는건 항상 고민해보셨으면 좋겠습니다~

2023-08-03 14:49 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +        assertNull(memberMapper.findById(loginRequestDto.id()));
이런것도 white / blackbox가 섞여있는 구조입니다.

테스트의 구조가 
1. 로그인할 멤버가 DB에 존재하는지 SQL 쿼리
2. 없다면 로그인 HTTP 요청 후 검증

이런 구조입니다. 이거는 이렇게 변경할 수 있어요.
1. HTTP 요청으로 아이디 중복 검사
2. 없다면, 로그인 시도 후 검증

API를 써서 검증하는 테스트는 그 목적에 맞게 한가지 방법으로 테스트해보세요~

2023-08-03 14:49 UTC, f-lab-maverick commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +    }
접근제어자도 함께 작성해주시면 좋곘네요~  JUnit test의 경우 default 접근제어자를 사용하지만, 이 메서드는 테스트코드가 아니므로 적절한 접근 제어가 필요해보입니다.

2023-08-04 03:45 UTC, gutenLEE commented on src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
> +        assertNull(memberMapper.findById(loginRequestDto.id()));
아하.... 이직 헷갈리네요.. 
넵!

2023-08-04 03:45 UTC, merged