Feat/4/credentials vault
f-lab-edu/heeverse-ticket pull request #19
Opened 2023-08-04 07:51 UTC by ZhenxiKim

## 개요
- 관련 Issue 번호 : #4 

## 작업사항
#16 에서 리뷰내용 수정사항 반영하였습니다.
민감정보는 spring-vault를 통해 외부관리로 적용하였습니다. 개발단계여서 로컬에 서버를 띄운뒤 인메모리로 관리하였습니다.

## 변경로직

### 변경전
민감정보 상수로 처리

### 변경후
민감정보 외부 모듈에서 받아옴

2023-08-04 08:49 UTC, ZhenxiKim commented on src/main/resources/application-local.yml
> +  scheme: http
기본 셋팅은 https인데 아직 SSL인증서 부분은 학습이 되지 않아 http로 테스트 진행했습니다.

2023-08-04 08:49 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/Authority.java
> +package com.heeverse.security;
security 관련 로직인 security 패키지가 적절한 듯 하여 패키지 이동하였습니다. config 패키지에는 @Configuration 어노테이션 붙은 클래스만 남겼습니다.

2023-08-04 11:16 UTC, f-lab-maverick requested changes
이번에는 코드 가독성을 위주로 피드백하였습니다.
수정 후 다시 리뷰요청 부탁드립니다~

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +        this.jwtTokenProvider = jwtTokenProvider;
이런 관습적인 코드는 lombok을 사용하셔도 좋습니다.
필요한 필수 파라미터를 생성자로 만들어주는 `@RequiredArgsConstructor`를 사용해보시는게 어떠실까요?

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/VaultEnvironmentConfig.java
> +    }
이렇게 바꾸면 catch문 이후를 안봐도 된다고 표현할 수 있으니, 읽는사람의 가독성을 향상시켜줄 수 있습니다. 

```suggestion
    @Override
    public VaultEndpoint vaultEndpoint() {
        String authority = url + ":" + port;
        try {
            return VaultEndpoint.from(new URI(scheme, authority, null, null, null));
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }   
    }
```

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
> +    public static final String HEADER_NAME = "Authorization";
`Authorization`과 같은 헤더 key는 Spring에 상수로 이미 지정되어있어서, 재사용해주시는것도 좋은 방법입니다. `HttpHeaders.AUTHORIZATION`

물론 모든 상수를 다 알 필요는 없습니다. 이렇게 상수로 제공되는게 있으니 생각나실 때 이미 지정된 상수를 꺼내서 사용하는것도 좋은 방식이라 참고차 말씀드렸습니다 :)

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
> +        if (!ObjectUtils.isEmpty(jwtToken) && jwtTokenProvider.validateToken(jwtToken)) {
`!ObjectUtils.isEmpty(jwtToken) && jwtTokenProvider.validateToken(jwtToken)`과 같이 조건이 중첩된 경우, 어떤것을 검증하고자 하는지 이름을 붙여주는것이 좋습니다.

변수로 변경하셔도 좋고, 메서드로 변경하셔도 좋습니다. 코드를 읽을 때 이 코드의 의도를 명확하게 파악할 수 있어야 하기 때문에, 중첩된 조건문이나 복잡한 조건의 경우에는 의도를 담은 이름을 지어주시는건 어떠신가요?

```suggestion
        if (isValidJsonToken(jwtToken)) {
```

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +    private final Duration TOKEN_DURATION_TIME = Duration.ofMillis(3600000);
ofMillis라는 메서드를 사용하여 큰 수를 주다보니 한눈에 몇시간인지 들어오지 않네요.
이런 경우에는 `ofHour`, `ofMinuit` 등 여러 단위를 나타낼 수 있는 함수가 있고, 체이닝 방식으로도 사용할 수 있습니다.

예를 들면, 3시간 30분을 표현할 때는 이렇게 표현할 수 있습니다.
`private final Duration TOKEN_DURATION_TIME = Duration.ofHours(3).plusMinutes(30);`

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +    private final String TOKEN_NAME = "JWT_KEY";
이 상수들은 다른곳에서도 사용할 수 있을거같은데요, 이런 경우 별도의 상수 클래스를 만들어 public하게 보관하는 것이 재사용하기 좋습니다.

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        assert read != null;
java에서 제공해주는 단언문은 이 단언이 문제가 있을 경우 명확한 메세지를 보여주지 않습니다.
이런 예외처리는 `throw`를 통해 명시적으로 예외처리를 해주셔야 이후 예외 관리에서도 관리할 수 있습니다.

단순한 validation처리는 `Assert.notNull(read, "read should not be null");`과 같은 코드를 사용하셔도 괜찮습니다 :)
내부적으로는 모두 `throw`를 통한 예외처리를 해주고 있기 때문입니다.

Spring에서 제공해주는 `Assert`클래스를 활용해보시는것도 좋은 방법이겠네요.

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        return (String) read.getRequiredData().get(TOKEN_NAME);
`read.getRequiredData().get(TOKEN_NAME)`을 한 결과가 null일 경우 어떻게될까요?

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +            .setExpiration(new Date(System.currentTimeMillis() + TOKEN_DURATION_TIME.toMillis()))
Tip. Date클래스를 사용해야하는건 불편합니다. 더하거나, 빼거나, 연산하기도 어렵고 formatting하기도 쉽지 않죠

옛날 코드중 Date에 의존성이 있는 코드의 경우 어쩔 수 없이 Date클래스를 사용해야 하기는 합니다.

이런 경우, 저는 연산이나 생성에 편리한 `LocalDateTime`으로 모든 데이터를 만들어둔 후 어댑터 패턴을 활용하여 Date로 변경하는 방식을 활용합니다. 코드 읽기도 편하고 쓰기도 편합니다.

예를 들면 아래와 같은 코드가 되겠네요.

```
.setExpiration(new DateAdapter(LocalDateTime.now().plus(TOKEN_DURATION_TIME)).toDate())
```

TOKEN_DURATION_TIME과 같은 Duration은 시간 연산시 바로바로 변경 없이 사용할 수 있습니다.

이렇게 자신만의 패턴으로 코드 활용도를 높이는 방식도 고민해주시면 좋겠네요. 단순하게 이 클래스에서는 파라미터로 `Date`를 받으니까 불편해도 이 `Date`클래스를 활용해야지~ 라고 생각하는 패러다임에서 벗어나시면 좀 더 좋은 코드를 고민할 수 있는 계기가 생길 것입니다.

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        if (!StringUtils.hasText(headerAuth)) {
조건문에 `!`를 활용해 ~~조건이 아닐 경우를 작성하는 것 보다는, 명확하게 ~~ 조건일 경우로 적어주시는게 읽을 때 있을 수 있는 실수를 방지할 수 있습니다.

```suggestion
        if (StringUtils.isEmpty(headerAuth)) {
```

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        }
1. catch문 안에서 로그만 찍고 넘어가는 형식으로 진행하시면 정말 예외가 발생하였을 때 모르고 넘어갈 수 있습니다. 예외가 발생하였을 때에는 명시적으로 예외를 던지거나, 별도 액션을 취해주시는게 좋습니다.
2. `e.printStackTrace()`는 안티패턴으로 사용을 지양해야하는 메서드중 하나입니다. 왜 그럴까요?
성능, 보안측면에서 찾아보시면 좋을것 같네요~

2023-08-04 11:16 UTC, f-lab-maverick commented on src/main/resources/application-local.yml
> +  scheme: http
모든걸 로컬에서 하면 시간이 지날수록 점점 불편해지실거에요.
이제 개발서버를 세팅할 시간이 다가오는것같군요 :)

2023-08-04 11:25 UTC, gutenLEE commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
> +        if (!ObjectUtils.isEmpty(jwtToken) && jwtTokenProvider.validateToken(jwtToken)) {
jwtToken 문자열 empty 검사도 `validateToken()` 메서드 안에서 하면 좋을 것 같습니다!

2023-08-04 11:25 UTC, gutenLEE commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +    private String getJwtKey() {
`getJwtKey()` 메서드 이 메서드를 호출하는 `getSecretKey()`와 `parsing()` 밑으로 배치시키면 
관련 메서드끼리 순서대로 배치되어 코드 파악에 쉬울 것 같습니다!

2023-08-04 11:25 UTC, gutenLEE commented on src/main/java/com/heeverse/config/VaultEnvironmentConfig.java
> +public class VaultEnvironmentConfig extends AbstractVaultConfiguration {
이 브랜치로 로컬에서 실행해보니 
`Could not resolve placeholder 'vault.scheme' in value "${vault.scheme}"` 에러 발생합니다!

2023-08-04 11:27 UTC, f-lab-maverick commented
conflict가 발생하는거같네요~ 충돌 해결도 같이 진행해보시겠어요?

2023-08-07 04:46 UTC, ZhenxiKim commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +        this.jwtTokenProvider = jwtTokenProvider;
관습적인 코드를 롬복을 사용하여 코드양을 줄이고, 가독성을 올려보겠습니다.

2023-08-07 05:11 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
> +        if (!ObjectUtils.isEmpty(jwtToken) && jwtTokenProvider.validateToken(jwtToken)) {
중첩된 조건문에 대해 변수로 빼서 어떠한 조건을 검사하지 말 수 있도록 수정하겠습니다.
또한 isEmpty메소드를 validateToken 메서드로 빼서 조건문을 간소화해 볼 수도 있을 거 같습니다.

2023-08-07 05:48 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        return (String) read.getRequiredData().get(TOKEN_NAME);
NullPointerException이 발생하게 됩니다. 상세 예외처리를 하여 api 통신 시 클라이언트가 어떤 exception이 발생했는지 알도록 수정하겠습니다.

2023-08-07 06:19 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        if (!StringUtils.hasText(headerAuth)) {
`Deprecated as of 5.3, in favor of hasLength(String) and hasText(String) (or ObjectUtils.isEmpty(Object))`
isEmpty가 deprecated된다고 하여 hasText를 사용했었습니다. 명확한 조건문을 선언하기 위해 `ObjectUtils.isEmpty(headerAuth)`로 수정하겠습니다.

2023-08-07 06:35 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        }
```java
  try {
        id = Jwts.parserBuilder()
            .requireAudience(getJwtKey())
            .build()
            .parse(headerAuth)
            .toString();
    } catch (Exception e) {
        throw new JwtParsingException();
    }
   ```
Exception으로 예외를 잡을 경우 try문 내부에서 exception 하위  예외 발생시 잡을 수 있도록 수정하였고, parsing 로직에서 exception이 발생 했음을 상세 exception을 날리도록 수정하였습니다.

2023-08-07 06:45 UTC, ZhenxiKim commented on src/main/java/com/heeverse/config/VaultEnvironmentConfig.java
> +public class VaultEnvironmentConfig extends AbstractVaultConfiguration {
application-local파일에 vault.scheme값을 명시했는데 혹시 pull받은 파일에 없었나요? @gutenLEE

2023-08-07 08:31 UTC, ZhenxiKim commented
security redirect 이슈는 JsonAuthenticationFilter에서 재정의한 successfulAuthentication에서 상위 클래스(SavedRequestAwareAuthenticationSuccessHandler)의 onAuthenticationSuccess 메소드를 호출해서 발생하는 이슈였습니다.
onAuthenticationSuccess 메소드에 redirect하는 로직이 존재합니다.

2023-08-07 08:42 UTC, gutenLEE commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +                .requestMatchers("/error").permitAll()
`/error` 요거는 언제 사용되는건가요~??

2023-08-07 08:42 UTC, gutenLEE commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
>          }
- 예외 전환을 할 때는 원인 예외를 포함해 주면 원인 예외까지 확인할 수 있어서 좋다고 합니다!
- 예외의 조상인 Exception 으로 catch 하는 이유가 궁금합니다!

2023-08-07 14:15 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
>          }
Q)원인 예외를 무조건 포함시켜주는게 관행?인지 궁금합니다
A) 아닙니다. 다만 원래 예외를 포함하여 생성하면 기존 예외가 어떻게 발생했는지 추적하기는 더 좋습니다.
catch후 신규 예외로 던진다면 try문중 어디에서 예외가 발생하던간에  `throw new JwtParsingException();`으로부터 cause가 생성됩니다.
원래예외를 포함하여 생성하면 스택트레이스에 원본 예외 발생지점이 포함되어 생성되어 어디에서 예외가 생성되었는지 파악하기 좀 더 편리합니다.

만약 예외가 정확히 어디에서 발생한건지 확인이 필요하지 않다면 신규 예외로 생성해도 무방합니다.

2023-08-07 14:22 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 머지하셔도 좋습니다.

2023-08-07 14:22 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/DateAdapter.java
> +}
이 클래스를 어댑터로 사용하기 편리하려면 `LocalDateTime`으로 생성할 수 있을 뿐만 아니라 `Date`로도 생성가능하도록 하는건 어떨까요?

2023-08-07 14:22 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/DateTarget.java
> +}
구현체가 하나일 때 인터페이스가 필요할까요?
이 인터페이스는 어떤 역할을 하나요?

2023-08-07 14:22 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +            .setExpiration(new DateAdapter(LocalDateTime.now().plus(TOKEN_DURATION_TIME)).toDate())
디자인 패턴 적용 👍

2023-08-08 04:56 UTC, ZhenxiKim commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +                .requestMatchers("/error").permitAll()
redirect 현상때문에 테스트 시 추가했는데 제거하겠습니다.

2023-08-08 11:44 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        }
@f-lab-maverick 2번 답변 올립니다.

`e.printstacktrace`는 내부적으로 `System.err`를 통해 에러가 발생한 메소드부터 stack 영역에 쌓인 stack trace를 출력합니다.
`System in, out, err` 모두 stream 기반(IO 작업)으로 출력하므로 애플리케이션 작업상 동기 작업을 하게 되어 성능상 좋지 않습니다.
보안 측면에서는 에러 나는 메소드 부터 stack Trace가 찍히는데 exception이 발생하는 line 번호를 직접 보여주므로 코드상 취약점을 드러내게 돼서 보안상 좋지 않습니다.

2023-08-09 06:07 UTC, ZhenxiKim commented on src/main/java/com/heeverse/common/DateTarget.java
> +}
@f-lab-maverick 어댑터 패턴에서 인터페이스는 어댑티와 호환 가능하지 않은 어댑터의 호환 역할을 하는데 여기서 Date클래스는 이미 정의된 java api여서 인터페이스 정의가 필요 없을거같습니다. 확장성을 고려하여 구현체가 2개 이상일때부터 인터페이스를 고려하는게 좋을거같습니다.

2023-08-09 06:08 UTC, ZhenxiKim commented on src/main/java/com/heeverse/common/DateAdapter.java
> +}
@f-lab-maverick Date로 쉬운 변환을 위해 LocalDateTime을 연산 후 어댑터를 통해 Date타입으로 변환했는데, Date를 파라미터로 받는 연산을 말씀하시는건가요?

2023-08-09 08:10 UTC, merged

2023-08-10 15:46 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/DateAdapter.java
> +}
네. 단순히 LocalDateTime을 Date로 바꾸기 위함이라면 유틸성 클래스를 만드는게 더 간단합니다.

LocalDateTime -> Adapter ->Date
Date -> Adapter -> LocalDateTime

두개 모두 가능하도록 만들면 범용성이 좋지 않을까요? Adapter를 사용하는 입장에서는 만들 때나 사용할 때나 타입에 대한 자유도를 보장받을 수 있겠네요.