[#17] 티켓 도메인 생성
f-lab-edu/heeverse-ticket pull request #20
Opened 2023-08-07 07:56 UTC by gutenLEE

## 개요
- 관련 Issue 번호 : #17 

## 작업사항
- 티켓 도메인 개발을 위한 기본 클래스 생성하기 
    - 티켓 : Ticket
    - 티켓 등급 : TicketGrade
- 티켓 생성 기능
- 티켓등급 생성 기능

### 변경 내용
<img width="924" alt="스크린샷 2023-08-07 오후 4 45 38" src="https://github.com/f-lab-edu/heeverse-ticket/assets/61870748/15c64cb5-2dc5-4431-bbf4-8cbfa13d5c07">

1. (티켓 등급 - 공연) 비식별 관계  추가했습니다.
    (티켓 등급 - 공연) 관계가 없을때는 공연에 연관된 티켓 등급을 조회하려면 
     티켓을 통해 티켓 틍급을 조회하는 부분이 비효율이라 판단했습니다. 

2. Mybatis 조회 결과를 List<Object> 형태로 맵핑하는 부분이 잘 안되어 찾아보고 있습니다.

2023-08-07 08:08 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/domain/entity/OrderInfo.java
`Ticket` 에 포함된 예매 관련 정보 필드들은 VO 클래스로 분리했습니다.

2023-08-07 08:08 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
`publish()` 는 공연에 티켓을 발행할 때 사용하는 스태틱 팩토리 메서드고
`toOrderedTicket()` 는 티켓의 판매 처리를 위한 메서드입니다. 

스태틱 팩토리 메서드 내부에서 호출하는 생성자는 모두 `private` 접근 제한을 두었습니다.

2023-08-07 08:08 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/domain/entity/TicketGrade.java
> +    @AutomapConstructor
myBatis 에서 쿼리 결과를 객체로 맵핑할 때 선언하는 어노테이션입니다.

2023-08-07 08:08 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket/domain/mapper/TicketMapperTest.java
> +        final var ticketGrades = 티켓_등급_생성();
피드백 주신 테스트 재사용 방법을 적용해봤습니다.

2023-08-07 08:08 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket/domain/mapper/TicketTestHelper.java
테스트 헬퍼 클래스를 만들어 봤는데 메서드들이 헬퍼 클래스 목적에 맞게 두었는지 궁금합니다!

2023-08-07 08:08 UTC, gutenLEE commented on src/main/resources/schema.sql
> +    delete_yn	boolean	COMMENT '취소여부',
@ZhenxiKim   저희가 기획한 스키마에서는 `취소 여부` 필드명이 `delete_yn` 입니다. 

개발하면서 보니 앞선 예약이 취소되면 해당 티켓이 삭제 되는게 아니라,
 다른 예약에 포함되는게 아닌가 싶었습니다!

삭제라는 네이밍보다는 취소로 하는게 어떨가 싶어서 Ticket 엔티티에서는 `cancelled` 로 선언해봤습니다. 
어떻게 생각하시나요!

2023-08-07 08:11 UTC, gutenLEE commented on src/main/resources/application-local.yml
myBatis 3.x 에서는 쿼리 결과를 객체로 맵핑할때
생성자의 매개변수 순서대로 맵핑하는게 디폴드라고 합니다. 
하여 생성자 매개변수 이름으로 맵핑하도록 변경했습니다!

2023-08-07 08:15 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/dto/TicketRequestDto.java
@ZhenxiKim 
공연 도메인에서 티켓 도메인으로 티켓 생성 요청시 사용할 DTO 클래스입니다. 
피드백 부탁드립니다!

2023-08-07 08:15 UTC, ZhenxiKim commented on src/main/resources/schema.sql
> +    delete_yn	boolean	COMMENT '취소여부',
좋습니다. boolean타입이니 cancelled컬럼명에 boolean 타입임을 나타내는것이 좋을거같습니다.

2023-08-07 09:07 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket/domain/mapper/TicketMapperTest.java
> +        List<Ticket> tickets = TicketTestHelper.publishTicket(ticketGrades);
테스트 행위에서는 ticket grade를 정의했지만 findTickets쿼리에서는 Tikect만 조회하여 테스트 시 exception이 발생하는것 같습니다.
`java.lang.ClassCastException: class java.util.HashMap cannot be cast to class com.heeverse.ticket.domain.entity.TicketGrade`

2023-08-07 09:07 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    private TicketMapper ticketMapper;
TicketMapper에 대한 의존성 주입이 누락된것같습니다.

2023-08-07 09:07 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket/dto/TicketRequestDtoTest.java
> +        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
validation 테스트 시 이렇게 적용할 수 있군요! 저도 적용해 보겠습니다.

2023-08-07 09:12 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket/domain/mapper/TicketMapperTest.java
> +        List<Ticket> tickets = TicketTestHelper.publishTicket(ticketGrades);
아 이게 Mybatis 조회 결과를 HashMap 으로 받아온걸 TicketGrade 으로 받도록 해서 실패해서 발생했습니다. 
hashMap 말고 List<TicketGrade> 로 만들고 싶은데 아직 방법을 못찾았습니다!

2023-08-07 15:02 UTC, f-lab-maverick requested changes
고생하셨습니다~ 코멘트 확인해서 수정 후 다시 리뷰 요청 부탁드려요

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/OrderInfo.java
> +}
이 클래스는 내부 상태를 초기화할 방법이 없네요.
이 클래스를 인스턴스화하였을 때 사용할 방법이 없을 것으로 보입니다. 적어도 생성자와 getter등 필요한 필수적인 메서드는 정의해주세요~

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +    }
`orderInfo`의 경우 상수가 아닌 변수입니다. 다른 모든 정보가 동일하고 `orderInfo`만 변경되어야 한다면 `setter`를 사용해주셔도 무방합니다.

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +    }
static하지 않은 method로 만든다면 이렇게도 사용 가능하겠네요.,
`ticket.toOrderedTicket(orderInfo)`

static method로 만든 이유가 있을까요?

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/TicketGrade.java
> +    }
`toEntity`라는 메서드명은 적절하지 않아보이네요.
이 메서드가 `TicketGradeDto`에 있었다면 적절한 위치이겠지만 엔티티 내부에 `toEntity`라는 메서드는 위치가 정확하지 않아보입니다.

또한, 이런 메서드는 static하게 만들 이유가 없습니다. 인스턴스가 반드시 필요한 메서드이고, 객체 생성을 하는 메서드이기 때문에 생성자 / 인스턴스 메서드로 만들어주시는게 사용에 더 명확할 것으로 보이네요.

이렇게 사용하는게 더 개발자에게 가독성과 사용성면에서 유용하지 않을까요?
```
// 생성자
new TicketGrade(ticketGradeDto)

// 메서드
ticketGradeDto.toEntity();
```

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/TicketGrade.java
> +    }
동일한 역할을 하는 생성자를 재사용해주셔도 좋습니다.
생성자 내부 코드의 중복도 중복 코드이기 떄문에 개선 대상입니다.

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/dto/TicketGradeDto.java
> +) {
모두 `NotNull`이라면 primitive type을 사용해주는건 어떨까요?
nullable이 아니라면 wrapper type을 사용할 이유가 없을 것으로 보이네요

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +public class TicketService {
`Service` 클래스 자체에 트랜잭션을 모두 걸어버린다면 
1. 트랜잭션 분리가 필요한 경우
2. 트랜잭션을 사용하지 않는 경우

이러한 케이스를 적용하기 어렵지 않을까요?

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/resources/mapper/TicketMapper.xml
> +    </select>
별도로 페이징, 정렬은 하지 않는것인가요?

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/resources/mapper/TicketMapper.xml
> +                );
`;`이 존재하네요. 이 쿼리를 실행할 때 에러가 발생할 수 있을거같네요~

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +    delete_yn	boolean	COMMENT '취소여부',
`delete_yn`이라는 명칭은 `boolean`타입에 명확하지는 않아보이네요~

2023-08-07 15:02 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +    grade_id	bigint  auto_increment  NOT NULL PRIMARY KEY,
보통 PK의 경우 `id`등으로 명확하게 정의해주는게 쿼리 작성시나 ERD 파악시 좀 더 쉽게 읽을 수 있게 해주는 방식중 하나입니다.

`~~~_id` 형식의 네이밍은 보통 조인을 위한 외래키 네이밍에 사용합니다.
물론 `테이블명_id`형식으로 사용하기도 합니다만 명확하게 PK임을 나타낸다면 컬럼명은 `id`, `seq`등으로 지어주는게 좋지 않을까요?

2023-08-07 15:02 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket/domain/mapper/TicketMapperTest.java
> +    private static final Long CONCERT_ID = 1L;
이후에 개발 DB가 생성되고 데이터가 생성되기 시작한다면 이 ID값은 사용하기 어렵겠네요.
어떤 상황에서도 (외부 환경 영향을 최대한 덜 받는 방식으로) 테스트는 비즈니스로직을 테스트하도록 노력해서 작성해주시면 좋을 것으로 보입니다.

이러한 방식으로는
1. Mocking
2. Data를 Insert한 후 그 데이터를 select하여 그 id를 사용하기
3. 테스트용 인메모리 DB 사용

과 같은 방식이 있겠네요.

2023-08-08 04:28 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +    }
아하 static하지 않아도 가능하네요..
스태틱 팩토리 메서드만 생각했네요..

2023-08-08 04:28 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/domain/entity/TicketGrade.java
> +    }
아하 `ticketGradeDto` 에 도메인 엔티티 생성 메서드가 위치해도 괜찮군요..

2023-08-08 04:28 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/dto/TicketGradeDto.java
> +) {
- TicketGradeDto  데이터들은 TicketGrade 도메인 생성에 쓰입니다. primitive type 으로 선언하게 되면 DB 에 null 아닌 0이 들어갈 위험이 있다고 생각했습니다!
- primitive type 을 사용하면 `@NonNull` 이 아닌  `@Min`, `@Max` 등으로 유효성 검사를 처리하면 대체가 될 것같습니다.

2023-08-08 04:28 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +public class TicketService {
아 넵 편리를 위해 클래스 레벨에 선언했는데 
트랜잭션 경계나 전파까지 고려해서 선언하겠습니다.

2023-08-08 04:28 UTC, gutenLEE commented on src/main/resources/mapper/TicketMapper.xml
> +    </select>
이후 작업에서 반영하겠습니다!

2023-08-08 04:28 UTC, gutenLEE commented on src/main/resources/schema.sql
> +    grade_id	bigint  auto_increment  NOT NULL PRIMARY KEY,
아하 놓친부분입니다 감사합니다!

2023-08-08 04:54 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +    }
객체 생성비용을 치르더라도 객체를 불변으로 유지하라는 의견을 따라보았는데요, 
setter 와 불변객체 결정 기준을 어떻게 잡아야할지 궁금합니다!

2023-08-08 06:44 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/dto/TicketRequestDto.java
확인했습니다. 이견없어서 개발 시 참고하겠습니다.

2023-08-08 06:48 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/dto/TicketRequestDto.java
추가로 도메인간 서비스 호출해서 요청하는데 @JsonProperty가 필요한 이유가 궁금합니다.

2023-08-08 09:08 UTC, yyy9942 commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +    }
불변객체를 사용한다는건 정말 불변한 상태를 유지하는 값의 성격의 오브젝트에 적합합니다.
예를 들자면, 시간이라는 값을 나타내는 `LocalDateTime`, 기간을 나타내는 `Duration` 등은 모두 불변객체입니다.

이 객체는 DB 테이블과 연결되는 엔티티의 성격을 가지고 있습니다. DB에서 데이터가 변경될 수 있는것처럼, 이 엔티티도 당연히 상태가 변경될 수 있겠습니다. 그러므로, 상태 변경을 할 수 있는 메서드를 정의해주셔도 괜찮습니다.

단순히 모든 필드에 `Setter`를 열어준다면 의도하지 않은 변경점이 있을 수 있고, 값의 변경을 추적하기 어렵기 때문에 무분별한 `setter` 사용은 지양해야 합니다. 이건 동작메서드로 구현하여 해결할 수 있겠네요.

그렇지만 불변성을 지키기 위해 모든 객체를 불변하도록 만든다면 상태 변경이 필요한 객체에서도 사용하기가 꽤 어려워질거에요. 불필요한 객체를 생성시키고, 사용하기도 어렵다면 얻을 수 있는 장점이 적어집니다. 장단점을 비교해보고 불변성이 이 객체에 적절한지를 고민해주시면 될 것으로 보입니다~

2023-08-08 09:09 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +    }
불변객체를 사용한다는건 정말 불변한 상태를 유지하는 값의 성격의 오브젝트에 적합합니다.
예를 들자면, 시간이라는 값을 나타내는 `LocalDateTime`, 기간을 나타내는 `Duration` 등은 모두 불변객체입니다.

이 객체는 DB 테이블과 연결되는 엔티티의 성격을 가지고 있습니다. DB에서 데이터가 변경될 수 있는것처럼, 이 엔티티도 당연히 상태가 변경될 수 있겠습니다. 그러므로, 상태 변경을 할 수 있는 메서드를 정의해주셔도 괜찮습니다.

단순히 모든 필드에 `Setter`를 열어준다면 의도하지 않은 변경점이 있을 수 있고, 값의 변경을 추적하기 어렵기 때문에 무분별한 `setter` 사용은 지양해야 합니다. 이건 동작메서드로 구현하여 해결할 수 있겠네요.

그렇지만 불변성을 지키기 위해 모든 객체를 불변하도록 만든다면 상태 변경이 필요한 객체에서도 사용하기가 꽤 어려워질거에요. 불필요한 객체를 생성시키고, 사용하기도 어렵다면 얻을 수 있는 장점이 적어집니다. 장단점을 비교해보고 불변성이 이 객체에 적절한지를 고민해주시면 될 것으로 보입니다~

2023-08-08 09:11 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/TicketGrade.java
> +    }
이 경우에도 "DTO가 Entity의 존재를 알아야 하는가?`, `Entity와 DTO가 서로 의존성을 가져야 하는가?`와 같은 근본적인 질문이 나올 수 있습니다. 이 부분은 개발 철학과 관련된 고민이니 이런 고민을 하는 사람들도 있구나~ 하고 넘어가주시면 됩니다.  좋은 코드를 고민하시다 보면 이러한 고민이 점점 생기실텐데 그 때 깊은 고민을 해보시는것도 좋겠네요.

2023-08-08 09:12 UTC, f-lab-maverick commented
conflict가 발생하고있네요~ 수정하시면서 충돌해결도 같이 진행해보시겠어요?

2023-08-08 09:58 UTC, gutenLEE commented on src/main/java/com/heeverse/member/domain/entity/Member.java
> +            @Param("email") String email) {
@ZhenxiKim 

mybatis 설정 옵션 `arg-name-based-constructor-auto-mapping=true` 으로 변경하니
디버깅 결과 쿼리 resultSet 를 객체로 맵핑할 때 생성자 파라미터 이름과 컬럼명 일치 검사 로직을 탑니다. 

```java
Param paramAnno = param.getAnnotation(Param.class);
String paramName = paramAnno == null ? param.getName() : paramAnno.value();
``` 
생성자 파라미터에 `@Param` 어노테이션이 없을 경우 파라미터의 이름을 가져오는데, 
문제는 파마리터 이름이 `arg+ [생성자 파라미터 순서]` 로 생성이 되버려서 
컬럼명 일치 검사에서 실패했습니다. 

`@Param` 선언하여 임시로 해결은 했으나 매번 이 어노테이션을 선언해야하는 불편함이 있을 것 같습니다. 
해결책을 찾아보고 반영하겠습니다!

2023-08-08 10:05 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/dto/TicketRequestDto.java
공연 도메인에서 클라이언트 요청 DTO에 중첩 DTO 로 이것을 사용할까 싶어 만들었는데
정희님 작업하실때 사용하지 않으면 어노테이션 삭제하겠습니다!

2023-08-08 11:52 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 코멘트 확인해주시고, 머지해주셔도 좋습니다.

2023-08-08 11:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +    }
1. 이렇게 생성자 내부에서 `ticketSerialNumber`를 생성해주도록 설정한 이유가 있을까요?
2. `ticketSerialNumber`에는 별도의 비즈니스 로직은 넣지 않을 예정인가요? (추적이 편하도록 날짜_공연장_ID 형식으로 생성하기도 합니다)
3. `ticketSerialNumber`를 생성하는 로직을 테스트할 수 있을까요?

2023-08-08 11:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +    }
이것도 static method일 필요는 없어보이네요.

2023-08-08 11:52 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket/dto/TicketRequestDtoTest.java
> +    }
이러한 테스트는 분리해주시는게 어떤 기능이 테스트 실패하는지 확인하기 좋습니다.
이 테스트가 깨질 때 정확하게 어떤 기능이 깨진건지 알기 어렵지 않을까요?

2023-08-08 11:52 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket/dto/TicketRequestDtoTest.java
> +    }
추가적으로, 만약 이렇게 동시에 여러가지를 테스트해야하는 경우 `assertAll`을 사용해주시는게 좋습니다.
왜냐하면 여러개의 단언문이 있을 경우, 상단에 있는 단언문이 깨질 경우 하단에 있는 단언문을 실행조차 하지 않기 때문입니다.

`assertAll`의 경우 [여기](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions)를 참고해주시면 됩니다.

2023-08-08 14:19 UTC, merged