[#17] 티켓 생성 기능
f-lab-edu/heeverse-ticket pull request #21
Opened 2023-08-11 09:16 UTC by gutenLEE

## 개요
- 관련 Issue 번호 : #17 

## 작업사항

- 티켓 생성 개발
    - 티켓 시리얼 넘버 생성
      -  시리얼 넘버 생성 로직과 데이터는 비즈니스 로직이라 판단하여 Util 클래스를 사용하지 않았습니다.
      -  유일 ID 를 생성 로직 변경, 유일 ID  타입 변경을 고려해 설계했습니다. 
      -  유일 ID 생성에 필요한 인자들 변경을 고려해 `SerialTokenDto` 상속 구조를 사용했습니다.
      -  티켓의 유일ID 구성은 `[공연일]-[공연 시퀀스]-[티켓 등급]-[티켓 생성 순서]` 입니다.
<img src="https://github.com/f-lab-edu/heeverse-ticket/assets/61870748/419f9493-4852-4192-9f57-eb1a9532a0e4" width="600px">  

## 변경로직

### 변경전
이전 PR #20 
- 티켓, 티켓 등급, 좌석 개념을 설계함

### 변경후
- 좌석 개념 제거하고 티켓과 등급별 티켓으로 변경
- 잘못 작성한 테스트 코드 제거

2023-08-11 09:32 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +
이런 생성 로직은 일급콜렉션 내부로 캡슐화 하는게 어떤지 궁금합니다. 

여기서 들었던 궁금한 점이 3가지 있습니다. 
- `List<ticketGradeDto>`을 `List<ticketGrade>` 로 변환하는 로직이 생성자에 위치하면 
무거운 작업이 아닐까 싶었습니다. 예를 들면 List 사이즈가 몇십 만개가 되는 상황들..

- 그 다음 고민은 그럼 static 메서드를 사용해야 하는데 
static 팩토리 메서드는 지양하지도 지향하지도 않는다는 의견을 보았습니다. 
이펙티브 자바에 등장하는 장점들로 스태틱 팩토리 메서드를 무조건 채택하기엔 개발자마다 의견이 다른듯합니다. 
선택 기준을 어떻게 잡아야할까요. 작업 비용이 낮을때? 아님 PR 을 통한 토론과 설득 후 채택 ? 등등..  궁금합니다.

- 일급 콜렉션에서 엔티티 객체를 생성해도 문제 없을까요?

2023-08-11 09:32 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +
실무에서 다른 개발자가 개발하는 피처에서 생성하는 DTO 가 필요하고 구조가 아직 미확정일땐
이렇게 주석 처리하고 푸쉬해도 괜찮을까요? (개발 브랜치 한정)

2023-08-12 05:04 UTC, ZhenxiKim reviewed
리뷰 완료하였습니다.

2023-08-12 05:04 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/service/TicketService.java
>      public TicketService(TicketMapper ticketMapper) {
관습적인 코드는 롬복(`@RequiredArgsConstructor`)으로 코드를 줄일 수 있을거같습니다.

2023-08-12 05:04 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +        return 0 < ticketMapper.countTicket(ticketRequestDto.concertId());
가독성 측면에서 비교대상을 좌측, 비교 조건을 우측에 두는것이 좋을거 같습니다.

2023-08-12 05:04 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +
첫번째 항목에 답을 하자면 List<GradeTicket>로 변환하는 작업에서 변환 로직에서 DB를 갖다오거나, 복잡한 연산이 있어야 무거운 작업이 되지 않을까 생각됩니다. 또한 기본 for문이 아닌 stream을 써서 내부 연산을 하기때문에 성능적으로도 더 좋을거같습니다. 
그리고 무거운 작업이 아니라면 생성자를 통해 객체를 변환하는게 객체 생성 시 어떤 주입이 필요한지 명시적으로 개발자에게 알려주기때문에 생서자로 변환하는것이 적절한 것 같습니다.

이러한 코드로직은 성능 테스트 요소로 삼아보면 좋을거같습니다~

2023-08-12 05:04 UTC, ZhenxiKim commented on src/main/java/com/heeverse/common/TicketSerialNumber.java
> +public class TicketSerialNumber implements SerialNumber<String> {
SerialNumber인터페이스는 공통의 기능을 추상화하여 common 패키지가 적절해 보이지만 TicketSerialNumber는 ticket 도메인 성격으로 ticket 도메인으로 옮겨도 될듯합니다.

2023-08-12 05:04 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    private String generateTicketSerialNumber(TicketRequestDto ticketRequestDto, GradeTicket grade, int idx) {
공연 도메인에서 요청한 TicketRequestDto에 대한 null체크가 추가되면 좋을거 같습니다.

2023-08-12 05:13 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +        return 0 < ticketMapper.countTicket(ticketRequestDto.concertId());
이건 예전에 블랙잭에서 멘토님께 피드백 받은 내용 공유드립니다

```
약간의 팁을 드리자면 부등호 조건을 설정할 떄에는 읽기 편하도록 아래처럼 설정해주시는게 좋습니다. 
사람의 뇌는 직관적으로 읽히는 방향이 아래와 같거든요.

1. `<`일 때에는 변수가 오른쪽
2. `>`일 때에는 변수가 왼쪽

`if (number < 2 || 14 < number)`
```

2023-08-12 05:22 UTC, gutenLEE commented on src/main/java/com/heeverse/common/TicketSerialNumber.java
> +public class TicketSerialNumber implements SerialNumber<String> {
옮기겠습니다!

2023-08-13 14:35 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +
네~ TODO로 달아두면 아직 개발이 진행중이라는걸 알 수 있습니다.
미완성인 기능을 머지하는건 또 다른 문제이겠지만, 작업중일 때 TODO로 해두는건 이슈 없습니다~

2023-08-13 14:36 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
>      public TicketService(TicketMapper ticketMapper) {
깃헙에서 어노테이션이나 코드를 작성하실 때에는 \` 을 사용하여 감싸주면 코드처리가 됩니다.
어노테이션으로 코드블럭 없이 작성하니 다른 사용자에게 태그가 걸리네요~

2023-08-13 16:34 UTC, f-lab-maverick requested changes
현재 `TicketSerialNumber`는 객체 자체로는 아무런 역할과 상태를 가지지 않고, 입력값을 받아 번호를 생성해주는 팩토리역할만 하고 있습니다.

이러한 형식 보다는, 생성자를 통해 생성될 때 내부에 생성된 SerialNumber를 들고있게 만들면 이 객체를 일급객체처럼 사용할 수 있겠네요. 

추상화는 꽤 잘 만들어주신것으로 보입니다 👍  리뷰 확인해서 한번 수정해보시겠어요?

2023-08-13 16:34 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/SerialTokenDto.java
> +    Delimiter delimiter;
접근제어자가 빠져있네요~

2023-08-13 16:34 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/TicketSerialNumber.java
> +    }
`StringJoiner`를 null로 선언할 필요가 있을까요? try문 내부에 return을 넣는다면 어떨까요?
최대한 변수 선언시 null이 들어가는 상황을 피해주세요. 대부분의 버그와 예외에서 NPE가 상위 순위를 차지하는 만큼 null을 다룰때에는 최대한 조심해주시는게 좋습니다.

2023-08-13 16:34 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/TicketSerialNumber.java
> +public class TicketSerialNumber implements SerialNumber<String> {
꽤 재미있는 인터페이스 구조를 만드셨네요. 제네릭을 조금 더 사용한다면 `public String generate(SerialTokenDto serialTokenDto)`에도 제네릭을 적용해서 `TicketSerialTokenDto tokenDto = (TicketSerialTokenDto) serialTokenDto;`와 같은 형변환을 안해도 되도록 만들 수 있을거같은데 시도해보시겠어요?

2023-08-13 16:34 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +                ticketSerialNumber, gradeTicket.getConcertId(), gradeTicket.getGradeName());
티켓의 SerialNumber를 좀 더 검증된 값으로 받기 위해서는 생성자 파라미터로 `TicketSerialNumber` 타입으로 입력받은 후, 내부에서 String으로 상태를 저장해주는게 좋습니다.
현재상태라면 파라미터로 모든 종류의 String이 들어올 수 있으므로, 검증된 타입을 파라미터로 받아서 버그 발생 가능성을 낮추는건 어떠신가요?

2023-08-13 16:34 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/TicketSerialNumber.java
> +    }
상태에 영향을 미치지 않는 일급함수로 보이지만, 이 클래스 내부에서만 사용하는 메서드라면 좀 더 적절한 접근 제어자를 사용해주는게 좋을 것으로 보이네요~

2023-08-13 16:34 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/TicketSerialNumber.java
> +        return sj.toString();
이렇게 `.add`를 통해서 계속해서 문자를 추가하는 연산으로 만드니 최종적으로 어떤 모습의 문자열이 나오는지 한눈에 들어오지 않습니다. 이런 경우 `String.format`을 사용해 주시거나, 덧셈연산으로 문자열을 만들어주셔도 좋습니다.

2023-08-14 05:18 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
> +                ticketSerialNumber, gradeTicket.getConcertId(), gradeTicket.getGradeName());
아하 생성자 파라미터로 필드 할당해줄 값만 받아야되는줄 알았는데 
초기화 작업에 필요하면 전략 객체같은 참조값을 받아도 괜찮군요

2023-08-16 07:05 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/domain/TicketSerialNumber.java
> +            sj.add(addPad(tokenDto.getIndexAsString(), tokenDto.getTicketCountStrLength()));
문자열 덧셈, format 모두 적용해봤는데 값이 5개나 되다보니까 가독성이 요게 젤 나았습니다..

2023-08-16 11:30 UTC, f-lab-maverick requested changes
`TicketSerialNumber`부분에 수정할 부분이 더 보이네요. 코멘트 확인 후 수정부탁드려요~
제가 드린 의견 외로 다른 의견이 있다면 자유롭게 주셔도 좋습니다 :)

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/SerialNumber.java
> +}
제가 피드백드린 의도대로 잘 작성해주셨네요~ 👍

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/SerialTokenDto.java
> +}
setter가 없다면 불변객체 또는 일급 객체로 만들어도 될 것으로 보이네요.
단순히 `delimiter`를 final로 선언하는것 만으로도 많은 장점을 얻을 수 있습니다. 불변객체는 어떤 장점이 있을까요?

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/TicketSerialNumber.java
> +        }
TicketSerialTokenDto의 내부 파라미터가 not null이라는 보장이 있다면 이러한 NPE처리는 불필요해지지 않을까요? `TicketSerialTokenDto` 생성자에서 이런것들을 검증한다면 한층 더 깔끔한 코드가 나올것으로 보이네요~

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/GradeTicket.java
> +    }
메서드를 호출하며 null을 넣는 행위는 지양해야합니다.
만약 초기화가 안되어야하는 필드가 있다면 별도의 생성자를 만들어주는건 어떨까요? null은 최대한 안전하게 다루는 습관을 들여야 개발자의 실수로 인한 NPE가 발생하지 않습니다~

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
>      }
중복되는 생성자 로직이 보이네요~ 생성자 코드 중복도 관리 대상입니다. 중복 코드가 발생하면 이후 수정할 때 모든 중복코드를 찾아서 수정해야하는 번거로움이 생기고, 누락에 대한 휴먼에러가 발생될 수 있습니다.

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/TicketSerialNumber.java
> +public class TicketSerialNumber implements SerialNumber<String, TicketSerialTokenDto> {
이 클래스는 내부 상태가 없으며, 이에 따라 인스턴스화도 필요하지 않은 객체로 보이네요.

단순히 `TicketSerialTokenDto`를 받아서 문자열을 리턴해주는 역할을 한다면 유틸성 static method로도 처리가 가능합니다.

이 클래스를 일급객체로 다뤄보는건 어떠신가요?

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    private final TicketSerialNumber serial = new TicketSerialNumber();
이렇게 빈 객체를 만든다는 것은 내부 상태의 초기화가 되었을 수도 있고, 안되었을 수도 있다는 불완전한 상태를 주게 됩니다. 인스턴스화를 했다면 완전한 상태로 사용할 수 있도록 만들어주는건 어떨까요?

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    private final TicketSerialNumber serial = new TicketSerialNumber();
이 클래스의 경우 내부 상태가 없는 특수한 클래스입니다. 그렇다면 꼭 인스턴스화를 할 필요가 있을까요?

이 클래스는 토큰을 받아서 문자열을 리턴해주는 역할을 하고 있습니다. `TicketSerialNumber`라는 네이밍이 적절할까요?

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    }
이건 테스트용 메서드로 보이는데 삭제해주세요~

2023-08-16 11:30 UTC, f-lab-maverick commented on src/test/java/com/heeverse/common/SerialNumberTest.java
테스트코드 잘 작성해주셨네요~ 이전보다 많이 발전한 모습이 보입니다.

2023-08-16 11:30 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/TicketSerialNumber.java
> +public class TicketSerialNumber implements SerialNumber<String, TicketSerialTokenDto> {
또는 이 클래스를 유틸성 클래스로 만들고, static method만 남겨도 좋을거같습니다~ `TicketSerialNumberFactory`와 같은 네이밍을 해도 좋을거같네요.

2023-08-17 02:50 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    }
앗 넵!

2023-08-17 04:31 UTC, gutenLEE commented on src/main/java/com/heeverse/common/SerialTokenDto.java
> +}
불변객체란 한 번 생성되면 수정할 수 없는 객체입니다. 

불변객체의 장점
- 멀티스레드 환경에서 쓰기 작업의 동기화 제어가 필요없어 안정성이 높다.
- 쓰기 작업이 필요 없어 Cache, Map, Set 등의 요소로 활용하기에 적합하다.
- 불변 객체가 소유한 객체들은 불변객체와 생명을 같이하여 CG 스캔 대상에서 제외되므로 GC 성능 높일 수 있다. 

불변객체 조건
- 수정자 메서드 만들지 않기
- 필드 접근 제어자 `private` 선언
- 상속 관계에서 수정을 차단하기 위해 `final`  선언
- 콜랙션 타입은 getter 메서드에서 수정 불가능한 콜렉션으로 변환해서 리턴하기
- 필드에 가변 객체가 있을 경우 방어적 복사해주기


상속 관계에서 수정할 수 있는 상황을 놓쳤네요... 반영하겠습니다!

2023-08-18 04:13 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket/domain/mapper/TicketTestHelper.java
이전에 주신 피드백중 테스트에서 재사용할 로직들을 헬퍼 클래스에 두는 방법을 알려주셨는데, 
적용해봤습니다. 

콘서트 브랜치가 머지된 후 로직을 채워넣겠습니다.

2023-08-18 04:13 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket/domain/TicketSerialNumber.java
- 피드백 주신 일급객체를 적용하며 느낀점들을 공유하자면, 

    1. `TicketSerialNumber` 가 시리얼번호 상태를 갖고 생성자에서 생성하게 만듦으로써 
          시리얼 번호 관심사의 응집도가 높아졌습니다. 


    2. 이전 로직인 `Ticket` 생성자에서 시리얼 생성 메서드를 호출, 작업중 예외 발생하면 
     `Ticket` 이 불완전한 상태로 생성될 가능성이 있습니다.

2023-08-18 14:42 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/TicketSerialNumber.java
그렇죠~ 그렇다면 이 `TicketSerialNumber`형태의 객체가 넘어올 때에는, 이미 검증된 값이라는걸 이제 단언하고 사용할 수 있겠네요

2023-08-18 14:51 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 머지해주셔도 좋습니다.

2023-08-18 14:51 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/TicketSerialNumber.java
> +    }
형변환을 하여 리턴할 때에는 `toXxx`와 같은 네이밍을 지어줄 수도 있습니다. 이 경우에는 `toString`을 사용할 수도 있겠네요. (`getSerial`도 나쁜 네이밍은 아닙니다.)

2023-08-18 14:51 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +                                    ), grade)
제가 이전에 불필요한 객체 생성을 지양해 보도록 피드백드리면서 동시에 이후에 이와 반대되는 피드백을 드릴것이라는 말씀을 드렸던게 기억나실까요?

그 예가 이러한 코드로 나오는 것으로 보입니다. "불필요한 객체 생성"은 객체생성을 하지 않고도 처리할 수 있는 로직에서는 생성을 지양하라는 피드백이며, 이러한 코드에서는 오히려 객체 생성이 더 많아져도 좋은 이유로는 이게 "필요한 객체 생성"으로 인식되기 때문입니다.

이렇게 명시적인 객체로 메시지를 전달하면 받는쪽에서는 정해진 타입으로만 메시지를 전달받고, 검증된 값을 받아서 추가적인 검증로직을 수행하지 않아도 되는 등 여러가지 장점이 생깁니다.

따라서 "필요한 객체 생성"이라는 판단이 들면 `new`연산자를 많이 사용해주셔도 좋습니다 :)

2023-08-18 14:51 UTC, f-lab-maverick commented on src/test/java/com/heeverse/common/AssertUtils.java
> +    }
`RunMethod `보다는 Runnuble interface를 받도록 해두시는게 좋을것으로 보이네요. 일반적으로 functional interface를 사용할 때에는 [이미 만들어진 범용 인터페이스](https://www.baeldung.com/java-8-functional-interfaces)를 사용하는 습관을 들이면 좋습니다.

2023-08-18 14:51 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket/dto/TicketRequestDtoTest.java
> +        concertSeq = TicketTestHelper.콘서트_생성하고_시퀀스_반환();
👍

2023-08-21 03:15 UTC, merged