[#18] concert 도메인 생성
f-lab-edu/heeverse-ticket pull request #22
Opened 2023-08-11 09:20 UTC by ZhenxiKim

## 개요
- 관련 Issue 번호 : #18 

## 작업사항

- 공연 도메인 생성 api 개발
- 공연 생성시 같이 생성되는 티켓 생성 호출은 미완성부분입니다.
- dev 브랜치 커밋을 댕겨오느라 dev 브랜치 커밋 파일이 같이 존재합니다. 이는 commit (a8c07c6fb1ee21bf50feec3bdf24393b49148948)으로 묶어서 commit 했습니다.

## 변경로직

### 변경전

### 변경후
- h2 security 설정 추가
- schema.sql FK 비식별관계로 설정

2023-08-11 09:31 UTC, ZhenxiKim commented on src/main/java/com/heeverse/concert/controller/ConcertController.java
> +    private static void validateTimeOrder(LocalDateTime beforeTime, LocalDateTime afterTime, String msg) {
request DTO 값에 대한 validation을 controller단에서 검사했는데, 공연 도메인의 값이기도 하여 Concert 클래스에서 처리하는게 적절한지 컨트롤러에서 하는것이 적절한지 궁금합니다.

2023-08-11 09:31 UTC, ZhenxiKim commented on src/test/java/com/heeverse/concert/dto/ConcertRequestDtoTest.java
> +    void requestDto_validation_success_test() {
requestDto 단위테스트는 작성하다 만 코드를 올렸네요 다음 pr에서 다시 작성하겠습니다.

2023-08-12 03:17 UTC, gutenLEE commented on src/main/java/com/heeverse/concert/service/ConcertService.java
> +            }
저는 등급별 티켓도 티켓 도메인의 역할이라 생각하여 티켓 서비스에 이 로직을 만들었는데 협의가 필요할 것 같습니다
등급별 티켓 관련 클래스들이 중복 작업되었습니다!

2023-08-12 03:17 UTC, gutenLEE commented on src/main/java/com/heeverse/concert/controller/ConcertController.java
> +    private static void validateTimeOrder(LocalDateTime beforeTime, LocalDateTime afterTime, String msg) {
저의 생각은 
검증의 목적이 사용자가 논리적으로 적합한 날짜 입력에 대한 검증이라면 
controller나 requestDto 또는 커스텀 밸리데이션 어노테이션으로 유효성 검사를 진행하고 
공연 날짜에 관련된 비즈니스 로직에 사용되는 검사면 concert 클래스에 작성하는게 좋을 듯 싶습니다

2023-08-12 03:17 UTC, gutenLEE commented on src/main/java/com/heeverse/concert/service/ConcertService.java
> +        }
`ConcertRequestDto` 를 리스트 받는 이유가 사용자가 여러 가수의 콘서트를 한 번에 등록하는 상황을 고려하신게 맞을까요?!

공연 등록에 연관된 테이블이 공연, 티켓, 등급별 티켓 3개입니다. 
여러 공연 중 특정 공연 등록 과정에서 예외가 발생하면 앞서 정상 등록된 공연 정보들도 롤백하는게 맞는지
실패한 공연만 롤백하는게 맞는지 정책이 필요할 것 같습니다!

2023-08-12 03:33 UTC, gutenLEE commented on src/main/java/com/heeverse/concert/controller/ConcertController.java
> +    private static void validateTimeOrder(LocalDateTime beforeTime, LocalDateTime afterTime, String msg) {
저도 추가로 궁금한 것이
실무에서 View 레이어의 Dto, 서비스 레이어에 도메인 개발, 유지보수 개발자가 다를 경우에
dto 에서 유효성을 제거해버리면 도메인쪽이 영향을 받을텐데 이런 상황을 고려해서
dto, 도메인에 중복이더라도 각각 유효성 검사 로직을 넣나요?!

2023-08-12 06:34 UTC, ZhenxiKim commented on src/main/java/com/heeverse/concert/service/ConcertService.java
> +            }
공연에서는 티켓 등급 요청에 대한 파라미터와 함께 티켓 서비스를 호출하기로 하였습니다. 콘서트서비스에서 TicketGrade관련 로직 제거하겠습니다.

2023-08-12 06:35 UTC, ZhenxiKim commented on src/main/java/com/heeverse/concert/service/ConcertService.java
> +        }
넵 관리자가 1~N개의 공연정보를 생성할 수 있다고 생각했습니다. 
회의 후 공연은 논리적으로 상위 도메인이므로 하위 도메인 생성 중 예외 발생 시 롤백하는 정책으로 정했습니다.

2023-08-12 13:20 UTC, f-lab-maverick requested changes
validation관련해서 어떤 레이어에서 검증을 진행해야할지, 어떤 검증을 해야할지, 검증 로직의 위치는 어디에 두어야할지 고민을 하시는거같네요. 이런 부분은 정답이 없는 문제입니다.

그렇기 때문에 최대한 관리하고 유지보수하기 좋은 코드로 만들기 위해서는 소통과 협의를 통해 코드 컨밴션을 맞춰야겠습니다. 이 부분은 같이 리뷰해보면 좋을듯하여 미팅 일정 드리도록 하겠습니다.

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/controller/ConcertController.java
> +@RequestMapping(value = "/concert")
어노테이션에서 value는 생략이 가능합니다.
```suggestion
@RequestMapping("/concert")
```

2023-08-12 13:20 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket/dto/TicketRequestDtoTest.java
> +        assertViolationCount(new TicketGradeDto( null, 0), 3);
`TicketGradeDto` 생성자 파라미터 앞쪽에 불필요한 공백이 있는 것으로 보이네요~

2023-08-12 13:20 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket/domain/mapper/TicketTestHelper.java
> +                new TicketGradeDto( "R석", 4000)
`TicketGradeDto` 생성자 파라미터에 존재하는 공백을 제거해주시는게 좋겠습니다.

2023-08-12 13:20 UTC, f-lab-maverick commented on src/test/java/com/heeverse/concert/dto/ConcertRequestDtoTest.java
> +    void requestDto_validation_success_test() {
`유효성 검증에 통과한다`와 같은 통짜 테스트 보다는 특정 유효성에 실패한다, 모든 검증에 성공한다 등으로 케이스를 세분화해주시는게 좋습니다. 이렇게 세분화해주셔야 이후 테스트가 실패할 때 정확히 어느 부분에서 테스트가 실패하는지 파악할 수 있습니다.

2023-08-12 13:20 UTC, f-lab-maverick commented on src/test/java/com/heeverse/concert/controller/ConcertControllerTest.java
> +        perform.andExpect(status().isCreated());
이렇게 내부 값까지 모두 검증하도록 해둔다면 DTO에 값이 추가되거나, 시그니처가 변경되었을 때 테스트가 쉽게 깨지게 됩니다.

모든 값을 검증하려하지 말고, 필수적으로 존재해야 하는 값과 로직을 테스트해보시겠어요?

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +);
concert와 식별관계를 정의하신건가요?
그렇다면 컬럼 명을 seq가 아닌 concert_seq로 정의해주어야 명확하게 식별관계라는걸 보여줄 수 있겠네요~

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +    delete_yn       boolean               NOT NULL COMMENT '삭제여부',
`delete_yn`이라는 컬럼명은 `y` / `n`이라는 값 중 하나가 표현된다고 볼 수 있습니다.
이 컬럼의 경우 boolean 타입이고, true/false의 값을 가지네요. 이런 경우 ~~_flag / is_~~ 이런 형식의 네이밍을 가지도록 만드는게 더 명시적이겠습니다.

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +    status          varchar(20)           NOT NULL COMMENT '완료, 취소',
어떤 status인지 명시해주지 않으면 DB에서 쿼리시 헷갈릴 수 있습니다.
이 경우 티켓의 유효 상태라는걸 나타내고 있으므로 그에 맞는 적절한 네이밍을 해주시면 좋겠네요.

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +    purchase_date        timestamp             NULL COMMENT '구매 일시',
다른 시간관련 컬럼은 `datetime`을 사용하는데, 이 컬럼은 `timestamp`를 사용하네요~ 다르게 사용하는 이유가 있을까요?
단순 오타라면 이런 시간컬럼은 통일해주셔야 이후 시간 비교/검색시 성능 저하를 막을 수 있습니다.

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/resources/schema.sql
> +    delete_yn            boolean               NOT NULL COMMENT '취소여부',
취소여부와 삭제여부는 비즈니스로직으로 다르게 처리될 수 있습니다. 코멘트와 컬럼명을 통일해주시는게 어떨까요?

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/resources/mapper/GradeTicketMapper.xml
> +    VALUES (#{gradeName}, #{ticketCount}, #{concertId}, #{createDateTime});
`;`가 있으면 실제 쿼리 작동시 에러가 날거같습니다~

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/resources/mapper/ConcertMapper.xml
> +    VALUES (#{concertName}, #{concertDate}, #{ticketOpenTime}, #{ticketEndTime}, #{createDateTime});
여기도 세미콜론이 있네요

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +                .requestMatchers(HttpMethod.POST, "/concert").permitAll()
새로 생성되는 모든 POST 요청에 대해 인증처리를 안하는것으로 보이는데 개발용으로 열어두신건가요?

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/service/ConcertService.java
> +    @Transactional(propagation = MANDATORY)
propagation을 이렇게 적용하신 이유가 있으신가요?

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/dto/ConcertResponseDto.java
미완성 클래스의 경우 일반적으로 push하지 않기는 합니다. 이대로 올라온다음 관리되지 않는 경우도 있기 때문이죠

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/dto/ConcertRequestDto.java
> +    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:Ss")
패턴이 계속 반복되고있습니다. 이 경우 공통으로 사용할 패턴을 상수로 정의해준다면 오타위험과 코드중복을 방지할 수 있지 않을까요?

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/dto/ConcertRequestDto.java
> +    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:Ss")
`@Future(message = "현재 시간보다 이후여야합니다.")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:Ss")`
이 패턴이 고정이라면 이 두개를 조합한 신규 어노테이션을 만들어주셔도 좋습니다.

2023-08-12 13:20 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/controller/ConcertController.java
> +    private static void validateTimeOrder(LocalDateTime beforeTime, LocalDateTime afterTime, String msg) {
각각의 레이어에서 검증해야 하는 내용이 다른 경우가 꽤 있어서, 레이어마다 검증을 다르게 두는건 괜찮습니다~

2023-08-13 13:04 UTC, f-lab-maverick commented
@ZhenxiKim @gutenLEE 
검증로직의 위치에 대한 고민을 하시는걸 보니 이번 피드백은 각 레이어드 아키텍처에서 도메인과 DTO의 분리에 대해 이야기해볼까 합니다. 이번 피드백을 고민해보신다면 클래스의 분리를 진행한 후 어디에 로직이 위치하면 좋을지 고민하는것에 대해 조금 더 좋은 방향으로 고민이 될 것으로 보이네요 :)

일반적으로 많은 개발자들이 흔히 개발하는 방법으로 "모든 데이터 조회 로직은 DB에 위임", "모든 데이터 처리 로직은 Service에 위임", "모든 처리는 하나의 도메인당 하나의 DTO에 위임"과 같은 개발방법을 즐겨 사용합니다. 이러한 방식은 복잡한 검색 쿼리를 통해 DB에서 데이터를 아추 큰 하나의 DTO로 조회해온 후, 이 DTO를 여러 로직에서 돌려 사용합니다. 이럴 경우, 이 하나의 DTO는 Controller에서 파라미터로 받는 용도로 사용하기도 하고, 비즈니스 로직을 수행하며 DB저장의 목적으로도 사용하게 됩니다.

이럴 경우 발생하는 이슈로는, 이 DTO가 너무나 많은 일을 하도록 만든다는겁니다. 그렇게 되면 아래와 같은 상태가 되겠죠.
![image](https://github.com/f-lab-edu/heeverse-ticket/assets/131429812/d75ea1d5-f915-4a04-b23a-7cf0022ae182)


이 DTO는 더 이상 누군가가 수정할 수 없습니다. 필드를 수정/삭제하면 어디서 어떤 일이 발생할지 예측할 수 없어집니다. 기능의 변경이 필요하다면 필드를 추가하는 형식으로 DTO를 수정하게 되고, 이 DTO는 점점 필드가 많아지게 됩니다. 그리고 이 필드들은 특정 상황에만 사용되고 초기화되기 때문에 항상 null을 체크하고 유효성에 맞는지 DTO에서 데이터를 꺼낸 후 검증이 필요하게 됩니다.

이런 상황이 발생한다면 코드가 점점 스파게티코드가 되고, 여러 사람의 손을 탈수록 수정이 아닌 필드 추가만 하기 때문에 점점 더 유지보수하고 운영하기에 어려운 코드가 됩니다. 이런 상황을 피하기 위해서는 클래스와 DTO, 도메인의 분리가 필수적입니다.

분리가 된다면 이러한 모습이 되겠네요.
![image](https://github.com/f-lab-edu/heeverse-ticket/assets/131429812/2f0f05df-b3c7-412a-8bc3-aa81f3c8a2f3)

몇개로 분리할지, 어떻게 분리할지는 자유롭게 고민해보시는게 좋습니다. 단, 하나의 클래스로 너무 많은 역할을 하지 않도록 만드는게 좋겠네요. 이번 검증부분도 Controller에서 넘어온 값을 검증하고, 저장하기 전 최종 유효성 검사를 하는 DTO(Entity)를 분리하면 검증이 어떤 위치로 오는게 좋을지 감이 오실거같습니다~

여기서 좀 더 도메인의 역할을 크게 보도록 고민한 개발 방법론이 DDD입니다. DDD가 만능은 아니지만 일부 차용하여 사용할 부분은 있다고 느껴져요. 이 글을 참고해보시겠어요? https://umbum.dev/1206

2023-08-14 06:49 UTC, ZhenxiKim commented on src/main/resources/schema.sql
> +    purchase_date        timestamp             NULL COMMENT '구매 일시',
단순오타였습니다. 수정하겠습니다!

2023-08-14 07:04 UTC, ZhenxiKim commented on src/main/resources/schema.sql
> +    delete_yn            boolean               NOT NULL COMMENT '취소여부',
다른 로직을 하나의컬럼에 담았네요 분리하겠습니다.

2023-08-14 08:53 UTC, ZhenxiKim commented on src/main/resources/mapper/GradeTicketMapper.xml
> +    VALUES (#{gradeName}, #{ticketCount}, #{concertId}, #{createDateTime});
테스트 시 문제가 없었고, 몇몇 사이트에서; 사용이 간간히 보여서 문법적으로 문제가 없는 줄 알았습니다. 추가적으로 검색해본 결과 몇몇 DB에서는; 이 쿼리문을 종결하는 구분자로 사용되지 않는다고 하여 DB 구현체 변경에 대비한 안전한 쿼리로 변경하겠습니다.

https://www.mssqltips.com/sqlservertip/6593/sql-semicolon-required-usage/

2023-08-14 09:03 UTC, ZhenxiKim commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +                .requestMatchers(HttpMethod.POST, "/concert").permitAll()
저 위 라인에서 아래 라인으로 옮겼습니다!

2023-08-14 09:07 UTC, ZhenxiKim commented on src/main/java/com/heeverse/concert/service/ConcertService.java
> +    @Transactional(propagation = MANDATORY)
MANDATORY 옵션을 자식 트랜잭션까지 적용된다고 오해했었습니다. 아래처럼 수정하겠습니다.
의도 : 공연(부모)트랜잭션 -> 티켓(자식) 트랜잭션까지 이어지는 것
변경 : 공연(부모)트랜잭션 : Propagation.REQUIRED
      티켓(자식)트랜잭션 : Propagation.MANDATORY

2023-08-17 09:18 UTC, ZhenxiKim commented on src/test/java/com/heeverse/concert/controller/ConcertControllerTest.java
> +        perform.andExpect(status().isCreated());
쉽게 깨지는 테스트 코드를 지양하기 위해 객체로 만든 뒤 json으로 변환하는 테스트 코드로 수정하였습니다.

2023-08-17 09:22 UTC, ZhenxiKim commented on src/main/resources/schema.sql
> +);
`CONSTRAINT grade_ticket_concert_seq FOREIGN KEY (seq) REFERENCES concert (seq)` 로 명칭을 세분화 하고 식별관계지만 부모테이블인(concert)의 seq를  grade_ticket의 PK로 적용할 수 없어 concert_seq를 추가하였습니다. 적용할 수없는 이유는 비즈니스 로직 상 concert : grade_ticket (1:N) 관계이므로 다른 PK가 필요했기 때문입니다.

2023-08-17 15:35 UTC, ZhenxiKim commented on src/main/java/com/heeverse/concert/dto/ConcertRequestDto.java
> +    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:Ss")
공통 상수 클래스로 빼서 다른 dto에서도 활용할 수 있도록 수정했습니다.

2023-08-18 09:48 UTC, gutenLEE commented on src/test/java/com/heeverse/concert/dto/ConcertRequestDtoTest.java
> +        ticketGradeDtoList.add(ticketGradeDto);
`ticketGradeDtoList`, `ticketGradeDto` 가 쓰이는곳이 없어서 삭제해도 될듯합니다!

2023-08-18 14:39 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 머지해주셔도 좋습니다.

2023-08-19 05:26 UTC, merged