Feat/24/concert select
f-lab-edu/heeverse-ticket pull request #29
Opened 2023-08-22 10:30 UTC by ZhenxiKim

## 개요
- 관련 Issue 번호 : #24 

## 작업사항

- join으로 인한 도메인 조합 결과는 도메인 클래스를 따로 생성하지 않도 dto끼리 통신
- @ResponseStatus + spring dev tools로 인한 api response에 불필요한 trace 추가됨
  - spring dev tools 라이브러리의 특정 기능을 사용하지 않아 제거
- 로그 추가
- 티켓 생성 요청 시 LocalDate -> LocalDateTime으로 타입 변경

2023-08-22 11:01 UTC, f-lab-maverick commented
conflict가 발생하고있습니다~ 이거 먼저 해결해주세요~

2023-08-22 11:26 UTC, f-lab-maverick requested changes
고생하셨습니다~ 코멘트 확인 후 수정, 답변 부탁드려요~

2023-08-22 11:26 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/controller/ConcertController.java
> +    }
페이징을 관리하실 때에는, Spring data 프로젝트에 있는 Pageable처럼 공통으로 페이징을 담당할 수 있는 인터페이스나 클래스를 사용하여 관리해주시는게 좋습니다. Data-JPA를 사용하지 않는다면 의존성이 없을테니 직접 비슷한걸 만들어주셔도 좋습니다.

이렇게 각각 파라미터를 받게된다면 페이징을 사용하는곳마다 다 별개로 페이징 파라미터를 정의해야 하기 때문에 프로젝트 전체의 컨밴션이 어긋날 수 있습니다.

2023-08-22 11:26 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/domain/FutureDate.java
> +@ConstraintComposition(CompositionType.AND)
이 어노테이션들은 어떤 역할을 하는건가요?

2023-08-22 11:26 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/dto/persistence/SearchConcertDto.java
> +}
이 DTO는 내부 필드를 초기화할 방법이 없네요~ 초기화나 상태 정의방식을 추가해주세요.

2023-08-22 11:26 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/dto/presentation/SearchConcertRequestDto.java
> +    private int cnt;
페이지와 카운트(offset이라고도 합니다.)는 0으로 시작하는지, 1로 시작하는지 등 정의하는 사람마다 모두 다르게 정의할 수 있습니다. 프로젝트 공통으로 쓰는 페이징 로직을 정의해보는건 어떨까요?

2023-08-22 11:26 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/service/ConcertService.java
> +            .collect(Collectors.toList());
DTO를 그대로 생성자에 넘겨주는것도 좋은 방법입니다. 코드가 훨씬 간결해지고 생성자에서 요구하는 DTO의 스펙도 더 명확하게 처리할 수 있어요.

```suggestion
        return concertList.stream().map(SearchConcertResponseDto::new)
            .collect(Collectors.toList());
```

2023-08-22 11:26 UTC, f-lab-maverick commented on src/main/resources/mapper/ConcertMapper.xml
> +    </if>
이런 동적 where쿼리를 만들 때에는 여러가지 조건으로 동적 쿼리를 만들게되는데요, 조건이 2개 이상일 경우에는 where문을 어떻게 위치시켜야하는지가 애매해질 수 있습니다.

이런 경우 <where>을 사용하셔도 좋고, 아래처럼 해주셔도 좋습니다~
```
where 1=1
<if test="concertName != ''">
    and CONCERT_NAME like CONCAT('%',#{concertName},'%')
</if>
<if>
    and ...
```

2023-08-22 11:26 UTC, f-lab-maverick commented on src/main/resources/mapper/ConcertMapper.xml
> +    OFFSET ${page}
페이징 로직이 이상하네요~
1. limit와 offset에 들어가는 파라미터가 의도된 페이징 동작을 하나요?

3. `SearchConcertRequestDto`를 보면 page와 cnt 모두 최소값이 1인데요, MySQL에서도 이런 페이징이 1부터 시작할까요?

4. 페이징은 이렇게 LIMIT를 사용하는 방식도 있지만 성능상의 문제도 있어서 다른 방식으로도 페이징을 구현할 수 있습니다. 페이징 관련해서 어떤 방법이 있고, 성능적으로는 왜 문제가 되는지도 한번 찾아보시겠어요?

2023-08-24 09:53 UTC, ZhenxiKim commented on src/main/java/com/heeverse/concert/dto/presentation/SearchConcertRequestDto.java
> +    private int cnt;
<img width="328" alt="스크린샷 2023-08-24 오후 6 50 14" src="https://github.com/f-lab-edu/heeverse-ticket/assets/45592236/80d8d6b2-092e-4707-8573-b339700656b7">
공통된 기능은 인터페이스에 정의하고 필드 및 추가적인 기능은 추상클래스에 정의하였습니다.

2023-08-24 12:34 UTC, gutenLEE commented on src/main/resources/mapper/ConcertMapper.xml
> +    WHERE 1=1
`WHERE 1=1` 은 어떤 의미인가요?!

2023-08-24 12:52 UTC, f-lab-maverick approved these changes
통합테스트 코드도 추가되면 좋겠네요~
테스트를 통과하는지 제작해보시고 머지해주세요. 고생하셨습니다~

2023-08-24 12:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/SORTING.java
> +}
이 Enum의 이름이 모두 대문자인 이유가 있을까요?
없다면 클래스와 마찬가지로 `Sorting` 또는 `Sort`와 같은 네이밍을 지켜주도록 수정해주세요~

2023-08-24 12:52 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/dto/persistence/ConcertRequestMapperDto.java
> +}
별도로 상태 변경이 없는 객체라면 불변성을 위해 final을 선언해주는것이 좋습니다~

2023-08-25 04:49 UTC, ZhenxiKim commented on src/main/resources/mapper/ConcertMapper.xml
> +    WHERE 1=1
`where 1=1`처럼 무조건 통과하게 하는 조건을 추가한 이유는

```sql
<if test="concertName != ''">
    where CONCERT_NAME like CONCAT('%',#{concertName},'%')
</if>
<if>
    and ...
 ```
위의 예시처럼 where절 조건이 추가될 경우 if문 안에 where절이 동적으로 생성 되므로 where 구문이 생성되지 않을 수 있습니다. 그래서 where 절을 기본적으로 작성하기 위해 무조건 통과하는 식을 적었습니다~ @gutenLEE

2023-08-25 05:17 UTC, ZhenxiKim commented on src/main/java/com/heeverse/common/SORTING.java
> +}
다른 이유는 없었습니다. 상수 네이밍과 혼동해서 사용했습니다.

2023-08-25 07:53 UTC, ZhenxiKim commented on src/main/resources/mapper/ConcertMapper.xml
> +    OFFSET ${page}
페이징 공통 모듈을 통해 1.2를 해결했습니다~
LIMIT, OFFSET을 통해 페이징 시 전체 데이터를 조회 후 OFFSET 숫자부터 ~LIMIT 개수를 잘라서 쿼리 결과를 뽑습니다. OFFSET 숫자가 클수록 처음부터 읽어야 할 데이터가 많아져서 성능에 좋지 않은 영향을 주지 않습니다.
다음 개선 포인트로 테스트해 보겠습니다.

2023-08-26 04:15 UTC, ZhenxiKim commented on src/test/java/com/heeverse/concert/controller/ConcertIntegrationTest.java
콘서트 조회 통합 테스트 작성 하여 머지하겠습니다.

2023-08-26 04:18 UTC, ZhenxiKim commented on src/main/java/com/heeverse/concert/domain/FutureDate.java
> +@ConstraintComposition(CompositionType.AND)
- @Documented
    - 메타 어노테이션으로 커스텀 어노테이션위에 선언하면 java doc에 포함되게한다.
- @Future
    - javax.validation.constraints 패키지에 있으며, virtual machine에 셋팅된 시간(셋팅된 timezone과 locale)보다 미래인지 검사하는 어노테이션
- @DateTimeFormat
    - pattern attiribute에 설정한 형식처럼 String type value를 날짜 타입의 형식으로 변환해준다.
    - 주로 request DTO에서 요청 파라미터 및 json 값을 변환하는데 사용한다.
- @Constraint
    - 커스텀 벨리데이션을 작성하여 사용할 수 있도록 선언한다.
- @ConstraintComposition
    - 구성 제약조건에 적용되는 속성으로 OR(제약조건이 or 조건으로 맞는 경우), ALL_FALSE(모두 조건이 맞지 않을 경우), AND(제약조건 모두 만족)가 있습니다.

@Constraint을 빼도 될거같지만 저 어노테이션이 없으면 커스텀 어노테이션이 작동하지 않았습니다. 이 내용은 추가정리해서 올리겠습니다.

2023-08-26 04:41 UTC, merged

2023-08-26 06:37 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/domain/FutureDate.java
> +@ConstraintComposition(CompositionType.AND)
`@Constraint`의 경우 validation의 구조상 선언해야하는것으로 알고있습니다~ 비어있는 값이라도 선언해주어야 밸리데이션 마킹 어노테이션이라는 선언이 되는 구조라 이걸 [왜 이렇게 해야하는지](https://stackoverflow.com/questions/4512826/empty-validatedby-in-constraint) 궁금해하시는분들도 꽤 있더라고요.

저 어노테이션도 `validatedBy `에 값을 주면 커스텀한 검증기를 지정해줄수도 있습니다. 이 때 어떻게 지정되는지도 한번 찾아보시면 Bean validation에 대한 이해가 더 높아질걸로 보이네요~