[#36] JWT token parsing 버그
f-lab-edu/heeverse-ticket pull request #39
Opened 2023-08-31 13:01 UTC by ZhenxiKim

## 개요
- 관련 Issue 번호 : #38 

## 작업사항

1. 특정 url일 경우 JWT token 검사가 제외되지 않는 현상
- `JwtAuthenticationFilter`에서 `shouldNotFilter`를 오버라이딩하여 특정 url 필터 타지 않도록 적용
- `requestMatchers(HttpMethod.POST, "/member").permitAll()`를 적용하면 해당 url에 모든 권한이 접근할 수 있는것이지 필터를 타지 않는것은 아니었다.

2. token parsing 시 secret key가 주입되지 않아 token 파싱 실패 현상
- parsing을 담당하는 `DefaultJwtParser`에 Key타입 필드가 주입되지않아 `InitializingBean`을 구현하여 빈이 초기화 된 이후 `afterPropertiesSet`를 통해 key 타입 필드를 초기화

3. JWT 토큰을 파싱하고 authentication을 얻는 메서드가 중복 코드가 있어 하나의 메서드로 리팩토링

2023-09-03 08:34 UTC, gutenLEE commented on src/main/java/com/heeverse/common/Constants.java
상수 개수가 더 틀어나면 용도별로 분리해는 리팩토링 작업을 해도 될 것 같습니다!

2023-09-03 08:34 UTC, gutenLEE commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +    public Authentication parsing(String headerAuth) {
`parsing()` 메서드에 여러가지 세부 구현 로직이 모여있는 느낌입니다!
1. header 파싱, `Claims` 생성 
2. 토큰 유효시간 검사 
3. 멤버 조회
4. authentication 생성

메서드로 분리하면 가독성이 높아질 것 같습니다!

2023-09-03 08:34 UTC, gutenLEE commented on src/main/java/com/heeverse/security/JsonAuthenticationFilter.java
>          response.setCharacterEncoding("UTF-8");
요것들도 기존에 있는 상수를 활용하면 좋을것같슴다!
```
    MediaType.APPLICATION_JSON_VALUE;
    StandardCharsets.UTF_8.name();
```

2023-09-03 10:49 UTC, f-lab-maverick requested changes
고생하셨습니다~ 리뷰 확인해주시고 수정 부탁드립니다.

2023-09-03 10:49 UTC, f-lab-maverick commented on .github/workflows/deploy.yml
이 부분은 다른 PR에서 진행하신듯 하여 넘어가도록 하겠습니다.

2023-09-03 10:49 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/Constants.java
> +    public static final String CLIAM_ID_KEY = "id";
CLAIM이라는 도메인에 한정된 key를 상수로 관리하는건 적절하지 않아 보입니다. 이 부분은 명시적으로 class로 시그니처를 확정할 수 있으므로, class로 만들어서 이를 ObjectMapper/BeanUtils등을 통해 map으로 변환하는게 어떤 데이터를 사용하는지 더 명시적 표현이 가능하지 않을까요?

2023-09-03 10:49 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/Constants.java
> +    public static final String CLIAM_ID_KEY = "id";
만약 다른 방식으로, 상수로 관리하고싶다면 ClameKeys 라는 별도의 상수 클래스를 만드는게 좋을 것으로 보이네요~

2023-09-03 10:49 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
특정 필터만 안타게하려면 해당 filter에 이런 로직 처리가 필요하긴 합니다.
이후에 비슷한 URL이 늘어난다면 이 List에 계속 추가하실 계획이신가요?

2023-09-03 10:49 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
>          }
이렇게 실제 exception 데이터를 남기지 않고 `JwtParsingException`으로만 남긴다면 추후에 이슈가 있을 때 로그 등으로 원인을 확인하기 어렵습니다. 간단하게라도 로그로 원본 Exception 정보를 남기는게 좋습니다.

이런식으로도 가능합니다.
```
log.error("~~~", e);
```

2023-09-03 10:49 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +    public Authentication parsing(String headerAuth) {
이 메서드는 너무나 큰 역할을 맡고있습니다~ 적절히 쪼개서 어떤 일을 하는지 작은 단위로 분리해주셔야 이후에 코드를 읽거나 수정할 때 명확하게 원하는 부분을 찾기 편해집니다.

2023-09-03 10:49 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +            throw new TokenExpiredException();
try 부터 catch까지 너무 큰 영역을 예외영역으로 잡고 있습니다.
try-catch 블록은 가능한 작은 영역으로 만들어야 예외 발생 가능 지점을 작은 단위로 관리할 수 있습니다.

2023-09-04 07:42 UTC, ZhenxiKim commented on src/main/java/com/heeverse/common/Constants.java
> +    public static final String CLIAM_ID_KEY = "id";
`public class ClaimData {
    private final String auth;
    private final String id;

    public ClaimData(String id, String auth) {
        this.id = id;
        this.auth = auth;
    }

    public Map<String, String> toMap() {
        ObjectMapper mapper = new ObjectMapper();
        return mapper.convertValue(this, Map.class);
    }

}
`

클래스로 생성하여 시그니처를 확정하는 방법을 위와같이 구현해봤습니다. 하지만 해당 시그니처의 해당하는 키값을 다른 메서드에서도 사용하고있어서 다른 쪽에서 사용하는 키값이 변경되며 시그니처 클래스도 변경해야하는 번거로움이 생겨 코드에는 claim 전용 상수로 적용했습니다.

2023-09-04 09:01 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
만약 운영 중 특정 필터가 추가된다면 컴파일해야 하므로 아래 두 가지 방법을 고민해 봤습니다.

1. application.yaml에 명시해서 가져오기
이 방법은 yaml파일이 env마다 생성되면 관리 포인트가 늘어나기도 하고, 외부에 노출될 수 있는 파일이므로 보안상 취약점이 될 거로 생각했습니다.

2. vault 서버에서 동적으로 가져오기
리팩토링한 부분은 vault 서버에서 동적으로 받아와서 url을 제외할 수 있도록 수정하였습니다.

2023-09-04 09:07 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
>          }
상위 exception으로 감싸서 예외를 처리하니 JWT token parsing 하는 [JwtParser 인터페이스](https://javadoc.io/doc/io.jsonwebtoken/jjwt/latest/io/jsonwebtoken/JwtParser.html) 구현체인 [DefaultJwtParser](https://javadoc.io/doc/io.jsonwebtoken/jjwt/0.2/io/jsonwebtoken/impl/DefaultJwtParser.html)에서 던지는 상세 exception을 확인할 수 없었습니다. 상위 exception으로 잡는 것을 제거하고 하위 상세 exception을 확인할 수 있도록 수정했습니다.

2023-09-04 09:12 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +            throw new TokenExpiredException();
try-catch가 잡고있는 범위를 메서드로 분리하고 각 메서드에서 예외를 던지면, 상위 메소드에서 exception에 대한 로그를 찍도록 수정했습니다.

2023-09-04 09:32 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> -        if (ObjectUtils.isEmpty(jwtToken)) {
DefaultPaser클래스에 토큰 만료시간 계산 로직이 있으므로 중복코드는 제거하였습니다.

2023-09-04 13:47 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
동적으로 변경한다는 것은 배포 없이 권한과 관련된 설정을 변경한다는 뜻인데요, 이렇게 동적으로 설정하신 이유가 있으신가요?

2023-09-04 13:58 UTC, f-lab-maverick requested changes
약간 더 수정하면 좋을 부분이 보여 리뷰 남깁니다.
확인 후 수정 부탁드려요~

2023-09-04 13:58 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JsonAuthenticationFilter.java
> +        response.setCharacterEncoding(StandardCharsets.UTF_8.name());
상수 사용 좋습니다 👍

2023-09-04 13:58 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        return new UsernamePasswordAuthenticationToken(member, null, authorities);
member가 null이면 어떻게되나요?
그리고 catch문에서 log만 찍고 Exception을 던지지 않는 이유가 있나요?

2023-09-05 06:04 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        return new UsernamePasswordAuthenticationToken(member, null, authorities);
try-catch에서 잡은 하위메서드의 exception이 상위 JwtParsingException로 잡혀서 제대로된 exception 메세지를 확인하기 어려워 exception을 던지지 않았었습니다. 
위의 방식은 exception을 잡게되어 제대로된 exception 처리가 되지않습니다.
exception도 처리하고 하위 메서드에서 발생한 exception은 상위 RuntimeException으로 전달하여 하위 exception도 함께 출력하게 변경했습니다.
`throw new JwtParsingException(e.getMessage(), e)`

2023-09-05 06:18 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        return new UsernamePasswordAuthenticationToken(member, null, authorities);
member가 null인경우 UsernamePasswordAuthenticationToken을 사용하는 다른 클래스에서 NullPointerException을 발생하게 됩니다. try-catch범위를 좁게 변경하고 각 하위메소드에서 해당 exception을 발생시키게 변경하였습니다.

2023-09-05 06:28 UTC, ZhenxiKim commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
고민한 선택지는 두 가지입니다.
application.yaml로 처리하면 local, dev, prod 세 가지 관리 포인트를 두어야 해서 관리 포인트가 많아지고, 휴먼 오류 발생확률이 올라갑니다.
vault 서버로 관리하면 하나의 관리 포인트가 되고, 코드상 접근권한에 대해 막긴 하지만 애플리케이션이 어떤 URL을 필터를 해제하는지 오픈하는 것보다 감추는 것이 보안상에도 안전할 것으로 고민하여 vault 서버를 선택했습니다.

2023-09-05 12:03 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
vault도 profile별로 다르게 관리할 수 있습니다.
별도로 동적이어야 하는 이유가 없다면 소스코드에서 관리하는 것이 가장 단순하게 처리할 수 있는 방식이긴 하겠네요

2023-09-05 12:04 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
>          }
catch된 Exception 인스턴스에 원본 예외 데이터가 남아있습니다. 이 원본 예외를 통해 로그를 남겨서 원본 예외메세지를 확인할 수 있습니다.
현재 작업해주신 내역처럼 wrapping하여 던지는것도 좋은 방식입니다~

2023-09-05 12:13 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +        return new UsernamePasswordAuthenticationToken(member, null, authorities);
네 null을 넘겨주는 순간 예외가 원래 터져야할곳이 아닌, 다른 메서드에서 터지게 되고, 이는 트러블슈팅시 예외 경로를 확인하기 어렵게 만드는 요인이 됩니다.

가능하면 변수에는 null을 할당하지 않고, 더 나아가 변수 선언과 동시에 값을 할당한 후 `final` 키워드로 상수화 하는게 좋습니다. 그러면 이런 장점들을 가질 수 있습니다~
- 한번 변수에 할당된 값이 다른 값으로 변하지 않음
- null safe
- 가독성 증가

2023-09-05 12:14 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 머지해주셔도 좋습니다.

2023-09-05 12:14 UTC, f-lab-maverick commented on src/main/java/com/heeverse/security/JwtTokenProvider.java
> +            claims = createJwtClaims(headerAuth);
catch문에서 무조건 throw된다면 아래쪽에 있는 return문을 try문 내부에 두어도 됩니다.

그러면 `Claims claims = null;`과 같이 변수에 null을 할당하지 않아도 되겠네요~

2023-09-06 04:36 UTC, merged