Feat/36/ticket order origin
f-lab-edu/heeverse-ticket pull request #44
Opened 2023-09-05 09:05 UTC by ZhenxiKim

## 개요
- 관련 Issue 번호 : #36 

## 작업사항
<img width="452" alt="image" src="https://github.com/f-lab-edu/heeverse-ticket/assets/45592236/90fdcd7b-23f6-4c55-84d3-c06228a28b70">

- select for update 쿼리를 이용하여 예매 기능 수행 시 lock을 설정했습니다.
- 기존 브랜치에서 작업하다가 pr 주제를 벗어난거같아 다시 브랜치를 땄는데, 기존 브랜치가 merge되지않아 기존 브랜치 기록까지 같이 딸려왔습니다.

2023-09-05 09:09 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> +        Long ticketOrderSeq = ticketOrderService.orderTicket(dto, (Member) authentication.getPrincipal());
CQS 패턴을 적용하여 수정로직과 조회로직을 분리하였습니다.

2023-09-11 15:10 UTC, f-lab-maverick reviewed
아직 Lock이 트랜잭션 내부에 존재하고, 티켓 발행쪽에서 동시성 제어 기법이 정리되지 않은 것으로 보여 이번 리뷰는 일부만 진행하였습니다.
이후 로직이 조금 정리되면 다시 요청 부탁드립니다~

2023-09-11 15:10 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/enums/BookingStatus.java
> +    private String status;
"예매 완료", "예매 취소"는 status라는 변수명과 매칭되지는 않는 것으로 보입니다.
`label`, `description` 등의 변수명은 어떠실까요?

2023-09-11 15:10 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/enums/BookingStatus.java
> +    private String status;
불변성이 보장된다는 것을 표현하기 위해 변수에 final을 붙여 상수화하는게 좋아보입니다~

2023-09-11 15:10 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +        return ticketMapper.updateTicketOrderSeq(new TicketRequestMapperDto(lockTicketSeqList, ticketOrderSeq));
`updateTicketOrderSeq`는 Service 계층에 설정하기 적절한 네이밍은 아니네요.  서비스계층의 메서드는 `issue(List<Long> lockTicketSeqList, Long ticketOrderSeq)` 와 같이 비즈니스 로직을 표현해주어야 합니다. 
비즈니스 로직을 표현할 수 있는 명칭과 함께 이에 맞는 여러 로직이 적용되어야 할 것으로 보입니다.

유효성검증이나 다른 로직은 추가될 여지가 없을까요?

2023-09-11 15:10 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> +        Long ticketOrderSeq = ticketOrderService.orderTicket(dto, (Member) authentication.getPrincipal());
트랜잭션 외부에서 이렇게 별도의 수정/조회를 한다면 동시성이슈는 없을까요?

2023-09-11 15:10 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
이 부분은 아직 확정되지 않은 동시성 제한 로직이 있어서 이번 리뷰에는 제외하도록 하겠습니다

2023-09-13 09:11 UTC, ZhenxiKim reviewed
위의 리뷰는 아직 반영을 하지 못했습니다. 이번 커밋 내용에 대한 리뷰와 함께 반영하겠습니다.

2023-09-13 09:11 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +public class TicketOrderFacade {
복잡한 예매하기 로직을 숨기고 요청하는 쪽에서는 `startTicketOrderJob`만 호출하는것을 신경쓰도록 faacade 패턴을 적용했습니다.

2023-09-13 09:11 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderServiceTest.java
> +@ActiveProfiles("dev")
named lock이 mysql에만 존재하여 dev로 환경셋팅하였습니다.

2023-09-13 09:11 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderServiceTest.java
> +        Logger log = (Logger) LoggerFactory.getLogger(TicketOrderServiceTest.class);
테스트 코드에는 `@Sl4j` 적용되지않아 log를 남기기위해 logger객체를 생성하였습니다.

2023-09-13 09:11 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderServiceTest.java
> +    private final int threadPoolSize = 32;
`ExecutorService e = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());`로 스레드 풀의 사이즈를 고민하다가 동시 요청 수 보다는 많아야 될거라고 임의의수를 지정해봤습니다. 성능 테스트를 하면서 적절한 스레드 풀 사이즈를 찾아가보려합니다.

2023-09-14 02:38 UTC, f-lab-maverick requested changes
첫 동시성 관련 테스트 작성 고생하셨습니다~ 
리뷰 확인 후 수정해주세요~

2023-09-14 02:38 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/domain/dto/TicketOrderResponseDto.java
> +    private String bookingStatus;
여기에 있는 final은 왜 제거하셨나요?

2023-09-14 02:38 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +    private static final int timeoutSeconds = 30;
시간단위는 `Duration`을 사용해주시는게 어떨까요?
`java.time`패키지에는 이런 시간을 다룰 수 있는 여러가지 클래스가 있습니다. `Duration`으로 관리하면 불변성도 얻을 수 있고, 시간이 시/분/초 어떤단위인지 변수명으로 추측하지 않아도 됩니다.

2023-09-14 02:38 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +}
이렇게 고정된 이름의 named lock을 사용하면 특정 티켓이 아닌 모든 티켓은 한번에 하나의 티켓 발급만 처리할 수 있게 됩니다.
사용자 100만명이 요청을 보냈을 때 Lock으로 인해 순차처리를 해야 한다면 Lock 획득에 타임아웃이 걸린 대상자는 티켓 발급에 실패할 것입니다. (티켓이 남아있다고 해도)

락의 범위를 축소해야 하며, 어떻게 더 좋은 성능과 더 많은 트래픽을 처리할 수 있는지 고민해보시겠어요?

2023-09-14 06:21 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> +        Long ticketOrderSeq = ticketOrderService.orderTicket(dto, (Member) authentication.getPrincipal());
동시성 이슈가 발생할 수 있네요. 만약 update 후 하나의 트랜잭션에서 동작하지 않는다면 다른 update 트랜잭션에서 수정한 값이 조회될 수 있습니다. command, query는 분리하되, 하나의 트랜잭션으로 동작하도록 수정하였습니다.

2023-09-14 06:23 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/domain/enums/BookingStatus.java
> +    private String status;
변수명만 무엇을 뜻하는지 애매할 수 있었네요 변수명을 상세하게 변경하고 불변화 하였습니다.

2023-09-14 07:18 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +        return ticketMapper.updateTicketOrderSeq(new TicketRequestMapperDto(lockTicketSeqList, ticketOrderSeq));
부가로직(유효성 검사)를 추가하고 서비스 계층에 맞는 이름으로 변경했습니다..

2023-09-14 07:22 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/domain/dto/TicketOrderResponseDto.java
> +    private String bookingStatus;
의식의 흐름이었던거같습니다.. 추가했습니다..

2023-09-15 04:45 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +    private static final int timeoutSeconds = 30;
불변성, 가독성을 위해Duration클래스를 적용했습니다. 날짜 기간이면 날짜 기간을 지정할 경우 Period 클래스도 함께 학습하게 되었습니다.

2023-09-16 08:38 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +    private static final int timeoutSeconds = 30;
row lock으로 변경하면서 lock에 설정한 timeout 파라미터가 불필요해져서 제거하였습니다.

2023-09-16 08:46 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +}
문제점) name lock을 동시에 동일한 lock의 이름으로 요청을 하게되면, 다른 티켓 번호를 요청해도 동시 처리가 불가해 졌습니다.

try1) request body로 lock의 이름을 만들어서 named lock 설정
이 방식은 요청하는 여러 트랜잭션마다 다른 이름의 lock을 획득할 수 있어 위의 문제점을 해결할 수 있습니다. 하지만 아직 lock의 범위가 크다는 문제를 가집니다.

try2) InnoDB row lock
lock의 범위를 row level로 줄이는 선택으로 row lock으로 리팩토링 했습니다.

2023-09-16 08:53 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +    protected Long createTicketOrder(TicketOrderRequestDto dto, Long memberSeq) throws Exception {
`startTicketOrderJob`메서드가 내부적으로 호출하고, 테스트 코드에서 사용하기 위해 protected로 선언했습니다.

2023-09-16 11:14 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
트랜잭션 롤백 문제 원인은 무엇이였나요??

2023-09-16 12:59 UTC, f-lab-maverick requested changes
조금만 더 수정하면 좋은 코드가 나올 것 같네요.
한번 더 수정해보시겠어요?

2023-09-16 12:59 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/domain/enums/BookingStatus.java
> +    CANCEL("예매 취소");
`예매 전` 과 같은 상태는 없는건가요?

2023-09-16 12:59 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +    }
이 메서드는 외부에서 호출 가능하며, DB를 통하는 메서드인데 별도 트랜잭션이 없습니다. 의도하신건가요?

2023-09-16 12:59 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/LockMapper.java
> +}
이 `LockMapper`는 `Ticket`에 종속적인 것으로 보이네요. 이 메서드를 사용하는 사람들은 이 Lock이 어디에 걸리는 것인지 직관적으로 알기 어렵지 않을까요?

2023-09-16 12:59 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +        return ticketOrderService.orderTicket(dto, memberSeq);
Lock을 획득하지 못해 실패하였을 때 적절한 Exception과 관련된 메세지를 리턴해주어야 할 것으로 보이네요~ 이대로 예외가 발생한다면 예외에는 timeout관련된 에러가 그대로 떨어질텐데 이는 API 사용하는쪽에서 명시적이지 않은 에러일 것이지 않을까요?

2023-09-16 12:59 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
실패 테스트도 추가되면 좋겠네요~
동시에 같은 좌석에 대한 Lock을 요청하면 순서에 따라 실패한다 와 같은 테스트요.

2023-09-17 06:29 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket/domain/enums/BookingStatus.java
> +    CANCEL("예매 취소");
예매하기 트랜잭션에서 예매하기 기능 성공 시 ticket_order 테이블에 row가 생성됩니다. insert 시 생성될 상태여서 예매 전 상태는 없어도 된다고 생각했습니다. 예매 취소 상태의 경우 추후 개발될 예매 취소 기능을 고려해서 생성했었습니다.

2023-09-19 05:30 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +        return ticketOrderService.orderTicket(dto, memberSeq);
lock획득 실패 시 lock 획득 실패에 대한 exception을 전달할 수 있도록 getLock메서드에 추가하였습니다.

2023-09-21 05:15 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +    public List<TicketOrderResponseDto> startTicketOrderJob(TicketOrderRequestDto dto, Long memberSeq) throws Exception{
구체적인 예외가 아닌 `throws Exception`  인 이유가 궁금합니다!

2023-09-22 03:45 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
>          Logger log = (Logger) LoggerFactory.getLogger(TicketOrderFacadeTest.class);
logger 는 인스턴스나 클래스 변수로 선언해 모든 테스트에서 사용하는게 좋을듯합니다.

2023-09-22 03:45 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    @BeforeEach
`@BeforeEach` 를 선언하게 되면 다른 개발자가 추가하는 테스트에도 이 로직이 실행되는 문제가 있네요! 
특정 테스트를 위한 사전 준비라면 `@BeforeEach` 보다는 테스트 재사용이나 `@TestFactory`를 활용하면 좋을듯합니다.

2023-09-22 10:43 UTC, f-lab-maverick requested changes
비즈니스로직에 대한 코드는 꽤 괜찮아졌네요~
테스트코드만 조금 추가/수정 해봅시다!

2023-09-22 10:43 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    }
이 로직 자체가 테스트의 로직으로 보이네요.
만약 로직이 변경되어 테스트의 초기화가 실패한다면 관련 테스트가 모두 실패할 것으로 보입니다.
테스트는 상태를 가지면 안됩니다. 필요한 모든 초기화 로직은 각 개별 테스트로직 내부에 만들어주세요.

2023-09-22 10:43 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    }
테스트케이스가 공통된 초기화 로직을 사용하다보니 케이스자체가 부족해보입니다.

`예매되지 않은 티켓은 주문에 성공한다`, `이미 예매된 티켓은 예매할 수 없다`, `동시에 같은 좌석을 예매 시도할 경우 한개의 요청만 성공한다`, `복수의 좌석을 예매 시도할 때 중복 예매 요청이 있을 경우 ...` 등 다양한 테스트케이스를 추가해주세요.

2023-09-23 13:15 UTC, f-lab-maverick reviewed
관련 내용은 슬랙에 리뷰로 남겨두었습니다.
상태를 제거한 부분 괜찮네요~ 테스트케이스 좀 더 보강해주시고, 너무 많은 역할을 하는 setUp 메서드도 리팩토링이 필요합니다.

2023-09-23 13:15 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/domain/entity/TicketOrder.java
> +
주석처리 되어있는 부분은 삭제해주세요~ 사용하지 않는 코드는 주석처리로 해두면 관리가 안되는 경우가 많습니다. 커밋 로그에 관련 코드가 남으므로 사용하지 않는다면 삭제해주시는게 좋습니다.

2023-09-23 13:15 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
> +                throw new TicketNotNormallyUpdatedException("이미 예매 성공한 티켓으로 인해 티켓 테이블에 order_seq update 실패");
`updateCount == 0`!
매직넘버가 있네요. 0과 같은 특수한 숫자라도 매직넘버 사용은 지양해주세요~

2023-09-25 07:38 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +    public List<TicketOrderResponseDto> startTicketOrderJob(TicketOrderRequestDto dto, Long memberSeq) throws Exception{
try-catch문이 존재하여 불필요한 throws exception 구문 제거했습니다.

2023-09-26 10:25 UTC, f-lab-maverick requested changes

2023-09-26 10:25 UTC, f-lab-maverick commented on src/main/resources/mapper/TicketOrderMapper.xml
> +    </delete>
이 메서드가 프로덕션에서 실행될 수 있다면 정말 위험한 쿼리이지 않을까요?
특히, TRUNCATE같은 경우 모든 데이터를 초기화하기 때문에 운영 DB의 계정에서는 권한도 빼두어야 하고, 이런 쿼리가 날아갈 가능성을 만들면 안됩니다. 테스트코드에서만 작동하는 별도의 초기화 매퍼를 만드는건 어떨까요?

2023-09-26 10:25 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    }
이 테스트를 개발 DB에서 한다고 쳤을 때, 개발DB에 이미 예매가 진행중인 건이 있다면 이 테스트는 실패할 것으로 보입니다. 모든 티켓에 대한 예매를 가져오는 것이 아닌, 테스트에서 만든 티켓에 대한 예매 건수를 가져와서 비교하는 형식으로 만들어야 테스트의 데이터와 개발환경의 데이터가 서로 격리되어 영향을 주지 않습니다~

2023-09-26 10:25 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    @Rollback
이 `@Rollback` 어노테이션과 테스트 최상단의 `@Transactional`이 하는 역할이 어떤 차이가 있을까요?

2023-09-26 10:25 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +        List<TicketOrder> ticketOrderList = ticketOrderMapper.selectAllTicketOrderList();
여기서도 모든 티켓 예매를 조회해와서 테스트를 하고 있네요. 정확히 테스트에 사용하는 데이터만을 조회할 수 있도록 변경해주세요~

2023-09-26 10:25 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    }
테이블에 `truncate`를 날리는 로직은 rollback이 아닌 clear가 맞는 네이밍으로 보입니다. 이 테스트가 개발서버나 기타 다른 서버에서 동작한다면 개발 데이터까지 모두 날아가지 않을까요?

2023-09-26 10:25 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    }
파라미터도 없고, 리턴값도 없는 메서드네요. 티켓을 예매 시도하였지만 리턴값이 아무것도 없군요. 이런 경우 어떤 티켓에 대한 예매를 시도한 것인지, 예매의 결과물이 어떤 것인지는 DB에서 모두 조회해오거나 하드코딩된 필터 값으로 조회 해와야 하는 경우가 생길 것으로 보입니다.

자연스러운 흐름으로 가려면 DB에 데이터를 insert하고, insert한 데이터의 key를 받아와 리턴해주어 이 key로 다른 테스트시 데이터 연결고리를 만들어 주는 것입니다.

테스트시 특정 데이터의 key (seq)를 어플리케이션에 고정해두는 방식은 테스트 가독성 측면에서도, 관리 측면에서도, 확장성 측면에서도 좋지 않습니다~

```
private TicketOrder orderTicket(Ticket ticket) throws Exception {
        TicketOrderRequestDto ticketOrderRequestDto = createTicketOrderRequestDto(ticket.getSeq());
        ticketOrderFacade.startTicketOrderJob(ticketOrderRequestDto, MemberTestHelper.getMemberSeq());
        // 티켓주문 조회
        return ticketOrder;
    }
```

이후 이 메서드를 호출하는 곳에서는 전달받은 TicketOrder 객체를 통해 데이터를 만들거나 업데이트할 수 있겠죠?

2023-09-26 10:25 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    }
이렇게 만들어두면 이후 다른 테스트 작성시에도 재사용이 용이합니다~

2023-09-30 16:01 UTC, ZhenxiKim reviewed
테스트 수행 시 의존성을 줄이고, 메서드별 역할을 최소화하도록 리팩토링했습니다.

2023-09-30 16:01 UTC, ZhenxiKim commented on src/test/java/com/heeverse/common/ServiceTest.java
> +public abstract class ServiceTest {
통합테스트에 공통으로 사용할 설정 및 주입할 클래스를 설정하여 추상클래스로 설정했습니다.

2023-09-30 16:01 UTC, ZhenxiKim commented on src/test/java/com/heeverse/common/factory/MemberFactory.java
> +public class MemberFactory {
테스트를 위해 given에 해당하는 로직을 처리해줄 클래스입니다. 클래스명은 xxxFacotry로 설정하였습니다.

2023-09-30 16:01 UTC, ZhenxiKim commented on src/test/java/com/heeverse/concert/domain/entity/ConcertHelper.java
> +public class ConcertHelper {
테스트를 위해 given에 해당하는 로직을 수행할때 mock데이터를 생성하는 클래스입니다. 클래스명은 xxxHelper로 설정하였습니다.

2023-10-01 04:13 UTC, gutenLEE commented on src/test/java/com/heeverse/common/ServiceTest.java
> +public abstract class ServiceTest {
현재 `TicketorderFacadeTest` 에서만 상속하고 있어 티켓 예매와 관련된 통합테스트에서만 사용하는지 모든 통합클래스에서 사용하는지 헷갈립니다!
모든 통합클래스에서 사용하는 용도라면 의존 관계가 없는 도메인의 `Factory` 도 접근할 수 있는 문제가 발생할 것 같슴다.

2023-10-01 14:49 UTC, ZhenxiKim commented on src/test/java/com/heeverse/common/ServiceTest.java
> +public abstract class ServiceTest {
모든 통합 클래스에 적용하기 위해 공통으로 사용될 memberFactory만 남겼습니다.

2023-10-02 02:05 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 머지해주셔도 좋습니다.

2023-10-02 02:05 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/domain/mapper/ConcertMapper.java
> +    List<RegisteredConcertMapperDto> selectRegisteredConcertList(@Param("concertSeqList") List<Long> concertSeqList);
`selectLatestConcertSeq();`는 `Phantom Read`가 발생할 수 있는 환경에서는 사용하면 안됩니다. 그 이유는 왜일까요?

2023-10-02 02:05 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/service/ConcertService.java
>      }
`createTicket`메서드는 `ConcertRequestDto.getTicketGradeDtoList`만 사용하고 이외 다른 상태는 사용하고있지 않습니다.
그렇다면 이 메서드는 `ticketGradeDtoList`, `concertSeq`만 파라미터로 받아도 되지 않을까요?

2023-10-02 02:05 UTC, f-lab-maverick commented on src/main/resources/mapper/TicketOrderMapper.xml
> +    </delete>
이 쿼리는 아직 삭제가 안된것같습니다~

2023-10-02 02:05 UTC, f-lab-maverick commented on src/test/java/com/heeverse/common/ServiceTest.java
> +public abstract class ServiceTest {
추상클래스로 Bean을 만들게 되면 생성자주입을 사용하기 어렵습니다. 여러가지 제약사항이 생기니 참고해주세요~

2023-10-02 02:05 UTC, f-lab-maverick commented on src/test/java/com/heeverse/common/ServiceTest.java
> +public abstract class ServiceTest {
테스트를 위한 Service Bean이라면 `IntegrationTestService`와 같은 네이밍이 적절해보입니다.

2023-10-02 12:29 UTC, ZhenxiKim commented on src/main/java/com/heeverse/concert/service/ConcertService.java
>      }
dot에서 두 개 필드를 꺼내서 dto를 파라미터로 넘겼습니다. 두 개 정도는 메서드 파라미터로 따로 넘기는 것이 좋을까요?

2023-10-02 13:02 UTC, ZhenxiKim commented on src/main/java/com/heeverse/concert/domain/mapper/ConcertMapper.java
> +    List<RegisteredConcertMapperDto> selectRegisteredConcertList(@Param("concertSeqList") List<Long> concertSeqList);
Tx1에서 `Select for update`쿼리로 rowlock을 잡았지만 다른 Tx2에서 insert하는 경우 언두로그 레코드에 락을 잠글 수 없어 insert되는 테이블에 row가 보였다 보이지 않는 Phantom Read가 발생합니다. 로직 상 concert테이블에 lock을 잡는 경우는 없지만, select for update를 하는경우 주의해야겠습니다.

2023-10-02 13:56 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    @Rollback
`@Rollback`은 클래스 레벨 또는 메서드레벨에 선언하여 테스트 코드 수행 후 무조건 rollback 처리되도록 합니다. 또한 상속 관계, nested class에도 적용됩니다.
`@Transactional`은 상속 및 nested class에는 적용되지 않아 재선언해야 합니다. runtimeException이나 error가 발생했을 경우 rollback을 처리하게 합니다.

2023-10-02 13:57 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    }
운영 환경에서 위험한 쿼리이므로 테스트 시 사용하지 않도록 제거했습니다.

2023-10-02 13:57 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +    }
테스트에 필요한 데이터를 만드는 메서드는 파라미터를 받아 필요한 값만 처리되도록 수정했습니다.

2023-10-03 07:28 UTC, f-lab-maverick commented on src/main/java/com/heeverse/concert/service/ConcertService.java
>      }
dto에 있는 여러 파라미터를 사용하고 있어서 넘겨도 무방해보이기는하네요~
다만 꼭 필요하지 않은 데이터까지 함께 dto로 묶어 넘기게 된다면 추후에 이 메서드를 사용하려면 꼭 필요한 데이터 뿐만이 아닌, DTO를 만들어 넘겨야 해서 사용하기 어려워질 수 있습니다. 이 부분만 참고해주시면 될 것 같습니다~

2023-10-03 08:44 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
> +        executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
이런게 있었군요

2023-10-03 08:52 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
> +    }
테스트 설명에 `동일한 티켓 예매 시도`면 실패라고 생각이 드는데 성공 테스트인 이유가 궁금합니다!

2023-10-03 11:44 UTC, f-lab-maverick approved these changes
확인하였습니다~

2023-10-03 11:44 UTC, f-lab-maverick commented on src/test/resources/test-data/create-test-data.sql
> +insert into venue (venue_name, address, seat_cnt, create_datetime)
이런식으로 SQL을 작성할 때 트랜잭션을 시작한다는 의미인 `BEGIN`은 필요하지 않을까요?

2023-10-04 08:28 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
> +@Transactional(isolation = Isolation.READ_COMMITTED)
동시성 테스트 결괏값을 가져와 테스트 검증을 위해 트랜잭션 격리 수준을 `READ_COMMITED`로 수정했습니다.
현재 테스트 코드는 단일 스레드로 동작하고, 멀티스레드로 동작하는 예매의 경우 다른 트랜잭션에서 수행됩니다. MYSQL의 기본 격리 수준인 `REPEATABLE_READ`의 경우 현재 테스트가 진행되는 트랜잭션에서는 테스트 중간에 수행되는 예매 기능의 결괏값은 조회되지 않습니다. 그리하여 동시성 테스트를 검증하기 위해 격리 수준을 `READ_COMMITED`로 수정했습니다.

2023-10-04 08:30 UTC, ZhenxiKim commented on src/test/resources/test-data/create-test-data.sql
> +insert into venue (venue_name, address, seat_cnt, create_datetime)
트랜잭션 시작을 명시적으로 선언하기 위해 BEGIN 명령어를 추가했습니다.

2023-10-04 08:31 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
> +    }
동시에 티켓을 예매하는 상황에서 성공,실패 경우가 나오는데 위의 경우 동시요청 수 만큼 ticketOrder테이블에 row가 생성되므로 성공테스트로 작성하였습니다.

2023-10-04 13:25 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
> +@Transactional(isolation = Isolation.READ_COMMITTED)
여러 테스트가 동시에 실행된다면 문제가 생기지 않을까요? 정확히 어떤 트랜잭션의 격리수준이 변경된건가요? 격리수준을 낮춘다는 것은 꽤 위험한 작업이라, 정확한 의도가 있어야 할 것으로 보입니다.

2023-10-04 13:50 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
> +@Transactional(isolation = Isolation.READ_COMMITTED)
```java
    void successBookingStatusTest() throws InterruptedException {
        List<Long> ticketList = createTicket(createConcert());
        Long memberSeq = memberFactory.createMember(MemberTestHelper.getMockMember());
        concurrencyRequest(ticketList, memberSeq);
        List<TicketOrder> ticketOrderList = ticketOrderMapper.selectTicketOrderListByMemberSeq(memberSeq);
        Assertions.assertEquals(threadCount, ticketOrderList.size());
    }
```
동시 예매 요청 후 요청한 결과값을 가져와 검증하려하는데, 값을 제대로 가져오지못해 아래와 같은 부분을 의심하고 적용했습니다.
successBookingStatusTest()가 수행되는 트랜잭션에서는 동시 예매 요청 결과가 수행되는 다른 트랜잭션에서 수행되니, 결과값(selectTicketOrderListByMemberSeq)을 읽어오기 위해 동시성 테스트 클래스만 READ_COMMITED를 적용했습니다.

위의 답변을 다시 고려하니 특정 테스트 결과값만 가져오기 위해 트랜잭션 격리 수준을 내리는것은 위험한것 같습니다. 다른 여러 트랜잭션에서 수행되는 값을 검증하기 위해서는 어떤식으로 접근해야할지 모르겠습니다.

2023-10-04 14:33 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
> +@Transactional(isolation = Isolation.READ_COMMITTED)
커밋된 데이터를 조회할 수 있게만 해도 어느정도의 안정성은 생기겠네요. "값을 제대로 가져오지못해 아래와 같은 부분을 의심하고 적용"했다는 부분은 이슈의 원인을 좀 더 세밀하게 분석해볼 필요성이 있습니다. 단순히 데이터 조회가 안되었는데 격리수준을 낮추니 된다더라~ 가 아닌, 원인분석을 통해 가장 적절한 해결책을 찾아보는게 좋겠습니다.

테스트 초기화를 진행하는 트랜잭션과 실제 테스트를 수행하는 트랜잭션이 달라서 발생하는 이슈라면 COMMIT이 호출된 시점 이후에 실행된 트랜잭션은 해당 데이터를 조회할 수 있어야하는게 맞습니다. 만약 트랜잭션의 시작 지점이 문제가 된다면 격리수준을 변경하는게 나쁘지 않은 선택이 될 수 있겠네요.

2023-10-06 08:45 UTC, merged