:bricks: Dockerfile 추가
f-lab-edu/heeverse-ticket pull request #46
Opened 2023-09-11 09:22 UTC by gutenLEE

## 개요
- 관련 Issue 번호 :  #31 

## 작업사항
- CD 플로우 변경
  SSH 로 소스코드 pull 방식에서 도커 허브로 변경했습니다.
- Dockerfile 추가

## 변경로직
<img src="https://github.com/f-lab-edu/heeverse-ticket/assets/61870748/7f9325e8-a522-440f-8f45-734c929ee20d" width="600px">

2023-09-11 14:48 UTC, f-lab-maverick requested changes
고생하셨습니다.
코드리뷰 확인해주시고 수정 후 다시 리뷰요청 부탁드립니다~

2023-09-11 14:48 UTC, f-lab-maverick commented on .github/workflows/deploy.yml
> +                        -p 8081:8081 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }} \
왜 8081번 포트인가요? 어플리케이션 기본 포트가 8081로 설정되어있어도 실제 서버로 노출할 때에는 80번 / 8080번 포트로 바인딩이 가능합니다~

2023-09-11 14:48 UTC, f-lab-maverick commented on Dockerfile
> +USER root
Docker Container에도 보안취약점이 있습니다. 컨테이너 특유의 성질을 이용해 컨테이너 권한으로 실제 호스트의 권한까지 얻을 수 있는 공격점이 있어요. 만약 권한이 탈취당한다면 정말 큰일이 발생할 수 있습니다.

그렇기 때문에 도커에서 사용하는 user(다른 스크립트에서도 마찬가지입니다)로는 "절대" root를 사용하면 안됩니다. 다른 user를 생성하여 그 user로 실행하도록 해보시겠어요?

2023-09-12 14:32 UTC, gutenLEE commented on script/deploy.sh
> -        $DEPLOY_JAR >> $LOG_PATH/deploy.log 2>$LOG_PATH/deploy_err.log &
@f-lab-maverick 
요 `>>`  append 하는 명령어가 도커 컨테이너에서는 안먹히는데 원인이 아직 뭔지 파악 못했습니다.
이 `>>` 포함 이하를 지워야 jar 실행이 됩니다.

log 파일의 권한 문제인가 싶었는데 위 echo 명령어 쓰기작업은 잘 됩니다.

2023-09-14 00:53 UTC, f-lab-maverick commented on script/deploy.sh
> -        $DEPLOY_JAR >> $LOG_PATH/deploy.log 2>$LOG_PATH/deploy_err.log &
우선 도커 컨테이너 내부에 로그를 남기는 행위는 컨테이너 재시작시 모든 파일이 유실되기 때문에 파일로 남기는건 많이 추천드리는 방식은 아닙니다. 컨테이너가 여러개이기 때문에 보통 로그수집기를 연동하여 사용하기는 합니다~

그리고 logback으로 로그 파일 경로 설정을 해주시는게 좋아보이네요. 현재 방식은 sysout, syserr를 남기는 형식이니 logback에 file appender를 통해 설정해보시겠어요?

2023-09-14 00:54 UTC, f-lab-maverick commented on script/deploy.sh
> -        $DEPLOY_JAR >> $LOG_PATH/deploy.log 2>$LOG_PATH/deploy_err.log &
컨테이너가 실행 후 바로 종료상태가 되는지, 오류를 생성하는지 등 상황에 따라 트러블슈팅 방법이 달라질거 같네요~ 별도 로그 없이 종료되나요?

2023-09-14 03:59 UTC, gutenLEE commented on script/deploy.sh
> -        $DEPLOY_JAR >> $LOG_PATH/deploy.log 2>$LOG_PATH/deploy_err.log &
네, 현재는 별도 로그 없이 종료되는데 고민해보겠습니다

2023-09-14 04:47 UTC, gutenLEE commented on script/deploy.sh
> -        $DEPLOY_JAR >> $LOG_PATH/deploy.log 2>$LOG_PATH/deploy_err.log &
추가로 로그 파일 경로를 볼륨으로 호스트 디렉토리에 마운트할 계획이였습니다.
logback 에러 로그 파일 경로 설정뒤 볼륨과 연결해보겠습니다

2023-09-14 10:32 UTC, gutenLEE commented on src/main/resources/logback-spring.xml
정희님 작업중인 브랜치에서 cherry pick 으로 
로그백 관련 코드 가져왔습니다.

2023-09-14 10:32 UTC, gutenLEE commented on src/main/resources/logback-spring.xml
> +        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
로그 파일에 무한히 쌓이지 않게 `RollingFileAppender` 적용했습니다.

2023-09-15 06:54 UTC, gutenLEE commented on .github/workflows/deploy.yml
> +            set -e
`set -e` 옵션을 사용하면 스크립트 실행 중 에러 발생하면 종료시킵니다. 
스크립트로 도커 이미지 pull & run 실패시 github-action 워크플로우도 실패하도록 변경했습니다.

2023-09-15 06:54 UTC, gutenLEE commented on Dockerfile
> +
변경 전에는 `mkdir` 작업 디렉토리 생성하고 `cd` 로 디렉토리 이동했었는데,
dockerfile 의 `WORKDIR` 명령어로 작업 경로 설정 가능해 적용했습니다.

2023-09-15 06:56 UTC, gutenLEE commented on .github/workflows/deploy.yml
> +                        -v home/ubuntu/workspace/scouter:/scouter
호스트 디렉토리와 컨테이너 내부 디렉토리로 연결 설정입니다.

2023-09-15 07:06 UTC, ZhenxiKim reviewed
리뷰완료했습니다.

2023-09-15 07:06 UTC, ZhenxiKim commented on src/main/resources/logback-spring.xml
> +        <logger name="com.heeverse" level="ERROR"  />
이 설정이 log를 출력할 레벨을 설정하는것으로 알고있는데 DEBUG레벨로 설정해서 ERROR레벨은 따로 설정하지 않아도 출력되지 않나요?

2023-09-15 07:06 UTC, ZhenxiKim commented on src/main/resources/logback-spring.xml
> +    <property name="LOG_DIR" value="/tmp/workspace/heeverse/logs" />
환경마다 분리되긴 하지만 로그폴더명에 어떤 환경이지 명시하면 좋을거 같습니다.

2023-09-15 07:06 UTC, ZhenxiKim commented on src/main/resources/logback-spring.xml
> +                <!-- 10주치 로그 파일 보관. 단, 1GB 까지 가능 -->
10주가 넘어간 데이터에 대한 백업은 어떻게 고려하셨는지 궁금합니다~

2023-09-15 07:12 UTC, gutenLEE commented on src/main/resources/logback-spring.xml
> +                <!-- 10주치 로그 파일 보관. 단, 1GB 까지 가능 -->
예전에 로그 파일 용량이 꽉차 배포에 실패한 경험이 있어 적용했습니다. 
아직 개발 단계라 로그 영구 저장까지는 필요 없을듯하여 적용했습니다.
영구 저장 니즈가 생기면 로그 수집기 추가하면 좋을듯합니다.

2023-09-15 07:14 UTC, gutenLEE commented on src/main/resources/logback-spring.xml
> +    <property name="LOG_DIR" value="/tmp/workspace/heeverse/logs" />
로그 파일명에 붙여도 좋을듯합니다

2023-09-15 07:27 UTC, gutenLEE commented on src/main/resources/logback-spring.xml
> +        <logger name="com.heeverse" level="ERROR"  />
아하 설정 레벨에서 상위 레벨까지 같이 찍히는군요

2023-09-15 07:47 UTC, gutenLEE commented on src/main/resources/logback-spring.xml
> +    <property name="LOG_DIR" value="/tmp/workspace/heeverse/logs" />
스프링 부트 환경 변수를 가져올 수 있네요 .. 
폴더명, 파일명 둘다 해봤는데 폴더에 붙이는게 더 깔끔하네요.
변경하겠습니다.

2023-09-15 08:02 UTC, ZhenxiKim commented on src/main/resources/logback-spring.xml
> +                <!-- 10주치 로그 파일 보관. 단, 1GB 까지 가능 -->
제가 말한 의미는 영구적 백업이라기보다는 로그 추적용으로 도커 서버이외의 곳에서 보관하면서 모니터링이나 로그 추적용으로 쓸 수 도 있을거같아 질문했습니다~ 듣기로는 로그도 따로 저장했다가 일정기간 이후에 지우는것 같더라고요

2023-09-15 08:06 UTC, gutenLEE commented on src/main/resources/logback-spring.xml
> +                <!-- 10주치 로그 파일 보관. 단, 1GB 까지 가능 -->
아하..중요한 로그는 보관 주기나 백업 방법도 고민해봐야겠습니다 !

2023-09-15 10:25 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 확인 완료했습니다.

2023-09-15 10:25 UTC, f-lab-maverick commented on src/main/resources/logback-spring.xml
> +                <!-- 10주치 로그 파일 보관. 단, 1GB 까지 가능 -->
로그가 용량이 상당히 크다보니 정말 필요한 로그가 아니라면 Application log는 영구저장까지는 하지 않기는 합니다. 개인정보 접근/수정 내역, 권한 부여 내역 등 중요한 로그는 RDB / 별도 Log appender로 분리하여 처리하기도 하니 영구저장을 고려하지는 않아도 될 것으로 보이네요.

2023-09-15 11:25 UTC, merged