feat : 잔여 티켓 집계 기능 추가
f-lab-edu/heeverse-ticket pull request #53
Opened 2023-09-21 07:48 UTC by gutenLEE

## 개요
- 관련 Issue 번호 : 
  - #17 
  - #44 

## 작업사항
- 티켓팅 중 잔여 티켓 집계 조회

2023-09-21 07:50 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +        @TestFactory
테스트 헬퍼 클래스를 따로 뒀었는데 이 어노테이션을 활용하면 좋을것같습니다. 

[참고 문서 : Dynamic Tests / TestFactory ](https://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests)

2023-09-21 10:33 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +        @TestFactory
참고하겠습니다~

2023-09-21 11:03 UTC, ZhenxiKim reviewed
리뷰 완료했습니다.

2023-09-21 11:03 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/domain/dto/TicketRemainsResponseDto.java
> +    public final long concertSeq;
wrapper타입으로 선언하여 null에 대한 검사 및 값의 유효성 검사를 하면 좋을것 같습니다. primitive type의 경우 기본값이 셋팅되어 예상하지 못한값이 들어갈 수 있습니다.

2023-09-21 11:03 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +            return Collections.emptyList();
catch구문에서 어떤 에러가 발생하는지 로그를 추가하는것이 에러 추적 시 도움이 될것같습니다. 또한 빈 객체를 리턴하는 것보다 잔여 좌석이 없음을 메세지로 전달하는것이 사용자 입장에서 더 이해하기 쉬울 것 같습니다.

2023-09-21 11:03 UTC, ZhenxiKim commented on src/main/resources/mapper/TicketMapper.xml
> +           OR cancelled_flag = 1
cancelled_flag 컬럼 타입을 boolean으로 변경하는것이 좋을것 같습니다.만약 다른 범위의 숫자를 임의로 셋팅하면 어플리케이션에서 어떤 상태를 뜻하는지 알 수 없으며, 취소 여부를 나타낼때는 boolean이 적절해 보입니다.

2023-09-21 11:03 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +        @DisplayName("티켓 예매중 티켓 집계 조회시 데드락이 아니라면 소요 시간은 1000 밀리 세컨드 이하")
만약 데드락 상황이 아니고 다른 디비 부하에 의해 쿼리 성능이 느릴 수도 있는 상황이 발생할 수도 있으니 데드락 상황보다는 정상 조회 시도 괜찮을 것 같습니다.

2023-09-21 11:03 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +                        lockTicketRowRecord();
두 개의 스레드에서 왜 각각 100번씩 작업을 수행하는지 궁금합니다.

2023-09-21 11:03 UTC, ZhenxiKim commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +                System.out.println("티켓 집계 조회 : " +   TimeUnit.MILLISECONDS.convert((end - start), TimeUnit.NANOSECONDS) + " millis");
테스트 코드에서는 `@Sl4j`가 지원되지 않아 Logger객체를 선언하여 로그를 남길 수 있습니다~
(해당 이유는 이 [사이트를](https://stackoverflow.com/questions/69542496/spring-boot-slf4j-logging-behavior-differs-in-test-and-in-real-application) 참고했습니다.)
 Sysout은 I/O 작업이 발생하여 지양하는것이 좋습니다. 아니면 테스트 스콥에 롬복을 추가하여 로그를 남길 수 있습니다.
```
testCompileOnly 'org.projectlombok:lombok'
testAnnotationProcessor 'org.projectlombok:lombok'
```

2023-09-21 12:55 UTC, f-lab-maverick requested changes
확인하였습니다. 리뷰 참고하셔서 코드 수정 후 다시 요청해주세요~

2023-09-21 12:55 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket/service/TicketService.java
> +        }
예외메세지와 실제 예외조건이 달라보이네요. `CollectionUtils.isEmpty(remainsTicketList)` 가 콘서트 시퀀스 정보가 없는것과는 관계가 없어보입니다~

2023-09-21 12:55 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +            return Collections.emptyList();
예외를 발생시켜야하는 상황과 잔여티켓 조회가 불가능할 때 0개 남은것으로 보여주는건 다른 비즈니스 로직으로 보이네요. 예외가 발생했을 때 0개 남은것으로 컬랙션을 내려주는게 적절한 비즈니스 로직을 처리한 것일까요?

2023-09-21 12:55 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +        @TestFactory
문서에서 좋은 기능을 찾으셨네요~ 👍

2023-09-21 12:55 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +                        lockTicketRowRecord();
오히려 for문을 돌면서 executors.submit을 호출하도록 변경해야할거같네요. 이렇게 for문으로 처리를 시키면 하나의 스레드가 100번 호출할것으로 보입니다.

2023-09-21 12:55 UTC, f-lab-maverick commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +                System.out.println("티켓 집계 조회 : " +   TimeUnit.MILLISECONDS.convert((end - start), TimeUnit.NANOSECONDS) + " millis");
티케팅과 집계조회를 같은 스레드풀로 동기화없이 사용하고있네요. 이러면 집계조회 작업을 다른 스레드가 작업하느라 티케팅에도 영향을 미치지 않을까요?

2023-09-22 03:12 UTC, gutenLEE commented on src/main/resources/mapper/TicketMapper.xml
> +           OR cancelled_flag = 1
mysql 이 bool 타입은 0, 1로 저장이 되서 똑같이 0, 1로 했는데
헷갈리지 않게 true, false 로 쓰겠습니다

2023-09-22 03:14 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +        @DisplayName("티켓 예매중 티켓 집계 조회시 데드락이 아니라면 소요 시간은 1000 밀리 세컨드 이하")
테스트 케이스 의도가 예매중 `SELECT ~ FOR UPDATE` 쿼리가 대량으로 발생하는 특정 상황에
집계 쿼리 영향을 테스트하려고 했습니다. 
정상조회라는 단어도 넣어서 의미를 더 명확하게 하겠슴다

2023-09-22 03:15 UTC, gutenLEE commented on src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
> +                        lockTicketRowRecord();
`SELECT ~ FOR UPDATE` 가 100번 발생하는 상황을 만들려 했는데 의도대로 안나왔네요
수정하겠습니다

2023-09-23 09:47 UTC, gutenLEE commented on src/main/resources/mapper/TicketOrderMapper.xml
개행이 들어가버렸네요
돌려놓겠습니다

2023-09-23 12:58 UTC, f-lab-maverick approved these changes
확인하였습니다. 머지해주셔도 좋습니다~

`테스트 부분에서 같은 스레드풀에서 집계와 티켓팅을 동시에 처리하면
왜 문제가 되는지 아직 감을 못잡습니다.` 라는 질문에 답변을 드리자면, 테스트 환경은 격리되어야 하고 한번에 하나의 테스트만 실행해야 하기 때문입니다.

티케팅에 대한 작업을 스레드풀에 요청하고, 집계 로직을 동일한 스레드풀에 요청하였을 경우 '티케팅', '집계' 두가지가 동일한 테스트 안에서 동작하게 됩니다. 그럴경우 이 테스트가 깨지면 정확히 어떤 로직이 깨지는 것인지 확인하기 어려워집니다. 테스트의 목적이 모호해 지는 문제가 생기는거죠

이를 방지하는 방법중 하나는 테스트의 목표를 단 하나로 설정하는 것입니다. '티케팅' 테스트, '집계' 테스트를 각각 만들어 둔 후 이 두가지를 동시에 하는 테스트가 같이 존재한다면 테스트가 실패할 때 정확히 어떤 부분이 실패하는 것인지를 알 수 있습니다.

2023-09-23 12:58 UTC, f-lab-maverick commented on src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
> +        }
띄어쓰기가 중복으로 들어갔네요~

2023-09-23 13:20 UTC, gutenLEE commented
> 확인하였습니다. 머지해주셔도 좋습니다~
> 
> `테스트 부분에서 같은 스레드풀에서 집계와 티켓팅을 동시에 처리하면 왜 문제가 되는지 아직 감을 못잡습니다.` 라는 질문에 답변을 드리자면, 테스트 환경은 격리되어야 하고 한번에 하나의 테스트만 실행해야 하기 때문입니다.
> 

아...스레드풀도 테스트 환경 격리가 적용되어야 하네요 ! 감사합니다

2023-10-06 05:38 UTC, merged