Feat/71/common response
f-lab-edu/heeverse-ticket pull request #73
Opened 2023-10-06 17:49 UTC by gutenLEE

## 개요
- 관련 Issue 번호 :  #71 

## 작업사항

- 정상 응답 통일화 : ResponseEntity
- 에러 응답 통일화 : Error핸들러 & 공통 ErrorResponse

## 변경로직

### 변경전
- POST 요청 성공시 created 상태만 반환

### 변경후
- PRG 패턴으로 중복 요청 방지를 위해 Redirect 추가

2023-10-06 18:20 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> -    @ResponseStatus(HttpStatus.CREATED)
@ZhenxiKim 
찾아보니 `ResponseEntity` 가  HttpStatus, HttpHeaders, HttpBody를 포함하는 클래스라고 하여
`@ResponseStatus`는 제거하는건 어떨까요?

2023-10-06 18:20 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> +            @AuthenticationPrincipal Member member) throws Exception {
이 어노테이션을 선언하면 Contoller로 Requset의 파라미터를 처리해주는 `AuthenticationPrincipalArgumentResolver`에서
`Authentication.getPrincipal()`을 수행해준다고 합니다.

```java
Allows resolving the Authentication.getPrincipal() using the AuthenticationPrincipal annotation. For example, the following Controller:
 @Controller
 public class MyController {
     @RequestMapping("/user/current/show")
     public String show(@AuthenticationPrincipal CustomUser customUser) {
         // do something with CustomUser
         return "view";
     }
 }
``` 
[링크 : AuthenticationPrincipalArgumentResolver](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/bind/support/AuthenticationPrincipalArgumentResolver.html)

2023-10-06 18:20 UTC, gutenLEE commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> +                .body(ticketOrderFacade.startTicketOrderJob(dto, member.getSeq()));
HTTP POST 요청을 2xx 으로 바로 리턴할 경우 
새로고침으로 동일 중복 처리 발생할 수 있어 GET 방식의 웹페이지로 리다이렉트 하는 패턴을 사용합니다. 
티켓 예매의 경우 새로고침을 해도 비즈니스 로직상 중복 예매가 발생하지 않지만
안전하게 적용해봤습니다.

[Post/Redirect/Get](https://en.wikipedia.org/wiki/Post/Redirect/Get)

2023-10-06 18:20 UTC, gutenLEE commented on src/main/java/com/heeverse/common/exception/GlobalExceptionHandler.java
`@RestControllerAdvice`로 Global Error 핸들러를 만들어봤는데요, 
도메인별로 나누는 게 좋을지 한 곳에 모을 지 고민이 많이 되네요.
한 곳에 모아야 Http 상태별로 분류하기 좋을 듯 하여 모아놨습니다.

2023-10-06 18:20 UTC, gutenLEE commented on src/main/java/com/heeverse/common/exception/ErrorMessage.java
http 분류별로 공통된 message를 사용하려고 만들었습니다. 
아직은 4xx, 5xx 크게 두 분류인데 피드백을 통해 세분화가 필요하면 더 나누겠습니다.

2023-10-06 18:20 UTC, gutenLEE commented on src/test/java/com/heeverse/common/ControllerExceptionUnitTest.java
> +    }
이 경우만 mocking이 적용 안되어 원인 파악중입니다

2023-10-07 05:23 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> -    @ResponseStatus(HttpStatus.CREATED)
세밀한 응답을 리턴할 수 있어서 ResponseEntity로 변경하는 것도 좋을 것 같습니다~

2023-10-07 05:39 UTC, ZhenxiKim commented on src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
> +                .body(ticketOrderFacade.startTicketOrderJob(dto, member.getSeq()));
이런 경우도 있겠군요 좋습니다~

2023-10-07 05:40 UTC, ZhenxiKim reviewed
리뷰완료했습니다.

2023-10-07 06:00 UTC, ZhenxiKim commented on src/main/java/com/heeverse/common/exception/GlobalExceptionHandler.java
도메인을 나타내는 enum 파라미터 속성이 있는 부모 클래스를 상속받아 global error handling시 도메인을 나타낼 수 있을 것 같습니다.

2023-10-07 06:04 UTC, ZhenxiKim commented on src/main/java/com/heeverse/common/exception/ErrorMessage.java
4xx, 5xx상태에 대한 공통의 메세지가 리턴되면 비즈니스 로직에서 발생된 상세 exception 내용이 전달되지않아 상세한 내용파악이 힘들지 않을까요?

2023-10-07 08:45 UTC, gutenLEE commented on src/main/java/com/heeverse/common/exception/ErrorMessage.java
어플리케이션 내부라면 비즈니스 로직의 상세 예외 내용을 전달하는게 좋지만
클라이언트에게 노출하는 예외 메세지는 어느 정도 유형별로 분류해서 일관된 메세지가 나가야하지 않을까 고민해봤습니다!
지금은 너무 크게 분류해서 말씀해주신대로 더 자세하게 분류할 필요가 있을 것 같습니다!

2023-10-07 08:45 UTC, gutenLEE commented on src/main/java/com/heeverse/common/exception/GlobalExceptionHandler.java
아 이것도 좋은방법이네요

2023-10-08 02:50 UTC, f-lab-maverick requested changes
리뷰 확인해주시고 다시 요청부탁드려요~

2023-10-08 02:50 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/IndexController.java
> +    @GetMapping(INDEX_URI)
URL을 상수화하셨군요~ 이렇게 관리하게된 계기가 있을까요?

2023-10-08 02:50 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/exception/ErrorMessage.java
서버쪽에서 난 에러를 클라이언트에게 그대로 전달하는것은 위험성이 있습니다.
별도 에러메세지를 가진 리턴값으로 전달해주어야 합니다~

2023-10-08 02:50 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/exception/ErrorMessage.java
> +    }
`early return pattern`을 적용해보시겠어요? else if를 사용하는 순간 코드의 가독성이 떨어지게됩니다.

2023-10-08 02:50 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/exception/GlobalExceptionHandler.java
여기서 정의한 예외 이외에 발생하는 예외에 대해서도 처리해주어야 합니다. 예를 들어, NPE가 발생했을 때 에러 핸들링이 안된다면 공통 에러 포맷이 깨져버릴 수 있기 때문입니다~

2023-10-08 02:50 UTC, f-lab-maverick commented on src/test/java/com/heeverse/common/ControllerExceptionUnitTest.java
> +    private final String 잔여_티켓_집계 = "/ticket-order/remains";
URI의 변수 명이 한글과 영어가 섞여있네요~ 한가지로 통일해주세요.

2023-10-08 02:50 UTC, f-lab-maverick commented on src/test/java/com/heeverse/common/ControllerExceptionUnitTest.java
> +@WebMvcTest
`@WebMvcTest`, `@SpringBootTest`는 어떤 차이가 있을까요?

2023-10-08 02:50 UTC, f-lab-maverick commented on src/test/java/com/heeverse/common/ControllerExceptionUnitTest.java
> +    }
원인 확인해서 잘 정리해주세요~ 티케팅 로직이 다른 로직과 다른 부분이 있어서 그런것같네요.

2023-10-08 02:50 UTC, f-lab-maverick commented on src/test/java/com/heeverse/common/ControllerExceptionUnitTest.java
꼼꼼한 테스트 작성 좋습니다 👍

2023-10-09 14:23 UTC, gutenLEE commented on src/main/java/com/heeverse/common/IndexController.java
> +    @GetMapping(INDEX_URI)
redirect용 페이지이므로 url 재사용이 높을 것으로 생각되어 하드코딩보단 static 변수로 선언하였습니다

2023-10-10 03:34 UTC, gutenLEE commented on src/test/java/com/heeverse/common/ControllerExceptionUnitTest.java
> +    }
Stub 내부코드로 Stub의 올바른 사용법을 알게되었습니다. 
### Stub?
Stub은 **어떤 입력에 대해 어떤 출력이 발생하는지 검증**하는 용도로 사용하는 test double입니다. 

### Stub 내부 동작 프로세스
Stub의 내부 동작 프로세스를 요약하면 아래와 같습니다.
```
1. 개발자가 작성한 Stub 내용, 즉 호출 메서드 정보, 입력 값, answer를 저장한다. 
2. Stub한 메서드가 호출되면 프록시 객체가 메서드 호출을 인터셉트해서 메서드 호출 내용과 Stub 정보가 일치하는지 검사한다.
3. 일치하면 1번에서 저장한 answer를 리턴한다. 
4. 불일치하면 default answer를 리턴한다. 
```

### 원인 1. `InvocationContainerImpl.findAnswerFor(Invocation)`
Mock 객체의 호출 및 검증을 수행하는 InvocationContainerImpl 클래스에서 
Stub 객체에 지정한 answer를 조회하여 리턴해 주는데, `findAnswerFor()`가 이 역할을 수행합니다.  
이 메서드 내부에서 실제 호출된 메서드와 Stub내용이 일치하는지 검증 코드가 있습니다. 
<img width="400" alt="findAnswerFor" src="https://github.com/f-lab-edu/heeverse-ticket/assets/61870748/fd4c5194-9680-4fd3-910e-2c3d350f366d">

디버깅 결과 메서드 argument가 Stub내용과 달라 검증단계 요건을 충족하지 못한게 원인이였습니다. 
 
```shell
// stubbed 내용
com.heeverse.ticket_order.service.TicketOrderFacade#0 bean.startTicketOrderJob(
    <any>,
    <any long>
); stubbed with: [org.mockito.internal.stubbing.answers.

// 실제 타깃 메서드 invocation 내용
com.heeverse.ticket_order.service.TicketOrderFacade#0 bean.startTicketOrderJob(
    TicketOrderRequestDto[ticketSetList=[1]],
    null
);
``` 
- Stub한 메서드 정보는 `startTicketOrderJob(any, any long)`
- 실제 메서드 호출 정보는 `startTicketOrderJob(any, null)`

두 번째 파라미터 입력 정보가 불일치했습니다. 

### 원인 2. 왜 Http Status가 201인가?
실제 메서드 호출 정보와 Stub 내용과 일치하지 않으면 실제 메서드가 호출된건가? 
그렇다면 왜 두번째 파라미터가 null로 인한 예외가 발생하지 않았는가? 의문이 들었습니다. 

디버깅을 더 해본 결과 Stub되지 않은 것으로 간주되면 Default 값을 리턴해주고 있었습니다. 
<img width="654" alt="answer_default_value" src="https://github.com/f-lab-edu/heeverse-ticket/assets/61870748/d1c8a4df-03e6-4307-bc26-1779bba1aa90">
정리하자면 Stubbing 한 `startTicketOrderJob()` 메서드에 정의된 answer가 없는 것으로 간주하고
해당 메서드 리턴 타입의 기본값을 반환해 준 것입니다. 

### 해결
Stub 객체 `startTicketOrderJob(any, any long)` 시나리오대로 동작하도록 
Member 객체 생성자에는 seq를 파라미터로 받지 않고 있어 mocking 하는 것으로 변경했습니다.  
```java
// Member mock = new Member(faker.book().author(), withMockMember.password(), withMockMember.userName(), withMockMember.email());
Member mock = mock(Member.class);
``` 
추가로 사용자 정의 타입을 mocking하면 클래스 내부의 메서드에 대해서도 stub이 적용되어 
`member.getSeq()`가 호출되면 기본값이 반환됩니다.

### 결론
Stub을 의도대로 사용하지 않아 발생한 이슈였습니다. 
Stub은 **어떤 입력에 대해 어떤 출력이 발생하는지 검증** 할 때 사용한다!

2023-10-10 06:30 UTC, gutenLEE commented on src/test/java/com/heeverse/common/ControllerExceptionUnitTest.java
> +@WebMvcTest
공식문서로 비교해보면 둘의 차이점은 실제 HTTP 통신과 컨텍스트 부트스트랩 범위에 있습니다.
1. 실제 HTTP 통신
`@SpringBootTest`는 웹 서버를 구동해 실제 HTTP 통신을 수행합니다. 통합테스트에 사용하는 이유입니다.
`@WebMvcTest`는 실제 HTTP 통신은 이뤄지지 않고 MockMvc로 요청과 응답을 mocking하여 결과만 반환합니다. 

> Provides support for different [webEnvironment](https://docs.spring.io/spring-boot/docs/3.1.2/api/org/springframework/boot/test/context/SpringBootTest.html#webEnvironment()) modes, including _**the ability to start a fully running web server**_ listening on a [defined](https://docs.spring.io/spring-boot/docs/3.1.2/api/org/springframework/boot/test/context/SpringBootTest.WebEnvironment.html#DEFINED_PORT) or [random](https://docs.spring.io/spring-boot/docs/3.1.2/api/org/springframework/boot/test/context/SpringBootTest.WebEnvironment.html#RANDOM_PORT) port.

> @WebMvcTest also auto-configures MockMvc. Mock MVC offers a powerful way to quickly test MVC controllers _**without needing to start a full HTTP server.**_

2. 컨텍스트 부트스트랩
`@SpringBootTest`는 `SpringBootTestContextBootstrapper`로 완전한 ApplicationContext를 로딩합니다. 
그러나 `@WebMvcTest`는 `WebMvcTestContextBootstrapper`로 컨트롤러와 관련된 일부만 로드를 로딩하여 웹 계층 단위테스트가 필요하다면  `@SpringBootTest`보다 가볍게 테스트를 돌릴 수 있습니다.

2023-10-10 12:27 UTC, gutenLEE commented on src/test/java/com/heeverse/docs/ControllerResponseUnitTest.java
> +                )).collect(Collectors.toList());
Response 메세지를 만들기 위해 필요한 데이터를 모두 생성했더니 
가독성이 떨어지네요.. 리팩토링 하겠습니다.

2023-10-10 14:33 UTC, gutenLEE commented on src/main/java/com/heeverse/common/exception/ErrorMessage.java
> +    }
early return pattern 적용해봤습니다. 
early return pattern의 장점으로 코드 가독성뿐만 아니라 fail fast 전략으로 견고한 코드를 작정할 수 있다는 것을 알게되었네요

2023-10-10 15:13 UTC, gutenLEE commented on src/test/java/com/heeverse/docs/ControllerResponseUnitTest.java
> +    }
파라미터로도 @Autowired 적용 가능합니다!

![image](https://github.com/f-lab-edu/heeverse-ticket/assets/61870748/5135a9d0-f192-4b85-a920-5e3067ad69a5)

2023-10-11 04:42 UTC, gutenLEE commented on src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
> +        return Arrays.stream(urlArr).anyMatch(pattern -> pathMatcher.match(pattern, path));
@ZhenxiKim 

`AntPathMatcher` 을 사용하면 단순 문자열 비교보다 path 패턴으로 매칭해줘서
유연하게 url pattern 문자열 지정이 가능한게 장점같습니다. 

> The mapping matches URLs using the following rules:
> `?` matches one character
> `*` matches zero or more characters
> `**` matches zero or more 'directories' in a path

2023-10-11 06:55 UTC, gutenLEE commented on src/main/java/com/heeverse/common/util/HttpStatusUtil.java
>  public class HttpStatusUtil {
`@UtilityClass` 적용했습니다. 

Util클래스를 위한 부가적인 코드를 자동 생성해줘 편하네요.
컴파일된 클래스 내용을 보니 클래스에 `final` 선언, `private` 생성자를 추가해줍니다.
```java
public final class HttpStatusUtil {
    public static boolean isError(HttpStatus status) {
        return !status.is2xxSuccessful();
    }

    public static boolean isNull(HttpStatus status) {
        return status == null;
    }

    private HttpStatusUtil() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }
}

```

2023-10-11 06:55 UTC, gutenLEE commented on src/main/java/com/heeverse/common/util/RegexUtils.java
@ZhenxiKim 
`@UtilityClass`  적용해봤습니다!

2023-10-11 11:56 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 머지해주셔도 좋습니다.

2023-10-11 11:56 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/exception/ErrorMessage.java
에러에 대한 상수화를 하셨군요~ 👍👍

2023-10-11 11:56 UTC, f-lab-maverick commented on src/main/java/com/heeverse/common/util/HttpStatusUtil.java
> +//@NoArgsConstructor(access = AccessLevel.PRIVATE)
필요하지 않은 주석은 제거해주세요.

2023-10-11 11:56 UTC, f-lab-maverick commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +                        .requestMatchers("/docs/**").permitAll()
`/docs/**`에 해당하는 모든 HTTP Method가 허용되어야 할 이유가 있을까요?

2023-10-11 11:56 UTC, f-lab-maverick commented on src/test/java/com/heeverse/docs/ControllerResponseUnitTest.java
> +    private static final Random random = new Random();
랜덤난수를 사용할 때에는 `ThreadLocalRandom`과 `SplittableRandom`, `SecureRandom`중 하나를 사용하는 것이 좋습니다. `Random`클래스의 여러가지 이슈를 개선한 것이기 때문에 이 세가지 랜덤 클래스를 찾아보시겠어요? `Random`클래스는 어떤 문제가 있을까요?

2023-10-11 11:56 UTC, f-lab-maverick commented on src/test/java/com/heeverse/docs/ControllerResponseUnitTest.java
> +        List<TicketOrderResponseDto> orderResponseDtos = givenTicketOrderResponse(concertSeq);
사소한 것이지만 이런 변수를 선언할 때에는 변경될 일이 없다면 모두 `final`처리를 통해 불변성을 보장해주는 것이 좋습니다~

2023-10-11 11:56 UTC, f-lab-maverick commented on src/test/java/com/heeverse/docs/WebMvcTestForRestDocs.java
> +public @interface WebMvcTestForRestDocs {
공통 어노테이션 추출 좋습니다 👍

2023-10-11 13:21 UTC, f-lab-maverick commented on src/test/java/com/heeverse/common/ControllerExceptionUnitTest.java
> +    }
좋습니다~ 이제 트러블슈팅때도 내부 코드를 보고 잘 디버깅해주시네요.
이렇게 디버깅하다가 라이브러리 자체에 버그가 있는걸 찾으신다면 이제 오픈소스 라이브러리에도 컨트리뷰터가 되실 수 있을겁니다.

2023-10-12 05:03 UTC, gutenLEE commented on src/main/java/com/heeverse/config/SecurityConfig.java
> +                        .requestMatchers("/docs/**").permitAll()
아하 필요한 GET에 대해서만 허용되도록 변경하겠습니다.

2023-10-12 11:01 UTC, merged